// TikTok capture — runs in the PAGE's MAIN world at document_start.
//
// Unlike Instagram (parses feed JSON on the main thread → JSON.parse hook),
// TikTok reads its API responses with `fetch().json()` — native parsing that a
// JSON.parse monkey-patch never sees (verified live: 0/167 caught). So we tee
// the RESPONSE BODIES of TikTok's own fetch/XHR calls instead. This is passive:
// we only read what the page already requested — no forged/signed requests, so
// no msToken/X-Bogus/X-Gnarly and no account-flagging risk.
//
// Hooking at document_start is not a nicety. TikTok's bundle captures the
// original `fetch` reference as it loads, so a hook installed even a second late
// catches nothing at all (measured 2026-08-16 with a page-level probe: 0 item
// calls, only telemetry).
//
// We relay compact records to our isolated bridge via window.postMessage (the two
// worlds share the DOM, not JS).

(function () {
  if (window.__fbwTtMainInit) return;
  window.__fbwTtMainInit = true;

  // Endpoints worth teeing.
  //
  // SEARCH_RE is separate from VIDEO_RE because the search family does not fit
  // the /<noun>/item_list shape at all: the default "Melhores" tab is
  // /api/search/general/full/ and the "Vídeos" tab is /api/search/item/full/.
  // Neither matched the old pattern, so the whole search surface — the one a
  // hashtag lands on — captured nothing. (docs/research/tiktok-data-map.md)
  const VIDEO_RE = /\/api\/(?:post|recommend|related|challenge|user)\/(?:item_list|item)\b/;
  const SEARCH_RE = /\/api\/search\/(?:general|item|video)\/(?:full|preview)\b/;
  const USER_RE = /\/api\/(?:search\/user\/full|user\/detail)\b/; // creator stats
  const MIX_RE = /\/api\/(?:mix|collection)\/item_list\b/; // playlist / collection videos
  const STORY_RE = /\/api\/story\/item_list\b/;
  const LISTMETA_RE = /\/api\/user\/(?:playlist|collection_list)\b/; // playlist/collection metadata
  const COMMENT_RE = /\/api\/comment\/list\b/;
  const interesting = (u) =>
    typeof u === "string" &&
    (VIDEO_RE.test(u) ||
      SEARCH_RE.test(u) ||
      USER_RE.test(u) ||
      MIX_RE.test(u) ||
      STORY_RE.test(u) ||
      LISTMETA_RE.test(u) ||
      COMMENT_RE.test(u));

  const num = (v) => (v == null ? null : typeof v === "number" ? v : (Number.isFinite(+v) ? +v : null));

  // The payload → record mapping is GENERATED from src/lib/shared/ttItems.js —
  // the isolated bridge inlines the same copy for the SSR path, which is how the
  // two stopped drifting. Run `npm run gen:inline` after editing the source.
// <<< inline:src/lib/shared/ttItems.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/ttItems.js and run `npm run gen:inline`.
// TikTok payload → lite record. Canonical source, INLINED into the TikTok capture
// scripts — see ./README.md before editing (no imports allowed in this file).
//
// WHY THIS EXISTS. Two copies of this mapping had already grown apart:
// tt-capture.js's `liteItem` (for fetch/XHR payloads) and tt-relay.js's `mapItem`
// (for the SSR hydration blob on a /video/ page). Both read the SAME webapp item
// struct; only their entry points differ.
//
// It also fixes a live blind spot found on 2026-08-16 (see
// docs/research/tiktok-data-map.md): the TikTok SEARCH surface produced ZERO
// records, for two independent reasons —
//
//   * /api/search/general/full/ (the default "Melhores" tab) answers with
//     `data[] → {type, item}`, and /api/search/item/full/ (the "Vídeos" tab)
//     answers with `item_list` — while the reader only ever looked at `itemList`
//     and `items`;
//   * neither URL matched the endpoint regex in the first place.
//
// And it stops throwing away `authorStats`, which every list payload carries.
// That is the follower count — the denominator behind "did well FOR an account
// this size" — and on Instagram it costs a separate enrichment round-trip.

const ttNum = (v) => (v == null ? null : typeof v === "number" ? v : Number.isFinite(+v) ? +v : null);

/**
 * Every list-shaped root TikTok answers with, flattened to raw items.
 *   itemList   /api/post|recommend|related|challenge/item_list/  (camelCase)
 *   item_list  /api/search/item/full/                            (snake_case)
 *   data[]     /api/search/general/full/  → {type, item, common}; type 1 = video,
 *              other types are user/live cards and carry no `item`
 */
function ttItemsIn(obj) {
  if (!obj || typeof obj !== "object") return [];
  const direct = obj.itemList || obj.item_list || obj.items;
  if (Array.isArray(direct)) return direct.filter(Boolean);
  if (Array.isArray(obj.data))
    return obj.data.map((d) => (d && typeof d === "object" ? d.item || null : null)).filter(Boolean);
  return [];
}

/**
 * Creator records: /api/search/user/full/ → `user_list[].user_info`, and
 * /api/user/detail/ → `userInfo.{user,stats}` (a different shape entirely, so it
 * is normalized here rather than at each call site).
 */
function ttUsersIn(obj) {
  if (!obj || typeof obj !== "object") return [];
  const out = [];
  if (Array.isArray(obj.user_list))
    for (const e of obj.user_list) if (e && e.user_info) out.push(e.user_info);
  const ui = obj.userInfo;
  if (ui && ui.user) out.push({ ...ui.user, __stats: ui.stats || ui.statsV2 || null });
  return out;
}

/**
 * Highest-quality rendition: max resolution first, then max bitrate.
 * bitrateInfo[0] is TikTok's default gear, not its best — a 1080 gear usually
 * sits deeper in the ladder. Returns { url, width, height, codec, bitrate } or null.
 */
function ttBestBitrate(video) {
  const gears = Array.isArray(video && video.bitrateInfo) ? video.bitrateInfo : [];
  let best = null;
  for (const g of gears) {
    const pa = (g && g.PlayAddr) || {};
    const url = (pa.UrlList && pa.UrlList[0]) || null;
    if (!url) continue;
    const area = (ttNum(pa.Width) || 0) * (ttNum(pa.Height) || 0);
    const score = area * 1e6 + (ttNum(g.Bitrate) || 0);
    if (!best || score > best.score)
      best = { url, width: ttNum(pa.Width), height: ttNum(pa.Height), codec: g.CodecType || null, bitrate: ttNum(g.Bitrate), score };
  }
  return best;
}

/**
 * The caption track to transcribe from — a direct WebVTT URL, which skips Whisper
 * entirely. Prefer an English track, else the first.
 *
 * Two places carry the same URLs: `video.subtitleInfos` (LanguageCodeName/Url) and
 * `video.claInfo.captionInfos` (languageCode/url). Measured on the search grid,
 * both were present or both absent together — but claInfo is read as a fallback
 * because it is the one the video-detail SSR blob is documented to always carry.
 */
function ttBestSubtitle(video) {
  const v = video || {};
  const subs = Array.isArray(v.subtitleInfos) ? v.subtitleInfos : [];
  const pick = subs.find((s) => /eng/i.test((s && s.LanguageCodeName) || "")) || subs[0];
  if (pick) {
    const url = pick.Url || (Array.isArray(pick.UrlList) && pick.UrlList[0]) || null;
    if (url)
      return {
        url,
        lang: pick.LanguageCodeName || null,
        format: String(pick.Format || "webvtt").toLowerCase(),
        source: pick.Source || null,
      };
  }
  const caps = Array.isArray(v.claInfo && v.claInfo.captionInfos) ? v.claInfo.captionInfos : [];
  const cap = caps.find((c) => /eng/i.test((c && c.language) || "")) || caps[0];
  if (cap) {
    const url = cap.url || (Array.isArray(cap.urlList) && cap.urlList[0]) || null;
    if (url)
      return {
        url,
        lang: cap.language || null,
        format: String(cap.captionFormat || "webvtt").toLowerCase(),
        source: String(cap.isAutoGen) === "True" ? "ASR" : null,
      };
  }
  return null;
}

/** Hashtags, from `challenges` when present and from `textExtra` otherwise. */
function ttHashtags(it) {
  const out = [];
  const seen = new Set();
  const push = (t) => {
    const name = String(t || "").trim();
    if (!name || seen.has(name.toLowerCase())) return;
    seen.add(name.toLowerCase());
    out.push(name);
  };
  if (Array.isArray(it.challenges)) for (const c of it.challenges) push(c && c.title);
  if (Array.isArray(it.textExtra)) for (const t of it.textExtra) push(t && t.hashtagName);
  return out;
}

/**
 * One webapp item struct → the record the panel and the page overlay both read.
 * Every field degrades to null rather than to a wrong value.
 */
function ttLiteItem(it) {
  if (!it || typeof it !== "object") return null;
  const v = it.video || {};
  const a = it.author || {};
  const s = it.statsV2 || it.stats || {};
  const as = it.authorStatsV2 || it.authorStats || {};
  const m = it.music || {};
  const hd = ttBestBitrate(v);
  const sub = ttBestSubtitle(v);
  const id = String(it.id || v.id || "");
  if (!id) return null;
  return {
    __kind: "video",
    id,
    username: a.uniqueId || null,
    nickname: a.nickname || null,
    author_id: a.id ? String(a.id) : null,
    author_sec_uid: a.secUid || null,
    author_avatar: a.avatarThumb || a.avatarMedium || null,
    author_verified: a.verified === true ? true : a.verified === false ? false : null,
    author_bio: a.signature || null,
    author_private: a.privateAccount === true ? true : a.privateAccount === false ? false : null,
    // Creator size, inline on every list payload. Instagram needs a separate
    // enrichment fetch for the same number; TikTok hands it over for free, which
    // is what makes views/follower cheap here.
    user_follower_count: ttNum(as.followerCount),
    user_following_count: ttNum(as.followingCount),
    user_heart_count: ttNum(as.heartCount != null ? as.heartCount : as.heart),
    user_video_count: ttNum(as.videoCount),
    play_count: ttNum(s.playCount),
    digg_count: ttNum(s.diggCount),
    comment_count: ttNum(s.commentCount),
    share_count: ttNum(s.shareCount),
    collect_count: ttNum(s.collectCount),
    repost_count: ttNum(s.repostCount),
    video: v.playAddr || null,
    // Highest-quality URL for downloads. downloadAddr is missing on roughly half
    // the search results (measured), so the gear ladder leads and playAddr is the
    // floor — it is present on every item seen.
    hd_url: (hd && hd.url) || v.downloadAddr || v.playAddr || null,
    hd_res: hd && hd.width && hd.height ? `${hd.width}x${hd.height}` : null,
    download_url: v.downloadAddr || v.playAddr || null,
    subtitle: sub,
    cover: v.cover || v.originCover || null,
    dynamic_cover: v.dynamicCover || null,
    duration: ttNum(v.duration),
    width: ttNum(v.width),
    height: ttNum(v.height),
    desc: (it.desc || "").slice(0, 500) || null,
    create_time: ttNum(it.createTime),
    music: m.title
      ? {
          title: m.title,
          author: m.authorName || null,
          id: m.id ? String(m.id) : null,
          url: m.playUrl || null,
          original: m.original === true || m.original === "True" || null,
          duration: ttNum(m.duration),
        }
      : null,
    hashtags: ttHashtags(it),
    // Only the video page carries these; a grid record simply has them as null.
    location: it.locationCreated || null,
    topics: Array.isArray(it.diversificationLabels) ? it.diversificationLabels.filter(Boolean) : [],
    suggested_words: Array.isArray(it.suggestedWords) ? it.suggestedWords.filter(Boolean) : [],
    is_ad: it.isAd === true || null,
    is_aigc: it.IsAigc === true || !!it.AIGCDescription || null,
    pinned: !!it.isPinnedItem,
  };
}

/** One creator record, from either creator shape ttUsersIn produces. */
function ttLiteUser(u) {
  if (!u || typeof u !== "object") return null;
  const st = u.__stats || {};
  const id = String(u.uid || u.id || "");
  const username = u.unique_id || u.uniqueId || null;
  if (!id && !username) return null;
  return {
    __kind: "tt_user",
    author_id: id || null,
    username,
    nickname: u.nickname || null,
    bio: u.signature || null,
    sec_uid: u.sec_uid || u.secUid || null,
    verified: u.verified === true || !!u.custom_verify || null,
    follower_count: ttNum(st.followerCount != null ? st.followerCount : u.follower_count),
    following_count: ttNum(st.followingCount != null ? st.followingCount : u.following_count),
    heart_count: ttNum(st.heartCount != null ? st.heartCount : (st.heart != null ? st.heart : u.total_favorited)),
    video_count: ttNum(st.videoCount != null ? st.videoCount : u.aweme_count),
  };
}

/**
 * Which TikTok surface a record belongs to. Decided WHERE AND WHEN the record is
 * captured, never at relay time — Instagram learned that the hard way: a replay
 * resends everything the capture ever saw, so stamping the live surface relabels
 * another profile's videos as the one you happen to be looking at now.
 */
function ttSurfaceKey(path, search) {
  const p = path != null ? path : (typeof location !== "undefined" ? location.pathname : "/");
  const q = search != null ? search : (typeof location !== "undefined" ? location.search : "");
  let m;
  if ((m = p.match(/^\/@([^/]+)/))) return "profile:" + decodeURIComponent(m[1]).toLowerCase();
  if ((m = p.match(/^\/tag\/([^/]+)/))) return "tag:" + decodeURIComponent(m[1]).toLowerCase();
  if (p.startsWith("/search")) {
    const k = new URLSearchParams(q || "").get("q");
    return "search:" + (k ? k.toLowerCase() : "");
  }
  if (p.startsWith("/foryou") || p === "/") return "feed";
  if (p.startsWith("/explore")) return "explore";
  return "feed";
}
// >>> inline:end

  function liteComment(c) {
    const u = c.user || {};
    return {
      __kind: "comment",
      cid: String(c.cid || c.id || ""),
      aweme_id: String(c.aweme_id || ""),
      text: (c.text || "").slice(0, 2000),
      digg_count: num(c.digg_count),
      reply_count: num(c.reply_comment_total != null ? c.reply_comment_total : c.reply_comment_count),
      username: u.unique_id || null,
      nickname: u.nickname || null,
      create_time: num(c.create_time),
      // Replies carry a reply_id (parent). Top-level comments have reply_id "0"/absent.
      is_reply: !!(c.reply_id && c.reply_id !== "0"),
      parent: c.reply_id && c.reply_id !== "0" ? String(c.reply_id) : null,
    };
  }

  const sentVid = new Map(); // id -> signature (skip resends of unchanged records)
  const allVid = new Map(); // id -> record, for replay
  const sentCom = new Set(); // cid, dedup
  const allCom = new Map(); // cid -> record, for replay
  const allUsr = new Map(); // author_id/username -> creator record, for replay

  function send(records) {
    if (records.length) window.postMessage({ __fbwTt: true, records }, location.origin);
  }

  const qparam = (url, name) => { try { return new URL(url, location.origin).searchParams.get(name); } catch { return null; } };

  function ingest(url, obj) {
    try {
      const out = [];
      const isStory = STORY_RE.test(url);
      const listId = MIX_RE.test(url) ? (qparam(url, "mixId") || qparam(url, "collectionId")) : null;
      // The surface is stamped HERE, where the record was captured — never at
      // relay time. A replay resends everything this world ever saw, so a
      // relay-time stamp relabels profile A's videos as whatever profile you are
      // looking at when the replay lands. (Instagram shipped that bug first.)
      const surface = ttSurfaceKey();
      for (const it of ttItemsIn(obj)) {
        if (!it.stats && !it.statsV2 && !it.video) continue;
        const r = ttLiteItem(it);
        if (!r) continue;
        r.__surface = surface;
        if (isStory) { r.__kind = "tt_story"; r.reel_owner = r.username || null; }
        if (listId) r.list_id = String(listId); // playlist/collection membership
        allVid.set(r.id, r);
        const sig = `${r.__kind}|${r.play_count}|${r.digg_count}|${r.comment_count}|${r.share_count}|${r.collect_count}|${r.user_follower_count}`;
        if (sentVid.get(r.id) !== sig) { sentVid.set(r.id, sig); out.push(r); }
      }
      // Creator records. A profile's /api/user/detail/ and the "Usuários" search
      // tab both land here; the bridge joins them onto every video by that author,
      // which is what fills the follower count in on surfaces whose items don't
      // carry authorStats.
      for (const u of ttUsersIn(obj)) {
        const r = ttLiteUser(u);
        if (!r) continue;
        const key = r.author_id || r.username;
        const prev = allUsr.get(key);
        allUsr.set(key, r);
        if (!prev || prev.follower_count !== r.follower_count) out.push(r);
      }
      // Playlist / collection metadata (the buckets themselves).
      const lists = obj && (obj.playList || obj.playlist || obj.collectionList || obj.collection);
      if (Array.isArray(lists)) {
        for (const L of lists) {
          if (!L) continue;
          const id = String(L.mixId || L.id || L.collectionId || "");
          if (!id) continue;
          out.push({
            __kind: "tt_list",
            list_id: id,
            kind: L.mixId || L.mixName ? "playlist" : "collection",
            name: L.name || L.mixName || L.collectionName || L.title || "Untitled",
            video_count: num(L.videoCount != null ? L.videoCount : (L.total != null ? L.total : L.itemCount)),
            cover: L.cover || L.coverUrl || (L.coverMedia && L.coverMedia.cover) || null,
            owner: (L.creator && L.creator.uniqueId) || null,
          });
        }
      }
      const comments = obj && obj.comments;
      if (Array.isArray(comments)) {
        for (const c of comments) {
          if (!c) continue;
          const r = liteComment(c);
          if (!r.cid) continue;
          allCom.set(r.cid, r);
          if (!sentCom.has(r.cid)) { sentCom.add(r.cid); out.push(r); }
          // Nested reply previews some responses embed under `reply_comment`.
          if (Array.isArray(c.reply_comment)) {
            for (const rc of c.reply_comment) {
              if (!rc) continue;
              const rr = liteComment(rc);
              if (rr.cid && !sentCom.has(rr.cid)) { sentCom.add(rr.cid); allCom.set(rr.cid, rr); out.push(rr); }
            }
          }
        }
      }
      // Cap replay buffers for long SPA sessions (oldest evicts first).
      while (allVid.size > 1200) allVid.delete(allVid.keys().next().value);
      while (sentVid.size > 1200) sentVid.delete(sentVid.keys().next().value);
      while (allCom.size > 2000) allCom.delete(allCom.keys().next().value);
      while (allUsr.size > 400) allUsr.delete(allUsr.keys().next().value);
      // sentCom was missing from this block — it grew forever (MAIN world survives
      // extension reloads), a few dozen bytes per comment id seen.
      while (sentCom.size > 4000) sentCom.delete(sentCom.values().next().value);
      send(out);
    } catch (_) {}
  }

  // ---- fetch tee ----
  const oFetch = window.fetch;
  if (typeof oFetch === "function") {
    window.fetch = function (...args) {
      const url = typeof args[0] === "string" ? args[0] : (args[0] && args[0].url);
      const p = oFetch.apply(this, args);
      if (interesting(url)) {
        p.then((res) => { res.clone().text().then((t) => { try { ingest(url, JSON.parse(t)); } catch {} }).catch(() => {}); }).catch(() => {});
      }
      return p;
    };
  }

  // ---- XHR tee (belt-and-suspenders; TikTok uses fetch today) ----
  const oOpen = XMLHttpRequest.prototype.open;
  const oSend = XMLHttpRequest.prototype.send;
  XMLHttpRequest.prototype.open = function (method, url) { this.__fbwUrl = url; return oOpen.apply(this, arguments); };
  XMLHttpRequest.prototype.send = function () {
    if (interesting(this.__fbwUrl)) {
      this.addEventListener("load", () => {
        try { ingest(this.__fbwUrl, JSON.parse(this.responseText)); } catch {}
      });
    }
    return oSend.apply(this, arguments);
  };

  // ---- the server-rendered blob ----
  //
  // A /video/ page fetches NOTHING for the video it opens on: the item is
  // server-rendered into #__UNIVERSAL_DATA_FOR_REHYDRATION__, so the fetch tee
  // above never sees it. The obvious place to read that is the isolated bridge —
  // and that is where it lived, and it was WRONG: measured 2026-08-16, TikTok
  // removes the script tag once React has hydrated, and on a warm load it was
  // already gone by the time a document_idle script looked (blob: false, while
  // the same page had served it seconds earlier).
  //
  // So it is read HERE, at document_start, polling only until the parser has
  // emitted the tag — long before hydration can strip it. Same ttLiteItem the
  // fetch path uses, so the record is identical either way.
  let ssrDone = false;
  let ssrTicks = 0;
  function readSsr() {
    if (ssrDone) return true;
    const el = document.getElementById("__UNIVERSAL_DATA_FOR_REHYDRATION__");
    if (!el || !el.textContent) return false;
    try {
      const scope = JSON.parse(el.textContent).__DEFAULT_SCOPE__ || {};
      const out = [];
      const it = scope["webapp.video-detail"] && scope["webapp.video-detail"].itemInfo &&
        scope["webapp.video-detail"].itemInfo.itemStruct;
      if (it) {
        const r = ttLiteItem(it);
        if (r) {
          r.__surface = ttSurfaceKey();
          allVid.set(r.id, r);
          out.push(r);
        }
      }
      // A profile page renders its owner the same way — that is the follower
      // count for every video listed on it.
      const ud = scope["webapp.user-detail"];
      if (ud) {
        for (const u of ttUsersIn(ud)) {
          const r = ttLiteUser(u);
          if (!r) continue;
          allUsr.set(r.author_id || r.username, r);
          out.push(r);
        }
      }
      ssrDone = true; // the blob is a one-shot; a SPA navigation refills it
      send(out);
      return true;
    } catch (_) {
      return false;
    }
  }
  // The tag lands mid-parse, so poll briefly rather than waiting for a load event
  // that fires long after hydration could have removed it.
  const ssrTimer = setInterval(() => {
    if (readSsr() || ++ssrTicks > 100) clearInterval(ssrTimer);
  }, 50);
  document.addEventListener("DOMContentLoaded", readSsr, { once: true });
  // An SPA navigation swaps the blob for the next video without a page load.
  let ssrPath = location.pathname;
  setInterval(() => {
    if (location.pathname === ssrPath) return;
    ssrPath = location.pathname;
    ssrDone = false;
    ssrTicks = 0;
    readSsr();
  }, 1000);

  // The isolated bridge attaches at document_idle — after we start capturing. It
  // asks us to replay everything buffered (videos + comments + creators).
  window.addEventListener("message", (e) => {
    if (e.source === window && e.data && e.data.__fbwTtReq)
      send([...allVid.values(), ...allCom.values(), ...allUsr.values()]);
  });
})();
