// TikTok bridge — isolated content-script world.
//
// Receives the MAIN-world fetch/XHR capture (relayed via window.postMessage),
// keeps a surface-scoped video map + a per-video comment store, answers the side
// panel (FBW_TT_LIST / FBW_TT_COMMENTS / FBW_TT_CLEAR), AND injects an on-page
// action overlay (save / download / transcribe / scrape comments / like) so you
// can act on the current video without opening the panel.
//
// Kept import-free on purpose: an ES import would make CRXJS wrap this in a
// dynamic-import loader, which TikTok's strict CSP can kill (that would break all
// capture). So the few helpers it needs are inlined.

if (location.hostname.endsWith("tiktok.com") && !window.__fbwTtInit) {
  window.__fbwTtInit = true;

  // ---- generation takeover ----
  // An extension reload/update re-injects this file into a FRESH isolated world, so
  // the __fbwTtInit guard above does not stop the OLD world — only its chrome.* dies.
  // Without this, every reload left another 1s interval, another scroll listener and
  // another full store running for the page's lifetime. Newer generation announces;
  // older tears itself down. (Same pattern as content/fb/comments-scrape.js.)
  const GEN = Date.now() + ":" + Math.random();
  let disabled = false;
  const onTakeover = (e) => {
    if (e.source !== window || !e.data || e.data.__fbwTtTakeover === undefined) return;
    if (e.data.__fbwTtTakeover === GEN || disabled) return;
    disabled = true;
    clearInterval(overlayInterval);
    clearTimeout(overlayTimer);
    window.removeEventListener("scroll", scheduleOverlay);
    window.removeEventListener("scroll", onLayerScroll, true);
    window.removeEventListener("resize", syncTtLayer);
    window.removeEventListener("message", onRelay);
    window.removeEventListener("message", onTakeover);
    document.removeEventListener("visibilitychange", scheduleOverlay);
    tileObserver.disconnect();
    document.getElementById("sw-tt-acts")?.remove();
    document.getElementById("sw-tt-layer")?.remove();
    document.querySelectorAll(".sw-ttovl, .sw-ttacts").forEach((n) => n.remove());
    ttLayerRails.clear();
    byId.clear();
    comments.clear();
    stories.clear();
    lists.clear();
    ttUsers.clear();
    ttUsersByName.clear();
  };
  window.addEventListener("message", onTakeover);
  window.postMessage({ __fbwTtTakeover: GEN }, "*");

  const byId = new Map(); // aweme id -> record; insertion order preserved for the list
  const comments = new Map(); // aweme_id -> { items: Map<cid, comment> }
  const stories = new Map(); // owner username -> Map<id, story item>  (TikTok stories)
  const lists = new Map(); // list_id -> { meta, items: Map<id, rec> }  (playlists/collections)

  // ================== IN-PAGE OVERLAY SETTINGS ==================
  // Tweak the look of the on-TikTok stats overlay here, then rebuild
  // (`npm run build`) and Reload ↻ the extension. Mirrors OVL in
  // src/content/ig/bridge.js — the two grids are meant to read the same.
  const TT_OVL = {
    bgOpacity: 0.62, // rail background darkness (0–1)
    fontPrimary: 16, // headline (views) font size, px
    fontRow: 12.5, // other rows font size, px
    iconPrimary: 16,
    iconRow: 13,
    glow: "rgba(70,130,255,.28)",
    borderColor: "rgba(150,180,255,.38)",
    radius: 12,
    btnSize: 26,
    gap: 6, // rail distance from the tile edge, px
  };
  // =============================================================

  let overlayOn = true; // sw_tt_overlay — the panel's toggle
  // Starts null, NOT normalizeTtErWeights(null): this line runs at the top of the
  // block while TT_ER_WEIGHTS is declared inside an inlined region further down,
  // and reading it here is a temporal dead zone. ttEngagementRate already falls
  // back to the defaults when handed nothing. (Instagram took its whole bridge
  // down with exactly this, 2026-08-15.)
  let ttErWeights = null;
  // The weights, flattened into a tile's repaint signature. Without this, changing
  // a weight re-ran the render and repainted nothing — every tile already on
  // screen kept its old ER.
  let ttErSig = "d";
  let ttScrollRun = null;
  let ttScrollStop = false;
  // <<< inline:src/lib/shared/txLang.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/txLang.js and run `npm run gen:inline`.
// The BR/EN transcription-language control that lives ON the page: the persisted
// choice, the little badge on a Transcribe button, and the two-item menu that opens
// when you press one. INLINED into content scripts — see src/lib/shared/README.md
// before editing (no imports allowed in this file).
//
// Facebook grew this first and Instagram/TikTok only got the storage half of it:
// they read `fbw_transcript_language` but had no way to SET it, so on Instagram the
// language was whatever the Facebook rail had last been left on. The three scripts
// also carried three hand-copied `normTxLang`/`getTxLang` pairs — the same drift
// this directory exists to stop.
//
// Deliberately NOT here: which button gets a badge, and when the badge is
// repainted. Each overlay has its own button class and its own render loop, so a
// platform opts a button in with enableTxBadge() and calls updateTxBadges() from
// whatever loop it already runs.

const TX_LANG_KEY = "fbw_transcript_language";
const TX_LANG_DEFAULT = "br";
const TX_LANG_OPTIONS = [
  { value: "br", label: "Português", short: "BR" },
  { value: "en", label: "English", short: "EN" },
];

function normTxLang(value) {
  const lang = String(value || "").trim().toLowerCase();
  if (lang === "en") return "en";
  if (lang === "br" || lang === "pt") return "br";
  return TX_LANG_DEFAULT;
}

function txLangInfo(value) {
  const lang = normTxLang(value);
  return TX_LANG_OPTIONS.find((o) => o.value === lang) || TX_LANG_OPTIONS[0];
}

// Where the menu goes for a button at `rect`, inside a `view` of {width,height}.
//
// Preferred side is LEFT of the button — the Facebook rail sits on the video's left
// edge and a menu opening rightwards would cover the video. A button too close to
// the left edge for that (Instagram's tile actions sit at left:7px) flips to the
// right instead of being clamped into a strip overlapping itself.
const TX_LANG_MENU_W = 124;
function txLangMenuPos(rect, view) {
  const preferred = rect.left - 102;
  const left = preferred < 8 ? rect.right + 6 : preferred;
  return {
    top: Math.max(8, Math.min(view.height - 92, rect.top)),
    left: Math.max(8, Math.min(view.width - 132, left)),
  };
}

const TX_LANG_CSS = `
.fbw-lang-host{position:relative}
.fbw-lang-badge{position:absolute;right:-5px;bottom:-5px;min-width:18px;height:14px;padding:0 3px;border-radius:5px;
  display:grid;place-items:center;background:rgba(15,23,42,.96);color:#dbeafe;border:1px solid rgba(150,185,255,.55);
  font:800 8px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:0;pointer-events:none}
.fbw-lang-menu{position:fixed;z-index:2147483600;display:grid;gap:4px;width:${TX_LANG_MENU_W}px;padding:6px;border-radius:9px;
  background:rgba(17,24,44,.98);border:1px solid rgba(150,185,255,.42);box-shadow:0 8px 24px rgba(0,0,0,.45);
  font:600 12px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#fff}
.fbw-lang-menu button{height:30px;border:0;border-radius:6px;background:transparent;color:#e5e7eb;text-align:left;
  padding:0 8px;cursor:pointer;font:inherit}
.fbw-lang-menu button:hover,.fbw-lang-menu button.active{background:rgba(59,130,246,.24);color:#fff}`;

// On <html>, not <body>: the menu itself is appended there (outside the page's
// React root, which reconciles <body> children away), so its rules must survive
// the same way.
function ensureTxLangStyle() {
  if (document.getElementById("fbw-lang-style")) return;
  const s = document.createElement("style");
  s.id = "fbw-lang-style";
  s.textContent = TX_LANG_CSS;
  (document.head || document.documentElement).appendChild(s);
}

let txLangCache = TX_LANG_DEFAULT;
// The buttons that asked for a badge. A Set (not a selector) because each overlay
// names its buttons differently, and pruning on the way past keeps rails that FB
// remounts constantly from leaking entries.
const txBadged = new Set();

async function getTxLang() {
  try {
    const r = await chrome.storage.local.get(TX_LANG_KEY);
    txLangCache = normTxLang(r?.[TX_LANG_KEY]);
  } catch {
    /* storage gone (extension reloaded under us) — keep the cached value */
  }
  return txLangCache;
}

async function setTxLang(value) {
  txLangCache = normTxLang(value);
  try {
    await chrome.storage.local.set({ [TX_LANG_KEY]: txLangCache });
  } catch {
    /* the caller still gets the normalized value for THIS job */
  }
  updateTxBadges();
  return txLangCache;
}

/** Opt a Transcribe button in: it gets the badge now and on every refresh. */
function enableTxBadge(btn) {
  if (!btn) return;
  ensureTxLangStyle();
  btn.classList.add("fbw-lang-host");
  txBadged.add(btn);
  paintTxBadge(btn);
}

/** Repaint one button's badge — a no-op for buttons that never opted in, so a
 *  platform's shared "button changed state" hook can call it blindly. */
function addTxBadge(btn) {
  if (btn && txBadged.has(btn)) paintTxBadge(btn);
}

function paintTxBadge(btn) {
  let badge = btn.querySelector(".fbw-lang-badge");
  if (!badge) {
    badge = document.createElement("span");
    badge.className = "fbw-lang-badge";
    btn.appendChild(badge);
  }
  badge.textContent = txLangInfo(btn.dataset.lang || txLangCache).short;
}

/** Repaint every opted-in badge, dropping buttons whose rail has been torn down.
 *  Busy buttons are skipped: their glyph is a spinner the badge would sit on. */
function updateTxBadges() {
  for (const btn of txBadged) {
    if (!btn.isConnected) {
      txBadged.delete(btn);
      continue;
    }
    if (!btn.classList.contains("busy")) paintTxBadge(btn);
  }
}

/** Load the stored choice and keep every badge in step with it — including when
 *  the OTHER platform's rail changes it in another tab. */
function watchTxLang() {
  getTxLang().then(updateTxBadges).catch(() => {});
  chrome.storage?.onChanged?.addListener?.((changes, area) => {
    if (area !== "local" || !changes[TX_LANG_KEY]) return;
    txLangCache = normTxLang(changes[TX_LANG_KEY].newValue);
    updateTxBadges();
  });
}

let txLangMenu = null;
let txLangOutside = null;

function closeTxLangMenu() {
  if (txLangOutside) {
    document.removeEventListener("pointerdown", txLangOutside, true);
    window.removeEventListener("blur", closeTxLangMenu);
    window.removeEventListener("scroll", closeTxLangMenu, true);
    txLangOutside = null;
  }
  if (txLangMenu) {
    txLangMenu.remove();
    txLangMenu = null;
  }
}

/**
 * Open the BR/EN menu for `btn`; `onPick(lang)` runs after the choice is saved.
 * A busy button is ignored — its job is already in flight.
 */
function openTxLangMenu(btn, onPick) {
  if (!btn || btn.classList.contains("busy")) return;
  ensureTxLangStyle();
  closeTxLangMenu();
  const pos = txLangMenuPos(btn.getBoundingClientRect(), {
    width: window.innerWidth,
    height: window.innerHeight,
  });
  const menu = document.createElement("div");
  menu.className = "fbw-lang-menu";
  menu.setAttribute("role", "menu");
  menu.style.top = `${pos.top}px`;
  menu.style.left = `${pos.left}px`;
  for (const opt of TX_LANG_OPTIONS) {
    const item = document.createElement("button");
    item.type = "button";
    item.className = opt.value === txLangCache ? "active" : "";
    item.textContent = opt.label;
    // The host page (FB's reel player, IG's story viewer) toggles playback on the
    // pointer sequence, so the whole sequence is swallowed — not just the click.
    item.addEventListener("pointerdown", (e) => { e.preventDefault(); e.stopPropagation(); });
    item.addEventListener("click", async (e) => {
      e.preventDefault();
      e.stopPropagation();
      const lang = await setTxLang(opt.value);
      btn.dataset.lang = lang;
      closeTxLangMenu();
      onPick(lang);
    });
    menu.appendChild(item);
  }
  txLangMenu = menu;
  document.documentElement.appendChild(menu);
  // Next tick: the click that OPENED the menu is still travelling, and a listener
  // armed synchronously would see it as an outside click and close immediately.
  setTimeout(() => {
    txLangOutside = (e) => {
      if (menu.contains(e.target) || btn.contains(e.target)) return;
      closeTxLangMenu();
    };
    document.addEventListener("pointerdown", txLangOutside, true);
    window.addEventListener("blur", closeTxLangMenu, { once: true });
    window.addEventListener("scroll", closeTxLangMenu, { once: true, capture: true });
  }, 0);
}
// >>> inline:end
  watchTxLang();
  // Bumped on every ingest. The panel sends its last seen value and we answer
  // { unchanged: true } when nothing moved, instead of structured-cloning the whole
  // store across processes every 2.5s.
  // One counter per store. A single shared counter meant a video ingest — which
  // happens constantly while the FYP streams — invalidated the comments, stories and
  // lists polls as well, so each of those re-serialised its whole payload every
  // 2.5s even though nothing in it had changed.
  const ver = { videos: 0, comments: 0, stories: 0, lists: 0 };
  const bump = (k) => { ver[k] += 1; };
  // Local mirror of the saved-post ids, kept in sync by one storage.onChanged
  // listener. The overlay used to chrome.storage.local.get("fbw_saved") on EVERY
  // 1s tick, deserializing the entire saved map (base64 thumbs included) into the
  // page process once a second.
  let savedIds = new Set();
  // The video whose comments were most recently fetched == the one you're viewing.
  // Lets the panel auto-follow the current video instead of sticking on a stale one.
  let lastCommentAweme = null;

  // Every store is capped — outer AND inner. Capping only the outer Map (as an
  // earlier version did) still lets a single scraped thread or a huge playlist grow
  // without limit, and the panel serializes all of it on every poll.
  const cap = (m, n) => { while (m.size > n) m.delete(m.keys().next().value); };

  function ingestStory(r) {
    const owner = r.reel_owner || r.username || "unknown";
    let S = stories.get(owner);
    if (!S) { S = new Map(); stories.set(owner, S); }
    bump("stories");
    const prev = S.get(r.id) || {};
    for (const k in r) if (r[k] != null || !(k in prev)) prev[k] = r[k];
    S.set(r.id, prev);
    cap(S, 100);
    cap(stories, 40);
  }
  function ingestListMeta(r) {
    let L = lists.get(r.list_id);
    if (!L) { L = { meta: {}, items: new Map() }; lists.set(r.list_id, L); }
    bump("lists");
    for (const k in r) if (r[k] != null) L.meta[k] = r[k];
    cap(lists, 60);
  }
  function ingestListVideo(r) {
    let L = lists.get(r.list_id);
    if (!L) { L = { meta: { list_id: r.list_id }, items: new Map() }; lists.set(r.list_id, L); }
    bump("lists");
    L.items.set(r.id, r);
    cap(L.items, 300);
    cap(lists, 60); // this path creates entries too, so it must cap as well
  }

  // The payload mapping, the ER maths and the collection knobs are GENERATED from
  // src/lib/shared/ — the MAIN-world capture inlines the same ttItems.js, which is
  // how its `liteItem` and this file's old private `mapItem` stopped drifting.
  // Run `npm run gen:inline` after editing any of them.
// <<< inline:src/lib/shared/harvest.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/harvest.js and run `npm run gen:inline`.
// Collection knobs that are not platform-specific: how far back a research grid
// should look, and how fast an auto-scroll may paginate. INLINED into content
// scripts — see ./README.md before editing (no imports allowed in this file).
//
// These grew inside igFilters.js, but nothing in them is Instagram: TikTok's
// createTime is the same unix-seconds stamp, and a harvester that keeps a
// constant fast cadence reads as automation on every platform. Split out here so
// the TikTok tool can use them without inlining Instagram's ER weights and React
// prop reader alongside.

// ---- date range ----
// A hashtag search is mostly old posts; "what worked this month" is the question
// worth asking, and sorting alone can't answer it.
const DATE_RANGES = [
  { value: "all", label: "Todo o período", days: null },
  { value: "7d", label: "Últimos 7 dias", days: 7 },
  { value: "14d", label: "Últimos 14 dias", days: 14 },
  { value: "30d", label: "Últimos 30 dias", days: 30 },
  { value: "90d", label: "Últimos 90 dias", days: 90 },
  { value: "180d", label: "Últimos 180 dias", days: 180 },
  { value: "1y", label: "Último ano", days: 365 },
  { value: "2y", label: "Últimos 2 anos", days: 730 },
];

/**
 * `takenAt` is UNIX SECONDS (IG's taken_at, TikTok's createTime). A record whose
 * date never arrived is KEPT: grid payloads often omit it, and hiding those posts
 * would look like the filter had eaten real results.
 */
function withinDateRange(takenAt, range, nowSec = Math.floor(Date.now() / 1000)) {
  const r = DATE_RANGES.find((x) => x.value === range);
  if (!r || r.days == null) return true;
  if (typeof takenAt !== "number" || !Number.isFinite(takenAt)) return true;
  return takenAt >= nowSec - r.days * 86400;
}

// ---- paced auto-scroll ----
// IG Sorter scrolls to the bottom on a timer: 3 s for the first five, 6 s for the
// next five, then 10 s. Same shape here.
function scrollGapMs(i) {
  if (i < 5) return 3000;
  if (i < 10) return 6000;
  return 10000;
}
// >>> inline:end
// <<< inline:src/lib/shared/ttItems.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/ttItems.js and run `npm run gen:inline`.
// TikTok payload → lite record. Canonical source, INLINED into the TikTok capture
// scripts — see ./README.md before editing (no imports allowed in this file).
//
// WHY THIS EXISTS. Two copies of this mapping had already grown apart:
// tt-capture.js's `liteItem` (for fetch/XHR payloads) and tt-relay.js's `mapItem`
// (for the SSR hydration blob on a /video/ page). Both read the SAME webapp item
// struct; only their entry points differ.
//
// It also fixes a live blind spot found on 2026-08-16 (see
// docs/research/tiktok-data-map.md): the TikTok SEARCH surface produced ZERO
// records, for two independent reasons —
//
//   * /api/search/general/full/ (the default "Melhores" tab) answers with
//     `data[] → {type, item}`, and /api/search/item/full/ (the "Vídeos" tab)
//     answers with `item_list` — while the reader only ever looked at `itemList`
//     and `items`;
//   * neither URL matched the endpoint regex in the first place.
//
// And it stops throwing away `authorStats`, which every list payload carries.
// That is the follower count — the denominator behind "did well FOR an account
// this size" — and on Instagram it costs a separate enrichment round-trip.

const ttNum = (v) => (v == null ? null : typeof v === "number" ? v : Number.isFinite(+v) ? +v : null);

/**
 * Every list-shaped root TikTok answers with, flattened to raw items.
 *   itemList   /api/post|recommend|related|challenge/item_list/  (camelCase)
 *   item_list  /api/search/item/full/                            (snake_case)
 *   data[]     /api/search/general/full/  → {type, item, common}; type 1 = video,
 *              other types are user/live cards and carry no `item`
 */
function ttItemsIn(obj) {
  if (!obj || typeof obj !== "object") return [];
  const direct = obj.itemList || obj.item_list || obj.items;
  if (Array.isArray(direct)) return direct.filter(Boolean);
  if (Array.isArray(obj.data))
    return obj.data.map((d) => (d && typeof d === "object" ? d.item || null : null)).filter(Boolean);
  return [];
}

/**
 * Creator records: /api/search/user/full/ → `user_list[].user_info`, and
 * /api/user/detail/ → `userInfo.{user,stats}` (a different shape entirely, so it
 * is normalized here rather than at each call site).
 */
function ttUsersIn(obj) {
  if (!obj || typeof obj !== "object") return [];
  const out = [];
  if (Array.isArray(obj.user_list))
    for (const e of obj.user_list) if (e && e.user_info) out.push(e.user_info);
  const ui = obj.userInfo;
  if (ui && ui.user) out.push({ ...ui.user, __stats: ui.stats || ui.statsV2 || null });
  return out;
}

/**
 * Highest-quality rendition: max resolution first, then max bitrate.
 * bitrateInfo[0] is TikTok's default gear, not its best — a 1080 gear usually
 * sits deeper in the ladder. Returns { url, width, height, codec, bitrate } or null.
 */
function ttBestBitrate(video) {
  const gears = Array.isArray(video && video.bitrateInfo) ? video.bitrateInfo : [];
  let best = null;
  for (const g of gears) {
    const pa = (g && g.PlayAddr) || {};
    const url = (pa.UrlList && pa.UrlList[0]) || null;
    if (!url) continue;
    const area = (ttNum(pa.Width) || 0) * (ttNum(pa.Height) || 0);
    const score = area * 1e6 + (ttNum(g.Bitrate) || 0);
    if (!best || score > best.score)
      best = { url, width: ttNum(pa.Width), height: ttNum(pa.Height), codec: g.CodecType || null, bitrate: ttNum(g.Bitrate), score };
  }
  return best;
}

/**
 * The caption track to transcribe from — a direct WebVTT URL, which skips Whisper
 * entirely. Prefer an English track, else the first.
 *
 * Two places carry the same URLs: `video.subtitleInfos` (LanguageCodeName/Url) and
 * `video.claInfo.captionInfos` (languageCode/url). Measured on the search grid,
 * both were present or both absent together — but claInfo is read as a fallback
 * because it is the one the video-detail SSR blob is documented to always carry.
 */
function ttBestSubtitle(video) {
  const v = video || {};
  const subs = Array.isArray(v.subtitleInfos) ? v.subtitleInfos : [];
  const pick = subs.find((s) => /eng/i.test((s && s.LanguageCodeName) || "")) || subs[0];
  if (pick) {
    const url = pick.Url || (Array.isArray(pick.UrlList) && pick.UrlList[0]) || null;
    if (url)
      return {
        url,
        lang: pick.LanguageCodeName || null,
        format: String(pick.Format || "webvtt").toLowerCase(),
        source: pick.Source || null,
      };
  }
  const caps = Array.isArray(v.claInfo && v.claInfo.captionInfos) ? v.claInfo.captionInfos : [];
  const cap = caps.find((c) => /eng/i.test((c && c.language) || "")) || caps[0];
  if (cap) {
    const url = cap.url || (Array.isArray(cap.urlList) && cap.urlList[0]) || null;
    if (url)
      return {
        url,
        lang: cap.language || null,
        format: String(cap.captionFormat || "webvtt").toLowerCase(),
        source: String(cap.isAutoGen) === "True" ? "ASR" : null,
      };
  }
  return null;
}

/** Hashtags, from `challenges` when present and from `textExtra` otherwise. */
function ttHashtags(it) {
  const out = [];
  const seen = new Set();
  const push = (t) => {
    const name = String(t || "").trim();
    if (!name || seen.has(name.toLowerCase())) return;
    seen.add(name.toLowerCase());
    out.push(name);
  };
  if (Array.isArray(it.challenges)) for (const c of it.challenges) push(c && c.title);
  if (Array.isArray(it.textExtra)) for (const t of it.textExtra) push(t && t.hashtagName);
  return out;
}

/**
 * One webapp item struct → the record the panel and the page overlay both read.
 * Every field degrades to null rather than to a wrong value.
 */
function ttLiteItem(it) {
  if (!it || typeof it !== "object") return null;
  const v = it.video || {};
  const a = it.author || {};
  const s = it.statsV2 || it.stats || {};
  const as = it.authorStatsV2 || it.authorStats || {};
  const m = it.music || {};
  const hd = ttBestBitrate(v);
  const sub = ttBestSubtitle(v);
  const id = String(it.id || v.id || "");
  if (!id) return null;
  return {
    __kind: "video",
    id,
    username: a.uniqueId || null,
    nickname: a.nickname || null,
    author_id: a.id ? String(a.id) : null,
    author_sec_uid: a.secUid || null,
    author_avatar: a.avatarThumb || a.avatarMedium || null,
    author_verified: a.verified === true ? true : a.verified === false ? false : null,
    author_bio: a.signature || null,
    author_private: a.privateAccount === true ? true : a.privateAccount === false ? false : null,
    // Creator size, inline on every list payload. Instagram needs a separate
    // enrichment fetch for the same number; TikTok hands it over for free, which
    // is what makes views/follower cheap here.
    user_follower_count: ttNum(as.followerCount),
    user_following_count: ttNum(as.followingCount),
    user_heart_count: ttNum(as.heartCount != null ? as.heartCount : as.heart),
    user_video_count: ttNum(as.videoCount),
    play_count: ttNum(s.playCount),
    digg_count: ttNum(s.diggCount),
    comment_count: ttNum(s.commentCount),
    share_count: ttNum(s.shareCount),
    collect_count: ttNum(s.collectCount),
    repost_count: ttNum(s.repostCount),
    video: v.playAddr || null,
    // Highest-quality URL for downloads. downloadAddr is missing on roughly half
    // the search results (measured), so the gear ladder leads and playAddr is the
    // floor — it is present on every item seen.
    hd_url: (hd && hd.url) || v.downloadAddr || v.playAddr || null,
    hd_res: hd && hd.width && hd.height ? `${hd.width}x${hd.height}` : null,
    download_url: v.downloadAddr || v.playAddr || null,
    subtitle: sub,
    cover: v.cover || v.originCover || null,
    dynamic_cover: v.dynamicCover || null,
    duration: ttNum(v.duration),
    width: ttNum(v.width),
    height: ttNum(v.height),
    desc: (it.desc || "").slice(0, 500) || null,
    create_time: ttNum(it.createTime),
    music: m.title
      ? {
          title: m.title,
          author: m.authorName || null,
          id: m.id ? String(m.id) : null,
          url: m.playUrl || null,
          original: m.original === true || m.original === "True" || null,
          duration: ttNum(m.duration),
        }
      : null,
    hashtags: ttHashtags(it),
    // Only the video page carries these; a grid record simply has them as null.
    location: it.locationCreated || null,
    topics: Array.isArray(it.diversificationLabels) ? it.diversificationLabels.filter(Boolean) : [],
    suggested_words: Array.isArray(it.suggestedWords) ? it.suggestedWords.filter(Boolean) : [],
    is_ad: it.isAd === true || null,
    is_aigc: it.IsAigc === true || !!it.AIGCDescription || null,
    pinned: !!it.isPinnedItem,
  };
}

/** One creator record, from either creator shape ttUsersIn produces. */
function ttLiteUser(u) {
  if (!u || typeof u !== "object") return null;
  const st = u.__stats || {};
  const id = String(u.uid || u.id || "");
  const username = u.unique_id || u.uniqueId || null;
  if (!id && !username) return null;
  return {
    __kind: "tt_user",
    author_id: id || null,
    username,
    nickname: u.nickname || null,
    bio: u.signature || null,
    sec_uid: u.sec_uid || u.secUid || null,
    verified: u.verified === true || !!u.custom_verify || null,
    follower_count: ttNum(st.followerCount != null ? st.followerCount : u.follower_count),
    following_count: ttNum(st.followingCount != null ? st.followingCount : u.following_count),
    heart_count: ttNum(st.heartCount != null ? st.heartCount : (st.heart != null ? st.heart : u.total_favorited)),
    video_count: ttNum(st.videoCount != null ? st.videoCount : u.aweme_count),
  };
}

/**
 * Which TikTok surface a record belongs to. Decided WHERE AND WHEN the record is
 * captured, never at relay time — Instagram learned that the hard way: a replay
 * resends everything the capture ever saw, so stamping the live surface relabels
 * another profile's videos as the one you happen to be looking at now.
 */
function ttSurfaceKey(path, search) {
  const p = path != null ? path : (typeof location !== "undefined" ? location.pathname : "/");
  const q = search != null ? search : (typeof location !== "undefined" ? location.search : "");
  let m;
  if ((m = p.match(/^\/@([^/]+)/))) return "profile:" + decodeURIComponent(m[1]).toLowerCase();
  if ((m = p.match(/^\/tag\/([^/]+)/))) return "tag:" + decodeURIComponent(m[1]).toLowerCase();
  if (p.startsWith("/search")) {
    const k = new URLSearchParams(q || "").get("q");
    return "search:" + (k ? k.toLowerCase() : "");
  }
  if (p.startsWith("/foryou") || p === "/") return "feed";
  if (p.startsWith("/explore")) return "explore";
  return "feed";
}
// >>> inline:end
// <<< inline:src/lib/shared/fmt.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fmt.js and run `npm run gen:inline`.
// Two formatters every platform needs: a date and an engagement rate. INLINED
// into content scripts — see ./README.md before editing (no imports allowed).
//
// These lived in igFormat.js and were hand-copied into ttMedia.js. Same numbers,
// two implementations, and only one of them was tested — exactly the drift this
// directory exists to stop. (Count formatting is next door, in counts.js.)

/** Unix SECONDS → "YYYY-MM-DD" (empty string when missing/invalid). */
function fmtDate(unixSeconds) {
  if (!unixSeconds) return "";
  const d = new Date(unixSeconds * 1000);
  return Number.isNaN(d.getTime()) ? "" : d.toISOString().slice(0, 10);
}

// Engagement-rate label. Never collapses to "0.0%": 1 decimal ≥10, 2 decimals
// ≥0.1, else 2 significant figures (e.g. "0.06%", "0.004%").
function fmtER(er) {
  if (er == null) return null;
  if (er === 0) return "0%";
  if (er >= 10) return er.toFixed(1) + "%";
  if (er >= 0.1) return er.toFixed(2) + "%";
  return Number(er.toPrecision(2)) + "%";
}
// >>> inline:end
// <<< inline:src/lib/shared/ttFormat.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/ttFormat.js and run `npm run gen:inline`.
// TikTok engagement maths and the permalink rule. Canonical source, INLINED into
// the TikTok content scripts — see ./README.md before editing (no imports allowed
// except from a sibling in this directory).

// ER weights — like 1×, comment & share 4×, save 2×. TikTok exposes shares AND
// saves on the list (Instagram exposes neither), so the weight set is richer than
// IG's and lives apart from it, under its own storage key.
const TT_ER_WEIGHTS = { like: 1, comment: 4, share: 4, save: 2 };
const TT_ER_WEIGHTS_KEY = "fbw_tt_er_weights"; // storage.local — panel writes, page reads

/** Per-field fallback: one junk value must not throw away the other three. */
function normalizeTtErWeights(w) {
  const out = { ...TT_ER_WEIGHTS };
  if (!w || typeof w !== "object") return out;
  for (const k of Object.keys(TT_ER_WEIGHTS)) {
    const n = Number(w[k]);
    if (Number.isFinite(n) && n >= 0) out[k] = n;
  }
  return out;
}

/** ER = (like×w + comment×w + share×w + save×w) / plays × 100. Null without plays. */
function ttEngagementRate(rec, weights) {
  if (!rec) return null;
  const v = rec.play_count;
  if (!v || v <= 0) return null;
  const w = weights || TT_ER_WEIGHTS;
  const eng =
    w.like * (rec.digg_count || 0) +
    w.comment * (rec.comment_count || 0) +
    w.share * (rec.share_count || 0) +
    w.save * (rec.collect_count || 0);
  return (eng / v) * 100;
}

/**
 * Views per follower — how far a video travelled beyond the audience it started
 * with. Null when either half is missing, so it degrades to "—" instead of to a
 * confident zero.
 */
function ttViewsPerFollower(rec) {
  if (!rec) return null;
  const f = rec.user_follower_count;
  const v = rec.play_count;
  if (!f || f <= 0 || v == null) return null;
  return v / f;
}

/** One decimal below 10×, none above — "3.4×", "112×". */
function fmtRatio(x) {
  if (x == null) return null;
  return (x >= 10 ? Math.round(x) : Number(x.toFixed(1))) + "×";
}

/** Absolute permalink back to a captured record, or null when it can't be built. */
function ttPermalink(rec) {
  if (!rec || !rec.id || !rec.username) return null;
  return `https://www.tiktok.com/@${rec.username}/video/${rec.id}`;
}

/** The ER label the overlay and the panel both print. */
function ttErLabel(rec, weights) {
  return fmtER(ttEngagementRate(rec, weights));
}
// >>> inline:end

  // The surface a record belongs to. Live value only — a record's OWN
  // capture-time `__surface` always wins (see onRelay).
  const surfaceKey = () => ttSurfaceKey();

  // The aweme id of the video the user is currently on. URL first (detail pages +
  // FYP once TikTok rewrites the path), then the most-centered <video>'s nearest
  // /video/<id> link, then the last video whose comments loaded.
  function currentAwemeId(centered) {
    const m = location.pathname.match(/\/video\/(\d+)/);
    if (m) return m[1];
    const v = centered !== undefined ? centered : mostCenteredVideo();
    if (v) {
      let el = v;
      for (let i = 0; i < 8 && el; i++) {
        const a = el.querySelector?.('a[href*="/video/"]');
        const mm = a && (a.getAttribute("href") || "").match(/\/video\/(\d+)/);
        if (mm) return mm[1];
        el = el.parentElement;
      }
    }
    return lastCommentAweme;
  }

  function mostCenteredVideo() {
    let best = null, bestScore = -Infinity;
    for (const v of document.querySelectorAll("video")) {
      const r = v.getBoundingClientRect();
      if (r.width < 120 || r.height < 120) continue;
      const visible = Math.min(r.bottom, innerHeight) - Math.max(r.top, 0);
      if (visible <= 0) continue;
      const score = visible - Math.abs(r.top + r.height / 2 - innerHeight / 2);
      if (score > bestScore) { bestScore = score; best = v; }
    }
    return best;
  }

  function ingestComment(r) {
    if (!r.aweme_id || !r.cid) return;
    lastCommentAweme = r.aweme_id;
    let C = comments.get(r.aweme_id);
    if (!C) { C = { aweme_id: r.aweme_id, items: new Map() }; comments.set(r.aweme_id, C); }
    bump("comments");
    const prev = C.items.get(r.cid) || {};
    for (const k in r) if (r[k] != null || !(k in prev)) prev[k] = r[k];
    C.items.set(r.cid, prev);
    cap(C.items, 500); // a scraped thread is unbounded upstream
    cap(comments, 60);
  }

  // Creator stats, keyed by author id AND by @handle. A video captured on a
  // surface whose payload omits authorStats still gets a follower count once the
  // creator's own record arrives (profile visit, or the "Usuários" search tab).
  const ttUsers = new Map();
  const ttUsersByName = new Map();
  function applyCreator(rec) {
    const u =
      (rec.author_id && ttUsers.get(rec.author_id)) ||
      (rec.username && ttUsersByName.get(rec.username)) ||
      null;
    if (!u) return rec;
    // Never downgrade: the item's own authorStats is the fresher number when it
    // has one, and the creator record is only the backfill.
    if (rec.user_follower_count == null) rec.user_follower_count = u.follower_count;
    if (rec.user_following_count == null) rec.user_following_count = u.following_count;
    if (rec.user_heart_count == null) rec.user_heart_count = u.heart_count;
    if (rec.user_video_count == null) rec.user_video_count = u.video_count;
    if (!rec.author_bio) rec.author_bio = u.bio;
    if (!rec.username && u.username) rec.username = u.username;
    return rec;
  }
  function ingestCreator(r) {
    const key = r.author_id || r.username;
    if (!key) return;
    const merged = { ...(ttUsers.get(key) || {}), ...r };
    ttUsers.set(key, merged);
    if (merged.username) ttUsersByName.set(merged.username, merged);
    for (const rec of byId.values())
      if (rec.author_id === merged.author_id || (merged.username && rec.username === merged.username))
        applyCreator(rec);
    // Both indexes are capped SEPARATELY — evicting the id map leaves the
    // by-name entry behind, and that one would then grow for the tab's life.
    cap(ttUsers, 400);
    cap(ttUsersByName, 400);
  }

  const onRelay = (e) => {
    if (e.source !== window || !e.data || !e.data.__fbwTt) return;
    if (disabled) return;
    const liveSurface = surfaceKey();
    for (const r of e.data.records || []) {
      if (r.__kind === "comment") { ingestComment(r); continue; }
      if (r.__kind === "tt_list") { ingestListMeta(r); continue; }
      if (r.__kind === "tt_story") { ingestStory(r); continue; }
      if (r.__kind === "tt_user") { ingestCreator(r); continue; }
      if (!r.id) continue;
      // The record's OWN capture-time surface wins. A replay resends everything
      // the MAIN world ever saw, so stamping the live surface here relabels the
      // videos of the profile you just left as this one's. `liveSurface` is only
      // the fallback for records from a MAIN world older than this build.
      const surface = r.__surface || liveSurface;
      r.surface = surface;
      if (!r.username && surface.startsWith("profile:")) r.username = surface.slice("profile:".length);
      const prev = byId.get(r.id) || {};
      for (const k in r) if (r[k] != null || !(k in prev)) prev[k] = r[k];
      byId.set(r.id, prev);
      applyCreator(prev);
      if (r.list_id) ingestListVideo(prev); // playlist/collection membership
    }
    while (byId.size > 500) byId.delete(byId.keys().next().value);
    bump("videos"); // lets the panel poll short-circuit when nothing changed
    scheduleOverlay();
  };
  window.addEventListener("message", onRelay);

  // Mirror fbw_saved ids locally (see savedIds above).
  const refreshSaved = (map) => { savedIds = new Set(Object.keys(map || {})); };
  chrome.storage?.local?.get("fbw_saved").then((r) => refreshSaved(r?.fbw_saved)).catch(() => {});
  const onSavedChanged = (ch, area) => {
    if (area === "local" && ch.fbw_saved) { refreshSaved(ch.fbw_saved.newValue); scheduleOverlay(); }
  };
  chrome.storage?.onChanged?.addListener(onSavedChanged);

  // TikTok's search and profile grids do NOT scroll the document — the scroller is
  // <main> (measured: document.scrollingElement.scrollHeight === clientHeight while
  // main.scrollHeight kept growing 2250 → 7287 as results loaded). Scrolling the
  // window there paginates nothing at all. The document is still the fallback for
  // any surface that does scroll normally.
  function gridScroller() {
    const main = document.querySelector("main");
    if (main && main.scrollHeight > main.clientHeight + 100) return main;
    for (const el of document.querySelectorAll("div")) {
      if (el.scrollHeight > el.clientHeight + 400 && /auto|scroll/.test(getComputedStyle(el).overflowY)) return el;
    }
    return document.scrollingElement || document.documentElement;
  }
  function scrollGridToEnd() {
    const s = gridScroller();
    s.scrollTo({ top: s.scrollHeight, behavior: "smooth" });
  }

  let lastReplayReq = 0;
  function requestReplay() {
    const now = Date.now();
    if (now - lastReplayReq < 600) return;
    lastReplayReq = now;
    window.postMessage({ __fbwTtReq: true }, location.origin);
  }
  requestReplay();
  setTimeout(requestReplay, 700);
  setTimeout(requestReplay, 1800);

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    // Every poll carries the panel's last seen `version`; when nothing has been
    // ingested since, answer with a tiny {unchanged} instead of structured-cloning
    // the whole store across processes.
    if (msg?.type === "FBW_TT_LIST") {
      if (msg.since === ver.videos) {
        // surface/current are cheap and CHANGE without a new capture (SPA nav,
        // scrolling the feed), so they ship even when the store has not moved.
        sendResponse({ unchanged: true, version: ver.videos, surface: surfaceKey(), current: currentAwemeId() });
        return;
      }
      sendResponse({ records: Array.from(byId.values()), surface: surfaceKey(), current: currentAwemeId(), version: ver.videos });
      return;
    }
    if (msg?.type === "FBW_TT_COMMENTS") {
      if (msg.since === ver.comments) {
        sendResponse({ unchanged: true, version: ver.comments, current: lastCommentAweme || currentAwemeId() });
        return;
      }
      const videos = [];
      for (const C of comments.values()) {
        videos.push({ aweme_id: C.aweme_id, meta: byId.get(C.aweme_id) || null, comments: Array.from(C.items.values()) });
      }
      // `current` = the video the user is viewing → the panel auto-selects it.
      sendResponse({ videos, current: lastCommentAweme || currentAwemeId(), version: ver.comments });
      return;
    }
    if (msg?.type === "FBW_TT_STORIES") {
      if (msg.since === ver.stories) { sendResponse({ unchanged: true, version: ver.stories }); return; }
      const out = [];
      for (const [owner, S] of stories) out.push({ owner, items: Array.from(S.values()) });
      sendResponse({ owners: out, version: ver.stories });
      return;
    }
    if (msg?.type === "FBW_TT_LISTS") {
      if (msg.since === ver.lists) { sendResponse({ unchanged: true, version: ver.lists }); return; }
      const out = [];
      for (const [, L] of lists) out.push({ ...L.meta, items: Array.from(L.items.values()) });
      sendResponse({ lists: out, version: ver.lists });
      return;
    }
    // Paced harvest: scroll the grid so TikTok paginates, at a cadence that slows
    // the longer it runs (scrollGapMs). Collection was manual before this — the
    // panel could only sort what the user had already scrolled past.
    if (msg?.type === "FBW_TT_SCROLL") {
      const rounds = Math.max(1, Math.min(60, Number(msg.rounds) || 10));
      if (!ttScrollRun) {
        // Clear the stop flag HERE, not only when a run ends: the panel's finish
        // estimate can outlast the page loop, and a Stop clicked in that window
        // would otherwise arm the flag with no run to stop, breaking the NEXT run
        // on its first iteration.
        ttScrollStop = false;
        ttScrollRun = (async () => {
          for (let i = 0; i < rounds; i++) {
            if (disabled || ttScrollStop) break;
            scrollGridToEnd();
            await new Promise((r) => setTimeout(r, scrollGapMs(i)));
          }
          ttScrollRun = null;
          ttScrollStop = false;
        })();
      }
      sendResponse?.({ ok: true, rounds });
      return;
    }
    if (msg?.type === "FBW_TT_SCROLL_STOP") { ttScrollStop = true; sendResponse?.({ ok: true }); return; }
    if (msg?.type === "FBW_TT_TOP") { gridScroller()?.scrollTo({ top: 0, behavior: "smooth" }); sendResponse?.({ ok: true }); return; }
    if (msg?.type === "FBW_TT_CLEAR") {
      byId.clear();
      comments.clear();
      stories.clear();
      lists.clear();
      lastCommentAweme = null;
      bump("videos"); bump("comments"); bump("stories"); bump("lists");
      requestReplay(); // re-pull the current surface so the panel isn't left empty
      sendResponse?.({ ok: true });
      return;
    }
    if (msg?.type === "FBW_PING") { sendResponse?.({ ok: true }); }
  });

  // ============================================================
  // On-page action overlay — a floating stack pinned to the window's right edge
  // (clear of TikTok's own action rail, which hugs the video). Acts on the current
  // video: save / download / transcribe (need the captured record for the media
  // URL), scrape-comments (open + auto-scroll the comment panel → passive capture),
  // like (click TikTok's native control). No blur (repaints jank the feed).
  // ============================================================
  // Icons and the ok/err flash are GENERATED from src/lib/shared/overlayUi.js —
  // the same set the Instagram and Pinterest overlays draw from (this script cannot
  // import; run `npm run gen:inline` after editing the source).
// <<< inline:src/lib/shared/overlayUi.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/overlayUi.js and run `npm run gen:inline`.
// The button machinery behind the injected page overlays: one icon vocabulary and
// one state machine. INLINED into content scripts — see src/lib/shared/README.md
// before editing (no imports allowed in this file).
//
// Instagram, TikTok and Pinterest each grew their own copy of both and the copies
// had already drifted: three stroke widths for the same lucide glyphs, two
// orderings of the same file-text paths, and 1200 / 1300 / 2500ms for the same
// "did it work?" flash.
//
// What is deliberately NOT here: the CSS and the render loops. Those are genuinely
// per-platform (different tile structures, different mutation patterns) and each
// overlay keeps its own button class — .sw-actbtn, .sw-ttbtn, .sw-pinbtn — so the
// state machine below only ever touches the element it is handed.

// lucide-style 24×24 stroked glyphs, rendered by overlayIcon().
const OVERLAY_ICONS = {
  dl: '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/>',
  save: '<path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>',
  img: '<rect width="18" height="18" x="3" y="3" rx="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.1-3.1a2 2 0 0 0-2.8 0L6 21"/>',
  tx: '<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/>',
  layers: '<path d="M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z"/><path d="M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12"/><path d="M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17"/>',
  msg: '<path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/>',
  heart: '<path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/>',
  ok: '<polyline points="20 6 9 17 4 12"/>',
  err: '<line x1="18" x2="6" y1="6" y2="18"/><line x1="6" x2="18" y1="6" y2="18"/>',
  // Instagram's stats rail only. Kept here so there is one place to look up a
  // glyph, rather than one shared map plus a private map for the odd ones out.
  eye: '<circle cx="12" cy="12" r="3"/><path d="M2.06 12.35a1 1 0 0 1 0-.7 10.75 10.75 0 0 1 19.88 0 1 1 0 0 1 0 .7 10.75 10.75 0 0 1-19.88 0"/>',
  zap: '<path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"/>',
  repost: '<path d="m17 2 4 4-4 4"/><path d="M3 11v-1a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v1a4 4 0 0 1-4 4H3"/>',
  cal: '<path d="M8 2v4"/><path d="M16 2v4"/><rect width="18" height="18" x="3" y="4" rx="2"/><path d="M3 10h18"/>',
  // Follower count — how big the account behind the post is.
  user: '<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
  // The sound a reel rides, so a trend can be traced to its audio.
  audio: '<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',
};

// 15px is the tile-action button's glyph; the floating rails pass their own size.
// An unknown name renders an empty <svg> rather than the string "undefined".
function overlayIcon(name, size = 15) {
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" width="${size}" height="${size}">${OVERLAY_ICONS[name] || ""}</svg>`;
}

// How long ok/err feedback stays before the button goes back to idle. Pinterest's
// 2.5s is the one long enough to be read on a grid that is still mutating.
const OVERLAY_FLASH_MS = 2500;

/**
 * busy / ok / err / idle for one overlay button. Only the STATE classes are
 * shared; the button's own class is the platform's business, so this takes the
 * element and never a class prefix.
 *
 * A button that names its idle glyph in `data-kind` also gets the glyph swapped
 * (Pinterest's spinner and ✓/✗); one that doesn't just recolours, which is what
 * the Instagram and TikTok rails have always done.
 */
function setOverlayBtnState(btn, state) {
  // Clear any pending flash first. Without this a flash armed by an earlier click
  // fires mid-way through a later one, strips the `busy` class and defeats the
  // re-entrancy guard that class IS on Pinterest (pin-api.js checks it before
  // starting a download).
  if (btn.__swFlashTimer) {
    clearTimeout(btn.__swFlashTimer);
    btn.__swFlashTimer = null;
  }
  btn.classList.remove("busy", "ok", "err");
  if (state === "busy" || state === "ok" || state === "err") btn.classList.add(state);
  const kind = btn.dataset.kind;
  if (!kind) return;
  btn.innerHTML = overlayIcon(state === "ok" || state === "err" ? state : kind);
}

/**
 * Show how an action actually ended, then return the button to idle. The timer is
 * kept on the button so a second click restarts it — otherwise the first click's
 * timer resets a button the second one has just put back into busy.
 */
function flashOverlayBtn(btn, state) {
  setOverlayBtnState(btn, state);
  clearTimeout(btn.__swFlashTimer);
  btn.__swFlashTimer = setTimeout(() => {
    if (btn.isConnected) setOverlayBtnState(btn, "idle");
  }, OVERLAY_FLASH_MS);
}
// >>> inline:end

  let styleAdded = false;
  function ensureStyle() {
    if (styleAdded) return;
    styleAdded = true;
    const s = document.createElement("style");
    s.textContent = `
      #sw-tt-acts{position:fixed;top:50%;right:16px;transform:translateY(-50%);z-index:2147482000;
        display:flex;flex-direction:column;gap:9px}
      .sw-ttbtn{position:relative;display:grid;place-items:center;width:42px;height:42px;border-radius:12px;cursor:pointer;color:#fff;
        background:rgba(20,20,24,.92);border:1px solid rgba(150,185,255,.45);box-shadow:0 2px 10px rgba(0,0,0,.4);
        transition:background .15s,color .15s,transform .1s}
      .sw-ttbtn:hover{background:rgba(40,44,60,.96);transform:translateY(-1px)}
      .sw-ttbtn.ok{color:#34d399;border-color:rgba(52,211,153,.6)}
      .sw-ttbtn.err{color:#f87171;border-color:rgba(248,113,113,.6)}
      .sw-ttbtn.on{color:#facc15;border-color:rgba(250,204,21,.6)}
      .sw-ttbtn.on svg{fill:#facc15}
      .sw-ttbtn[disabled]{opacity:.4;cursor:default}
      .sw-ttbtn[data-tip]:hover::after{content:attr(data-tip);position:absolute;right:calc(100% + 8px);top:50%;
        transform:translateY(-50%);background:rgba(17,20,32,.97);color:#fff;font:600 11px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
        padding:5px 8px;border-radius:6px;white-space:nowrap;pointer-events:none;box-shadow:0 2px 8px rgba(0,0,0,.5);border:1px solid rgba(150,185,255,.28)}

      /* ---- grid tile + player rails ----
         Same vocabulary as the Instagram overlay (OVL there, TT_OVL here) so a
         hashtag grid reads identically on both platforms. No backdrop blur: each
         blurred surface re-rasters the moving grid behind it every scrolled frame,
         which is what made the Instagram version cost 68ms/frame before it went.
         (No backticks anywhere in this block — the stylesheet is a JS template
         literal and one would end it mid-rule.) */
      .sw-ttovl{position:absolute;right:${TT_OVL.gap}px;bottom:${TT_OVL.gap}px;display:flex;flex-direction:column;gap:4px;
        padding:7px 10px;border-radius:${TT_OVL.radius}px;background:rgba(0,0,0,${TT_OVL.bgOpacity});
        border:1px solid ${TT_OVL.borderColor};box-shadow:0 0 12px ${TT_OVL.glow},inset 0 0 0 1px rgba(160,190,255,.12);
        color:#fff;pointer-events:none;z-index:5;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
        text-shadow:0 1px 2px rgba(0,0,0,.45)}
      .sw-ttovl-row{display:flex;align-items:center;gap:6px;font-size:${TT_OVL.fontRow}px;font-weight:700;line-height:1;white-space:nowrap}
      .sw-ttovl-row.primary{font-size:${TT_OVL.fontPrimary}px;font-weight:800}
      .sw-ttovl.compact{padding:5px 7px;gap:3px;border-radius:9px}
      .sw-ttovl.compact .sw-ttovl-row{font-size:11px}
      .sw-ttovl.compact .sw-ttovl-row.primary{font-size:13px}
      .sw-ttovl svg{flex:none}
      .sw-ttacts{position:absolute;top:7px;left:7px;display:flex;flex-direction:column;gap:5px;z-index:6}
      .sw-ttact{position:relative;display:grid;place-items:center;width:${TT_OVL.btnSize}px;height:${TT_OVL.btnSize}px;border-radius:8px;
        cursor:pointer;color:#fff;background:rgba(0,0,0,${TT_OVL.bgOpacity});border:1px solid ${TT_OVL.borderColor};
        box-shadow:0 0 8px ${TT_OVL.glow};transition:background .15s}
      .sw-ttact:hover{background:rgba(0,0,0,.8)}
      .sw-ttact.on{color:#facc15;border-color:rgba(250,204,21,.55);box-shadow:0 0 8px rgba(250,204,21,.3)}
      .sw-ttact.on svg{fill:#facc15}
      .sw-ttact.ok{color:#34d399;border-color:rgba(52,211,153,.6)}
      .sw-ttact.err{color:#f87171;border-color:rgba(248,113,113,.6)}
      /* TikTok's player paints its own full-size click layer over everything in
         its subtree — the same trap Instagram set, where our button came SIXTH in
         elementsFromPoint and every tap toggled playback instead. No z-index
         inside that subtree can win, so the player's rails live in a fixed
         top-level layer on <html>, positioned over the player each pass. */
      #sw-tt-layer{position:fixed;left:0;top:0;width:0;height:0;z-index:2147483000;pointer-events:none}
      #sw-tt-layer .sw-ttovl,#sw-tt-layer .sw-ttacts{position:fixed}
      #sw-tt-layer .sw-ttacts{pointer-events:auto}`;
    (document.head || document.documentElement).appendChild(s);
  }

  const ext = (url, kind) => {
    const m = String(url || "").match(/\.(mp4|mov|webm|jpg|jpeg|png|webp)(\?|$)/i);
    if (m) { const e = m[1].toLowerCase(); return e === "jpeg" ? "jpg" : e; }
    return kind === "video" ? "mp4" : "jpg";
  };
  const sanit = (s) => String(s || "").replace(/[\\/:*?"<>|]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 40);
  const ttName = (rec, e) => `tt-${sanit(rec.username || rec.nickname)}-${rec.id}.${e}`;

  // A /video/ page fetches NOTHING for the video it opens on — the item is
  // server-rendered into __UNIVERSAL_DATA_FOR_REHYDRATION__, so the MAIN-world
  // fetch tee has nothing to see and byId stays empty. (Confirmed 2026-08-16: a
  // cold load of a video page fires zero item requests; only scrolling into the
  // next one hits /api/related/item_list/.) So the blob is read here, with the
  // SAME ttLiteItem the fetch path uses.
  //
  // Memoized per aweme id INCLUDING failures. The blob is hundreds of KB to a few
  // MB; on the FYP feed (or after any SPA nav) the id never matches, so an
  // unmemoized version re-parsed the whole thing on every tick, forever.
  const ssrTried = new Set();
  function ssrScope() {
    const el = document.getElementById("__UNIVERSAL_DATA_FOR_REHYDRATION__");
    if (!el) return null;
    return JSON.parse(el.textContent).__DEFAULT_SCOPE__ || null;
  }
  function ssrRecord(awemeId) {
    if (ssrTried.has(awemeId)) return null; // already parsed once for this id
    ssrTried.add(awemeId);
    cap(ssrTried, 200);
    try {
      const scope = ssrScope();
      const it = scope && scope["webapp.video-detail"]?.itemInfo?.itemStruct;
      // Id-matched, so a blob left over from before an SPA navigation is ignored.
      if (!it || String(it.id) !== String(awemeId)) return null;
      const r = ttLiteItem(it);
      if (!r) return null;
      r.surface = surfaceKey();
      return r;
    } catch {
      return null;
    }
  }
  // A profile page renders its owner the same way (webapp.user-detail). That is
  // the follower count for every video on the page, so it is read once per path.
  let ssrUserPath = null;
  function ssrCreator() {
    if (ssrUserPath === location.pathname) return;
    ssrUserPath = location.pathname;
    if (!/^\/@/.test(location.pathname)) return;
    try {
      const scope = ssrScope();
      const ui = scope && scope["webapp.user-detail"];
      if (!ui) return;
      for (const u of ttUsersIn(ui)) {
        const r = ttLiteUser(u);
        if (r) ingestCreator(r);
      }
    } catch {
      /* a shape we don't know is not worth a thrown overlay pass */
    }
  }
  // Counts straight off the player's own action rail.
  //
  // Needed because the SSR blob is NOT reliable: TikTok registers a service
  // worker, and on a warm load it serves a shell with no
  // __UNIVERSAL_DATA_FOR_REHYDRATION__ at all (measured 2026-08-16 — the same URL
  // that had shipped the blob minutes earlier returned none). With no fetch and no
  // blob there is a third source, and it is the one the user is looking at.
  //
  // Views are deliberately absent: TikTok does not print a play count on a video
  // page, so ER stays null there rather than being invented from a smaller
  // denominator. `parseCount` handles the localized abbreviations ("14,3 mil").
  function domCounts(centered) {
    // Scope to the centered item's own container — the immersive feed keeps the
    // NEXT video's rail mounted too, and an unscoped query reads its numbers.
    let scope = centered;
    for (let i = 0; i < 8 && scope; i++) {
      if (scope.querySelector && scope.querySelector('[data-e2e="like-count"]')) break;
      scope = scope.parentElement;
    }
    if (!scope || !scope.querySelector) return null;
    const read = (name) => {
      const el = scope.querySelector(`[data-e2e="${name}"]`);
      return el ? parseCount((el.innerText || "").trim()) : null;
    };
    const digg = read("like-count");
    const comment = read("comment-count");
    if (digg == null && comment == null) return null;
    return {
      digg_count: digg,
      comment_count: comment,
      share_count: read("share-count"),
      collect_count: read("favorite-count"),
    };
  }

  function currentRecord(centered) {
    const id = currentAwemeId(centered);
    if (!id) return null;
    let rec = byId.get(id);
    if (!rec || !(rec.video || rec.download_url)) {
      const ssr = ssrRecord(id);
      if (ssr) {
        rec = applyCreator({ ...(rec || {}), ...ssr });
        byId.set(id, rec); // cache so the panel sees it too
        bump("videos"); // …and so its next poll actually ships it
      }
    }
    // Last resort: no capture, no blob. The counts on screen still beat a blank
    // rail, and the record stays out of byId — a countsless, media-less stub must
    // not reach the panel's grid or the Library.
    if (!rec || (rec.digg_count == null && rec.play_count == null)) {
      const dom = domCounts(centered);
      if (dom) {
        const m = location.pathname.match(/^\/@([^/]+)/);
        return applyCreator({
          id,
          username: (rec && rec.username) || (m ? decodeURIComponent(m[1]) : null),
          surface: surfaceKey(),
          ...(rec || {}),
          ...dom,
        });
      }
    }
    return rec || null;
  }

  // Library record shape — GENERATED from src/lib/shared/savedEntry.js (this
  // script cannot import; run `npm run gen:inline`). The background owns and
  // serializes the write, so a panel toggle and a page toggle can't clobber.
// <<< inline:src/lib/shared/counts.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/counts.js and run `npm run gen:inline`.
// Localized count parsing/formatting. INLINED into content scripts — see
// src/lib/shared/README.md before editing (no imports allowed in this file).

// Localized abbreviated-count multipliers. FB/IG/TikTok render counts abbreviated
// with a locale word or suffix: pt-br "mil"/"mi", en "K"/"M", plus other locales'
// short forms. A missing entry here means a real count parses as null, which is
// how the comment scraper used to lose reaction counts on non-pt/en UIs.
const COUNT_UNITS = {
  k: 1e3, mil: 1e3, rb: 1e3, tis: 1e3, tys: 1e3, tusen: 1e3,
  m: 1e6, mi: 1e6, mio: 1e6, jt: 1e6, mln: 1e6, mn: 1e6,
  b: 1e9, mrd: 1e9, bi: 1e9,
};

/**
 * Parse a localized count string into a number, or null.
 *   "14 mil" -> 14000   "1,5 mil" -> 1500   "1.2M" -> 1200000   "543" -> 543
 * When a unit word/suffix is present the numeric part is a small decimal, so a
 * comma is the decimal separator (pt-br "1,5"). Without a unit the value is a
 * plain integer whose separators are thousands groups and are stripped.
 */
function parseCount(text) {
  if (text == null) return null;
  if (typeof text === "number") return Number.isFinite(text) ? text : null;
  // A trailing period is an abbreviation mark in some locales ("1,2 mil.").
  const s = String(text).trim().toLowerCase().replace(/\s+/g, "").replace(/\.$/, "");
  if (!s) return null;
  const m = s.match(/^([\d.,]+)([a-zçã]+)?$/);
  if (!m) return null;
  const rawNum = m[1];
  const unitWord = m[2] || "";
  const mult = unitWord ? COUNT_UNITS[unitWord] : 1;
  if (unitWord && mult == null) return null; // unknown suffix → not a count
  // Separator rules, in order of how much they tell us:
  //   both present   → the LAST one is the decimal, the other is grouping.
  //                    "1.234,5" is 1234.5 (pt-BR) and "1,234.5" is 1234.5 (en).
  //   one + a unit   → that one is the decimal ("76,8 mil", "1.2M").
  //   one, no unit   → grouping; strip it ("1.234" is 1234, "76.800" is 76800).
  const hasDot = rawNum.includes(".");
  const hasComma = rawNum.includes(",");
  let norm;
  if (hasDot && hasComma) {
    const decimal = rawNum.lastIndexOf(".") > rawNum.lastIndexOf(",") ? "." : ",";
    const grouping = decimal === "." ? "," : ".";
    norm = rawNum.split(grouping).join("").replace(decimal, ".");
  } else if (unitWord) {
    norm = rawNum.replace(",", ".");
  } else {
    norm = rawNum.replace(/[.,]/g, "");
  }
  const num = parseFloat(norm);
  if (!Number.isFinite(num)) return null;
  return Math.round(num * mult);
}

// Display formatting. 964490 -> "964.5K". Null renders as an em dash rather than
// "0" — an unknown count and a zero count are different facts. Counts are stored
// raw and formatted here at render time.
function fmtCount(n) {
  if (n == null) return "—";
  if (n >= 1e6) return (n / 1e6).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1e3) return (n / 1e3).toFixed(1).replace(/\.0$/, "") + "K";
  return String(n);
}
// >>> inline:end

// <<< inline:src/lib/shared/savedEntry.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/savedEntry.js and run `npm run gen:inline`.
// The ONE shape of a saved-Library record, and the permalink rules behind it.
// INLINED into content scripts — see src/lib/shared/README.md before editing
// (no imports allowed in this file).
//
// This exists because `fbw_saved` used to be written from ten places (six panel
// tools, three page overlays, the transcription rail) with five different shapes:
//
//   * counts were pre-formatted strings, sometimes via an UNGUARDED fmtCount(null)
//     (so whatever that returned got persisted instead of null), and Pinterest
//     stored the literal string "—" for views where everything else stored null;
//   * `sourceUrl` was present in some and absent in others, and VideoCard falls
//     back to `facebook.com/reel/<id>` when it's missing — a dead link for a
//     TikTok or Pinterest item;
//   * TikTok stored a signed, expiring CDN URL as `thumb`.
//
// Counts are stored as RAW NUMBERS (or null) — never formatted. Formatting is a
// render-time concern, and storing numbers keeps the Library sortable. VideoCard
// tolerates strings for records written before schema 2.

const SAVED_SCHEMA = 2;

// Absolute permalink back to the item, per platform. Centralized because a
// missing sourceUrl silently degrades into a wrong Facebook link.
function savedSourceUrl(platform, { code, id, username } = {}) {
  const key = code || id;
  switch (platform) {
    case "instagram":
      return key ? `https://www.instagram.com/p/${key}/` : null;
    case "tiktok":
      return username && id ? `https://www.tiktok.com/@${username}/video/${id}` : null;
    case "facebook":
      return key ? `https://www.facebook.com/reel/${key}` : null;
    case "pinterest":
      return key ? `https://www.pinterest.com/pin/${key}/` : null;
    default:
      return null;
  }
}

// Profile URL. FB/IG are stored relative (VideoCard prepends the origin);
// TikTok/Pinterest are absolute, and prepending an origin to those would nest one
// URL inside another and produce a dead link.
function savedAuthorUrl(platform, username) {
  if (!username) return null;
  switch (platform) {
    case "instagram":
      return `/${username}/`;
    case "tiktok":
      return `https://www.tiktok.com/@${username}`;
    case "pinterest":
      return `https://www.pinterest.com/${username}/`;
    case "facebook":
      return null; // FB reels grids expose no reliable author URL
    default:
      return null;
  }
}

function num(v) {
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

/**
 * Build a Library record. `id` and `platform` are required; everything else
 * degrades to null rather than to a wrong value.
 *
 * counts: { like, comment, view, share, save } — raw numbers or null.
 * Pass `sourceUrl` to override the derived permalink (Pinterest carries its own).
 */
function buildSavedEntry({
  id,
  platform,
  thumb = null,
  caption = null,
  authorName = null,
  username = null,
  authorUrl,
  counts = {},
  code = null,
  pk = null,
  mediaType = null,
  sourceUrl,
  now = Date.now(),
} = {}) {
  if (!id || !platform) return null;
  return {
    schema: SAVED_SCHEMA,
    videoId: String(id),
    platform,
    thumb: thumb || null,
    caption: caption || null,
    author: {
      name: authorName || username || "desconhecido",
      url: authorUrl !== undefined ? authorUrl : savedAuthorUrl(platform, username),
    },
    // `views` keeps its legacy key so existing VideoCard markup is unchanged.
    counts: {
      like: num(counts.like),
      comment: num(counts.comment),
      views: num(counts.view ?? counts.views),
      share: num(counts.share),
      save: num(counts.save),
    },
    code: code || null,
    pk: pk || null,
    media_type: mediaType || null,
    sourceUrl:
      sourceUrl !== undefined
        ? sourceUrl
        : savedSourceUrl(platform, { code, id, username }),
    updatedAt: now,
  };
}
// >>> inline:end

  async function ttSave(rec) {
    const entry = buildSavedEntry({
      id: rec.id,
      platform: "tiktok",
      thumb: rec.cover || rec.dynamic_cover || null,
      caption: rec.desc || null,
      authorName: rec.username || rec.nickname || null,
      username: rec.username || null,
      counts: {
        like: rec.digg_count,
        comment: rec.comment_count,
        view: rec.play_count,
        share: rec.share_count,
        save: rec.collect_count,
      },
      code: rec.id,
    });
    if (!entry) throw new Error("registro sem id");
    const res = await chrome.runtime.sendMessage({ type: "FBW_SAVED_TOGGLE", entry });
    if (!res || res.ok === false) throw new Error(res?.error || "falha ao salvar");
    return res.saved;
  }
  // Returns only after the background has actually answered: its { ok:false }
  // reply used to be dropped, so a failed download still flashed green.
  async function ttDownload(rec) {
    // Always the highest-quality rendition available.
    const url = rec.hd_url || rec.download_url || rec.video;
    if (!url) return false;
    try {
      const res = await chrome.runtime.sendMessage({ type: "FBW_DL_MEDIA", platform: "tiktok", kind: "video", url, filename: ttName(rec, ext(url, "video")) });
      return !(!res || res.ok === false);
    } catch {
      return false;
    }
  }
  // The cover. The -thumb suffix is what marks it; it shares the imagens/ bucket
  // with the full-size images, same as the panel and the Instagram rail.
  async function ttThumb(rec) {
    const url = rec.cover || rec.dynamic_cover;
    if (!url) throw new Error("sem miniatura");
    const e = ext(url, "image");
    const res = await chrome.runtime.sendMessage({
      type: "FBW_DL_MEDIA",
      platform: "tiktok",
      kind: "image",
      folder: "thumb",
      url,
      filename: ttName(rec, e).replace(new RegExp("\\." + e + "$"), "-thumb." + e),
    });
    if (!res || res.ok === false) throw new Error(res?.error || "download falhou");
  }
  async function ttTranscribe(rec, language) {
    if (!rec.video && !rec.subtitle) return false;
    chrome.runtime.sendMessage({
      type: "FBW_TRANSCRIBE", videoId: rec.id, mediaUrl: rec.video, platform: "tiktok",
      // The language just picked on the button; the stored choice only when a
      // caller had no menu to offer.
      language: language ? normTxLang(language) : await getTxLang(),
      // Caption-first: if TikTok ships an ASR track, transcribe from it (no Whisper).
      captionUrl: rec.subtitle && rec.subtitle.url ? rec.subtitle.url : null,
      captionFormat: rec.subtitle && rec.subtitle.format ? rec.subtitle.format : null,
      // TikTok names its own track (LanguageCodeName, e.g. "eng-US"). The record
      // must be labelled with THAT, not with the BR/EN pick — Whisper never ran.
      captionLang: rec.subtitle && rec.subtitle.lang ? rec.subtitle.lang : null,
      caption: rec.desc || null,
      author: { name: rec.username || rec.nickname || "unknown", url: rec.username ? `https://www.tiktok.com/@${rec.username}` : null },
      thumb: rec.cover || rec.dynamic_cover || null,
      sourceUrl: rec.username ? `https://www.tiktok.com/@${rec.username}/video/${rec.id}` : null,
      // Raw numbers — VideoCard formats at render time (schema 2).
      counts: { like: rec.digg_count ?? null, comment: rec.comment_count ?? null, views: rec.play_count ?? null },
    }).catch(() => {});
    return true;
  }
  function nativeClick(el) {
    if (!el) return false;
    const b = el.closest('button,[role="button"],a') || el;
    b.dispatchEvent(new PointerEvent("pointerdown", { bubbles: true }));
    b.dispatchEvent(new MouseEvent("mousedown", { bubbles: true }));
    b.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
    b.click();
    return true;
  }
  function ttLike() {
    const el = document.querySelector('[data-e2e="like-icon"], [data-e2e="browse-like-icon"]');
    return nativeClick(el);
  }
  // Open the comment panel and auto-scroll it a few times so the passive fetch hook
  // bulk-captures the thread (top-level + reply pages) into the store.
  async function ttScrape() {
    const open = document.querySelector('[data-e2e="comment-icon"], [data-e2e="browse-comment-icon"]');
    if (open) nativeClick(open);
    await new Promise((r) => setTimeout(r, 900));
    const box = document.querySelector('[data-e2e="comment-list"], [class*="CommentListContainer"], [class*="DivCommentListContainer"]');
    for (let i = 0; i < 8; i++) {
      if (box) box.scrollTop = box.scrollHeight;
      else window.scrollBy(0, 700);
      // expand a couple of "view replies" toggles if present
      document.querySelectorAll('[data-e2e="view-more-1"], [class*="DivViewRepliesContainer"] span').forEach((n, idx) => { if (idx < 4) nativeClick(n); });
      await new Promise((r) => setTimeout(r, 650));
    }
    return true;
  }

  // ============================================================
  // Stats overlay — the same rail the Instagram grid gets, on TikTok tiles and on
  // the player. TikTok's payloads make this cheaper than Instagram's: the follower
  // count rides along on every list item (authorStats), so views-per-follower is
  // there from the first paint instead of after an enrichment round-trip.
  // ============================================================
  // `compact` drops the rail to three rows and a smaller type size. TikTok mixes
  // tile sizes on one page — a /video/ page's "Você pode gostar" sidebar is
  // 185x249 against the search grid's 252x336 — and the full eight-row rail
  // overflows the small ones, clipping its own numbers. A short rail beats a
  // broken one, and beats no rail at all.
  const COMPACT_W = 230;
  function buildStatRail(rec, compact) {
    const el = document.createElement("div");
    el.className = compact ? "sw-ttovl compact" : "sw-ttovl";
    const rows = [];
    const hasViews = rec.play_count != null;
    if (compact) {
      const icon = compact ? TT_OVL.iconRow : TT_OVL.iconPrimary;
      if (hasViews)
        rows.push(`<div class="sw-ttovl-row primary">${overlayIcon("eye", icon)}<span>${fmtCount(rec.play_count)}</span></div>`);
      rows.push(`<div class="sw-ttovl-row">${overlayIcon("heart", TT_OVL.iconRow)}<span>${fmtCount(rec.digg_count)}</span></div>`);
      const erC = ttErLabel(rec, ttErWeights);
      if (erC != null)
        rows.push(`<div class="sw-ttovl-row">${overlayIcon("zap", TT_OVL.iconRow)}<span>${erC}</span></div>`);
      el.innerHTML = rows.join("");
      return el;
    }
    if (hasViews)
      rows.push(`<div class="sw-ttovl-row primary">${overlayIcon("eye", TT_OVL.iconPrimary)}<span>${fmtCount(rec.play_count)}</span></div>`);
    rows.push(`<div class="sw-ttovl-row${hasViews ? "" : " primary"}">${overlayIcon("heart", TT_OVL.iconRow)}<span>${fmtCount(rec.digg_count)}</span></div>`);
    rows.push(`<div class="sw-ttovl-row">${overlayIcon("msg", TT_OVL.iconRow)}<span>${fmtCount(rec.comment_count)}</span></div>`);
    // Shares and saves are TikTok's own: Instagram exposes neither, which is why
    // the ER weights differ and why these two rows have no IG counterpart.
    if (rec.share_count != null)
      rows.push(`<div class="sw-ttovl-row">${overlayIcon("repost", TT_OVL.iconRow)}<span>${fmtCount(rec.share_count)}</span></div>`);
    if (rec.collect_count != null)
      rows.push(`<div class="sw-ttovl-row">${overlayIcon("save", TT_OVL.iconRow)}<span>${fmtCount(rec.collect_count)}</span></div>`);
    const er = ttErLabel(rec, ttErWeights);
    if (er != null)
      rows.push(`<div class="sw-ttovl-row">${overlayIcon("zap", TT_OVL.iconRow)}<span>${er}</span></div>`);
    // How big the account is, and how far past it the video travelled — the pair
    // that turns "this did well" into "this did well FOR an account this size".
    if (rec.user_follower_count != null) {
      const vpf = fmtRatio(ttViewsPerFollower(rec));
      rows.push(
        `<div class="sw-ttovl-row">${overlayIcon("user", TT_OVL.iconRow)}<span>${fmtCount(rec.user_follower_count)}${vpf ? " · " + vpf : ""}</span></div>`,
      );
    }
    const d = fmtDate(rec.create_time);
    if (d) rows.push(`<div class="sw-ttovl-row">${overlayIcon("cal", TT_OVL.iconRow)}<span>${d}</span></div>`);
    el.innerHTML = rows.join("");
    return el;
  }

  // TikTok toggles playback on the POINTER sequence, not on click — a button that
  // only swallows `click` still pauses the video the moment you press it.
  // stopPropagation, not stopImmediatePropagation: the transcribe button's own
  // language menu listens on the button itself and must still run.
  function swallowPointer(btn) {
    const stop = (e) => { e.preventDefault(); e.stopPropagation(); };
    for (const ev of ["pointerdown", "mousedown", "pointerup", "mouseup"]) btn.addEventListener(ev, stop);
  }
  async function actRun(btn, fn) {
    try { await fn(); flashOverlayBtn(btn, "ok"); }
    catch (e) { flashOverlayBtn(btn, "err"); console.warn("[fbw] tt overlay action failed", e); }
  }
  function buildTileActs(rec) {
    const wrap = document.createElement("div");
    wrap.className = "sw-ttacts";
    const mk = (icon, title, fn) => {
      const b = document.createElement("button");
      b.className = "sw-ttact";
      b.type = "button";
      b.title = title;
      b.innerHTML = overlayIcon(icon, 15);
      swallowPointer(b);
      b.addEventListener("click", (ev) => { ev.preventDefault(); ev.stopPropagation(); fn(b); });
      return b;
    };
    const saveBtn = mk("save", savedIds.has(rec.id) ? "Salvo — toque para remover" : "Salvar na Biblioteca", (b) =>
      actRun(b, async () => { b.classList.toggle("on", await ttSave(rec)); }),
    );
    if (savedIds.has(rec.id)) saveBtn.classList.add("on");
    wrap.appendChild(saveBtn);
    wrap.appendChild(mk("dl", "Baixar vídeo", (b) => actRun(b, async () => {
      if (!(await ttDownload(rec))) throw new Error("sem URL de vídeo");
    })));
    wrap.appendChild(mk("img", "Baixar miniatura", (b) => actRun(b, () => ttThumb(rec))));
    if (rec.video || rec.subtitle) {
      // Two taps, like every other rail: BR/EN first, then the job. A caption
      // track still wins over Whisper, and then the pick simply does not apply.
      const txBtn = mk("tx", "Transcrever", (b) =>
        openTxLangMenu(b, async (lang) => flashOverlayBtn(b, (await ttTranscribe(rec, lang)) ? "ok" : "err")),
      );
      enableTxBadge(txBtn);
      wrap.appendChild(txBtn);
    }
    return wrap;
  }

  // A tile's repaint signature. Counts arrive in waves (a search result is listed
  // before its authorStats join lands), so a rail built from the first wave has to
  // be rebuilt — an "already annotated, skip" test alone leaves it stale forever.
  const tileSig = (rec, compact) =>
    [rec.play_count, rec.digg_count, rec.comment_count, rec.share_count, rec.collect_count,
     rec.user_follower_count, rec.create_time, savedIds.has(rec.id) ? 1 : 0, ttErSig,
     compact ? "c" : "f"].join("|");
  const hasStats = (rec) =>
    rec && (rec.play_count != null || rec.digg_count != null || rec.comment_count != null);

  const tileId = (a) => {
    const m = (a.getAttribute("href") || "").match(/\/video\/(\d+)/);
    return m ? m[1] : null;
  };

  // ---- the top-level layer for player rails (see the CSS note) ----
  const ttLayerRails = new Map(); // host element -> its rails
  function ensureTtLayer() {
    let layer = document.getElementById("sw-tt-layer");
    if (!layer) {
      layer = document.createElement("div");
      layer.id = "sw-tt-layer";
      document.documentElement.appendChild(layer);
    }
    return layer;
  }
  function placeTtRails(host, rails) {
    const r = host.getBoundingClientRect();
    if (!host.isConnected || r.width < 100 || r.bottom < 0 || r.top > window.innerHeight) {
      rails.ovl.style.display = "none";
      rails.acts.style.display = "none";
      return;
    }
    rails.ovl.style.display = "";
    rails.acts.style.display = "";
    rails.acts.style.left = Math.round(r.left + 8) + "px";
    rails.acts.style.top = Math.round(r.top + 8) + "px";
    // Lower-middle, flush to the video's RIGHT edge. TikTok burns captions across
    // the lower-centre of the frame and hangs its own action rail just outside the
    // right edge, so this sits between them rather than on either.
    rails.ovl.style.left = "auto";
    // documentElement.clientWidth, NOT window.innerWidth: innerWidth counts the
    // scrollbar while a fixed element's `right` is measured without it, so every
    // offset came out ~15px further left than asked for.
    rails.ovl.style.right = Math.round(document.documentElement.clientWidth - r.right + 2) + "px";
    rails.ovl.style.top = Math.round(r.top + r.height * 0.55) + "px";
    rails.ovl.style.bottom = "auto";
  }
  function syncTtLayer() {
    for (const [host, rails] of ttLayerRails) {
      if (!host.isConnected) {
        rails.ovl.remove();
        rails.acts.remove();
        ttLayerRails.delete(host);
        continue;
      }
      placeTtRails(host, rails);
    }
  }
  let ttLayerQueued = false;
  const onLayerScroll = () => {
    if (!ttLayerRails.size || ttLayerQueued) return;
    ttLayerQueued = true;
    requestAnimationFrame(() => { ttLayerQueued = false; syncTtLayer(); });
  };
  window.addEventListener("scroll", onLayerScroll, { passive: true, capture: true });
  window.addEventListener("resize", syncTtLayer, { passive: true });

  // The box to hang the player rails on: the nearest positioned-looking ancestor
  // of the centered <video> that is still the size of the video itself.
  function playerHost(video) {
    let el = video;
    for (let i = 0; i < 4 && el && el.parentElement; i++) {
      const p = el.parentElement;
      const pr = p.getBoundingClientRect();
      const vr = video.getBoundingClientRect();
      if (Math.abs(pr.width - vr.width) > 40 || Math.abs(pr.height - vr.height) > 40) break;
      el = p;
    }
    return el;
  }

  function renderTileOverlays() {
    if (disabled || document.visibilityState !== "visible") return;
    if (!overlayOn) {
      if (document.querySelector(".sw-ttovl, .sw-ttacts")) {
        tileObserver.disconnect();
        document.querySelectorAll(".sw-ttovl, .sw-ttacts").forEach((e) => e.remove());
        ttLayerRails.clear(); // the layer's rails were in that sweep
        observeBody();
      }
      return;
    }
    // Pass 1 does ZERO layout reads — rects are only measured for tiles that
    // actually need (re)building, and the observer is disconnected while we append
    // our own nodes so we never re-trigger ourselves.
    const toBuild = [];
    for (const a of document.querySelectorAll('a[href*="/video/"]')) {
      const id = tileId(a);
      if (!id) continue;
      const rec = byId.get(id);
      if (!hasStats(rec)) continue; // no stats yet → no empty box
      // A rail already on the tile tells us which tier it was built at, so the
      // common case still costs no layout read; only unstamped tiles are measured.
      const built = a.querySelector(":scope > .sw-ttovl");
      const compact = built ? built.classList.contains("compact") : a.getBoundingClientRect().width < COMPACT_W;
      const sig = tileSig(rec, compact);
      if (a.dataset.swId === id && a.dataset.swSig === sig && built) continue;
      toBuild.push([a, id, rec, sig]);
    }
    if (!toBuild.length) return;
    ensureStyle();
    tileObserver.disconnect();
    for (const [a, id, rec, sig] of toBuild) {
      // Real thumbnails only: TikTok wraps the same href around tiny text links
      // (the "@user · desc" line under a card). Small anchors stay unstamped and
      // are retried once they lay out.
      const rect = a.getBoundingClientRect();
      if (rect.width < 90 || rect.height < 120) continue;
      a.querySelectorAll(":scope > .sw-ttovl, :scope > .sw-ttacts").forEach((e) => e.remove());
      a.dataset.swId = id;
      a.dataset.swSig = sig;
      if (getComputedStyle(a).position === "static") a.style.position = "relative";
      a.appendChild(buildStatRail(rec, rect.width < COMPACT_W));
      a.appendChild(buildTileActs(rec));
    }
    observeBody();
  }

  // The player's own rail. Separate from the tile pass because it must live in the
  // top-level layer (TikTok's click-eating layer) and is rebuilt on stats change,
  // not on DOM mutation.
  function renderPlayerRail(centered) {
    // A grid tile plays a muted preview on hover, and that preview is a <video>
    // big enough to look like a player — which would hang a SECOND, floating copy
    // of the rail over a tile that already carries its own. If the centered video
    // lives inside a tile we already annotated, the tile's rail is the right one.
    if (centered && centered.closest("a[data-sw-id]")) centered = null;
    if (!overlayOn || !centered) {
      for (const rails of ttLayerRails.values()) { rails.ovl.remove(); rails.acts.remove(); }
      ttLayerRails.clear();
      return;
    }
    const rec = currentRecord(centered);
    if (!hasStats(rec)) return;
    const host = playerHost(centered);
    const r = host.getBoundingClientRect();
    if (r.width < 200 || r.height < 200) return;
    // Drop rails belonging to a player that is no longer the active one.
    for (const [h, rails] of ttLayerRails)
      if (h !== host) { rails.ovl.remove(); rails.acts.remove(); ttLayerRails.delete(h); }
    const sig = tileSig(rec, false);
    const prev = ttLayerRails.get(host);
    // NO early "already has a rail" skip: on a /video/ page the SSR record and the
    // creator join land a beat apart, and a rail built before that would show
    // likes with no follower count and no ER, forever.
    if (prev && prev.sig === sig) { placeTtRails(host, prev); return; }
    ensureStyle();
    if (prev) { prev.ovl.remove(); prev.acts.remove(); }
    const layer = ensureTtLayer();
    const rails = { ovl: buildStatRail(rec), acts: buildTileActs(rec), sig };
    layer.appendChild(rails.ovl);
    layer.appendChild(rails.acts);
    ttLayerRails.set(host, rails);
    placeTtRails(host, rails);
  }

  // TikTok virtualizes its grids, so this fires often; debounced then run at idle
  // so a burst of mutations costs one off-path pass.
  const tileObserver = new MutationObserver(() => scheduleOverlay());
  const observeBody = () => {
    if (document.body) tileObserver.observe(document.body, { childList: true, subtree: true });
  };
  observeBody();

  chrome.storage?.local?.get(["sw_tt_overlay", TT_ER_WEIGHTS_KEY]).then((r) => {
    if (r?.sw_tt_overlay != null) overlayOn = !!r.sw_tt_overlay;
    applyTtErWeights(r && r[TT_ER_WEIGHTS_KEY]);
    scheduleOverlay();
  }).catch(() => {});
  function applyTtErWeights(raw) {
    ttErWeights = normalizeTtErWeights(raw);
    ttErSig = `${ttErWeights.like}/${ttErWeights.comment}/${ttErWeights.share}/${ttErWeights.save}`;
  }
  chrome.storage?.onChanged?.addListener((ch, area) => {
    if (area !== "local") return;
    if (ch.sw_tt_overlay) overlayOn = !!ch.sw_tt_overlay.newValue;
    if (ch[TT_ER_WEIGHTS_KEY]) applyTtErWeights(ch[TT_ER_WEIGHTS_KEY].newValue);
    if (ch.sw_tt_overlay || ch[TT_ER_WEIGHTS_KEY]) scheduleOverlay();
  });

  let overlayTimer = null;
  function scheduleOverlay() {
    clearTimeout(overlayTimer);
    overlayTimer = setTimeout(() => {
      maintainOverlay();
      if (typeof requestIdleCallback === "function")
        requestIdleCallback(renderTileOverlays, { timeout: 700 });
      else renderTileOverlays();
    }, 250);
  }
  function buildOverlay() {
    ensureStyle();
    const wrap = document.createElement("div");
    wrap.id = "sw-tt-acts";
    const mk = (name, tip, fn) => {
      const b = document.createElement("button");
      b.className = "sw-ttbtn";
      b.type = "button";
      b.dataset.act = name;
      b.setAttribute("data-tip", tip);
      b.innerHTML = overlayIcon(name, 19);
      b.addEventListener("click", (ev) => { ev.preventDefault(); ev.stopPropagation(); fn(b); });
      return b;
    };
    wrap.appendChild(mk("save", "Salvar na Biblioteca", async (b) => {
      const rec = currentRecord(); if (!rec) return flashOverlayBtn(b, "err");
      try {
        const saved = await ttSave(rec);
        b.classList.toggle("on", saved);
        flashOverlayBtn(b, "ok");
      } catch (e) {
        flashOverlayBtn(b, "err");
        console.warn("[fbw] tt save failed", e);
      }
    }));
    wrap.appendChild(mk("dl", "Baixar vídeo", async (b) => flashOverlayBtn(b, (await ttDownload(currentRecord() || {})) ? "ok" : "err")));
    // BR/EN first, then the job — same two taps as the Facebook rail. A caption
    // track still wins over Whisper, and then the pick simply does not apply.
    const ttTxBtn = mk("tx", "Transcrever", (b) =>
      openTxLangMenu(b, async (lang) =>
        flashOverlayBtn(b, (await ttTranscribe(currentRecord() || {}, lang)) ? "ok" : "err"),
      ),
    );
    enableTxBadge(ttTxBtn);
    wrap.appendChild(ttTxBtn);
    wrap.appendChild(mk("msg", "Coletar comentários", async (b) => { await ttScrape(); flashOverlayBtn(b, "ok"); }));
    wrap.appendChild(mk("heart", "Curtir", (b) => flashOverlayBtn(b, ttLike() ? "ok" : "err")));
    return wrap;
  }
  function maintainOverlay() {
    if (disabled || document.visibilityState !== "visible") return;
    ssrCreator(); // cheap: parses the blob once per profile path, not per tick
    // ONE layout pass per tick: mostCenteredVideo() reads a rect per <video>, and it
    // used to run twice (once here, once inside currentAwemeId()). Resolve it here
    // and thread it down.
    const centered = mostCenteredVideo();
    const onVideo = /\/video\/\d+/.test(location.pathname) || location.pathname.startsWith("/foryou") || location.pathname === "/" || !!centered;
    let wrap = document.getElementById("sw-tt-acts");
    if (!onVideo) { if (wrap) wrap.remove(); return; }
    if (!wrap) { wrap = buildOverlay(); (document.body || document.documentElement).appendChild(wrap); }
    // Reflect saved state + enable/disable media actions for the current record.
    const rec = currentRecord(centered);
    const sb = wrap.querySelector('[data-act="save"]');
    if (sb) sb.classList.toggle("on", !!(rec && savedIds.has(rec.id))); // mirrored, no storage read
    const hasMedia = !!(rec && (rec.video || rec.download_url));
    updateTxBadges(); // this tick is also the BR/EN badge's repaint loop
    for (const act of ["dl", "tx"]) {
      const b = wrap.querySelector(`[data-act="${act}"]`);
      if (b) b.toggleAttribute("disabled", !hasMedia);
    }
    renderPlayerRail(centered);
  }
  const overlayInterval = setInterval(maintainOverlay, 2000);
  window.addEventListener("scroll", scheduleOverlay, { passive: true });
  document.addEventListener("visibilitychange", scheduleOverlay);
  scheduleOverlay();
}
