// TikTok bridge — isolated content-script world.
//
// Receives the MAIN-world fetch/XHR capture (relayed via window.postMessage),
// keeps a surface-scoped video map + a per-video comment store, answers the side
// panel (FBW_TT_LIST / FBW_TT_COMMENTS / FBW_TT_CLEAR), AND injects an on-page
// action overlay (save / download / transcribe / scrape comments / like) so you
// can act on the current video without opening the panel.
//
// Kept import-free on purpose: an ES import would make CRXJS wrap this in a
// dynamic-import loader, which TikTok's strict CSP can kill (that would break all
// capture). So the few helpers it needs are inlined.

if (location.hostname.endsWith("tiktok.com") && !window.__fbwTtInit) {
  window.__fbwTtInit = true;

  // ---- generation takeover ----
  // An extension reload/update re-injects this file into a FRESH isolated world, so
  // the __fbwTtInit guard above does not stop the OLD world — only its chrome.* dies.
  // Without this, every reload left another 1s interval, another scroll listener and
  // another full store running for the page's lifetime. Newer generation announces;
  // older tears itself down. (Same pattern as content/fb/comments-scrape.js.)
  const GEN = Date.now() + ":" + Math.random();
  let disabled = false;
  const onTakeover = (e) => {
    if (e.source !== window || !e.data || e.data.__fbwTtTakeover === undefined) return;
    if (e.data.__fbwTtTakeover === GEN || disabled) return;
    disabled = true;
    clearInterval(overlayInterval);
    clearTimeout(overlayTimer);
    window.removeEventListener("scroll", scheduleOverlay);
    window.removeEventListener("message", onRelay);
    window.removeEventListener("message", onTakeover);
    document.removeEventListener("visibilitychange", scheduleOverlay);
    document.getElementById("sw-tt-acts")?.remove();
    byId.clear();
    comments.clear();
    stories.clear();
    lists.clear();
  };
  window.addEventListener("message", onTakeover);
  window.postMessage({ __fbwTtTakeover: GEN }, "*");

  const byId = new Map(); // aweme id -> record; insertion order preserved for the list
  const comments = new Map(); // aweme_id -> { items: Map<cid, comment> }
  const stories = new Map(); // owner username -> Map<id, story item>  (TikTok stories)
  const lists = new Map(); // list_id -> { meta, items: Map<id, rec> }  (playlists/collections)
  // <<< inline:src/lib/shared/txLang.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/txLang.js and run `npm run gen:inline`.
// The BR/EN transcription-language control that lives ON the page: the persisted
// choice, the little badge on a Transcribe button, and the two-item menu that opens
// when you press one. INLINED into content scripts — see src/lib/shared/README.md
// before editing (no imports allowed in this file).
//
// Facebook grew this first and Instagram/TikTok only got the storage half of it:
// they read `fbw_transcript_language` but had no way to SET it, so on Instagram the
// language was whatever the Facebook rail had last been left on. The three scripts
// also carried three hand-copied `normTxLang`/`getTxLang` pairs — the same drift
// this directory exists to stop.
//
// Deliberately NOT here: which button gets a badge, and when the badge is
// repainted. Each overlay has its own button class and its own render loop, so a
// platform opts a button in with enableTxBadge() and calls updateTxBadges() from
// whatever loop it already runs.

const TX_LANG_KEY = "fbw_transcript_language";
const TX_LANG_DEFAULT = "br";
const TX_LANG_OPTIONS = [
  { value: "br", label: "Português", short: "BR" },
  { value: "en", label: "English", short: "EN" },
];

function normTxLang(value) {
  const lang = String(value || "").trim().toLowerCase();
  if (lang === "en") return "en";
  if (lang === "br" || lang === "pt") return "br";
  return TX_LANG_DEFAULT;
}

function txLangInfo(value) {
  const lang = normTxLang(value);
  return TX_LANG_OPTIONS.find((o) => o.value === lang) || TX_LANG_OPTIONS[0];
}

// Where the menu goes for a button at `rect`, inside a `view` of {width,height}.
//
// Preferred side is LEFT of the button — the Facebook rail sits on the video's left
// edge and a menu opening rightwards would cover the video. A button too close to
// the left edge for that (Instagram's tile actions sit at left:7px) flips to the
// right instead of being clamped into a strip overlapping itself.
const TX_LANG_MENU_W = 124;
function txLangMenuPos(rect, view) {
  const preferred = rect.left - 102;
  const left = preferred < 8 ? rect.right + 6 : preferred;
  return {
    top: Math.max(8, Math.min(view.height - 92, rect.top)),
    left: Math.max(8, Math.min(view.width - 132, left)),
  };
}

const TX_LANG_CSS = `
.fbw-lang-host{position:relative}
.fbw-lang-badge{position:absolute;right:-5px;bottom:-5px;min-width:18px;height:14px;padding:0 3px;border-radius:5px;
  display:grid;place-items:center;background:rgba(15,23,42,.96);color:#dbeafe;border:1px solid rgba(150,185,255,.55);
  font:800 8px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:0;pointer-events:none}
.fbw-lang-menu{position:fixed;z-index:2147483600;display:grid;gap:4px;width:${TX_LANG_MENU_W}px;padding:6px;border-radius:9px;
  background:rgba(17,24,44,.98);border:1px solid rgba(150,185,255,.42);box-shadow:0 8px 24px rgba(0,0,0,.45);
  font:600 12px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#fff}
.fbw-lang-menu button{height:30px;border:0;border-radius:6px;background:transparent;color:#e5e7eb;text-align:left;
  padding:0 8px;cursor:pointer;font:inherit}
.fbw-lang-menu button:hover,.fbw-lang-menu button.active{background:rgba(59,130,246,.24);color:#fff}`;

// On <html>, not <body>: the menu itself is appended there (outside the page's
// React root, which reconciles <body> children away), so its rules must survive
// the same way.
function ensureTxLangStyle() {
  if (document.getElementById("fbw-lang-style")) return;
  const s = document.createElement("style");
  s.id = "fbw-lang-style";
  s.textContent = TX_LANG_CSS;
  (document.head || document.documentElement).appendChild(s);
}

let txLangCache = TX_LANG_DEFAULT;
// The buttons that asked for a badge. A Set (not a selector) because each overlay
// names its buttons differently, and pruning on the way past keeps rails that FB
// remounts constantly from leaking entries.
const txBadged = new Set();

async function getTxLang() {
  try {
    const r = await chrome.storage.local.get(TX_LANG_KEY);
    txLangCache = normTxLang(r?.[TX_LANG_KEY]);
  } catch {
    /* storage gone (extension reloaded under us) — keep the cached value */
  }
  return txLangCache;
}

async function setTxLang(value) {
  txLangCache = normTxLang(value);
  try {
    await chrome.storage.local.set({ [TX_LANG_KEY]: txLangCache });
  } catch {
    /* the caller still gets the normalized value for THIS job */
  }
  updateTxBadges();
  return txLangCache;
}

/** Opt a Transcribe button in: it gets the badge now and on every refresh. */
function enableTxBadge(btn) {
  if (!btn) return;
  ensureTxLangStyle();
  btn.classList.add("fbw-lang-host");
  txBadged.add(btn);
  paintTxBadge(btn);
}

/** Repaint one button's badge — a no-op for buttons that never opted in, so a
 *  platform's shared "button changed state" hook can call it blindly. */
function addTxBadge(btn) {
  if (btn && txBadged.has(btn)) paintTxBadge(btn);
}

function paintTxBadge(btn) {
  let badge = btn.querySelector(".fbw-lang-badge");
  if (!badge) {
    badge = document.createElement("span");
    badge.className = "fbw-lang-badge";
    btn.appendChild(badge);
  }
  badge.textContent = txLangInfo(btn.dataset.lang || txLangCache).short;
}

/** Repaint every opted-in badge, dropping buttons whose rail has been torn down.
 *  Busy buttons are skipped: their glyph is a spinner the badge would sit on. */
function updateTxBadges() {
  for (const btn of txBadged) {
    if (!btn.isConnected) {
      txBadged.delete(btn);
      continue;
    }
    if (!btn.classList.contains("busy")) paintTxBadge(btn);
  }
}

/** Load the stored choice and keep every badge in step with it — including when
 *  the OTHER platform's rail changes it in another tab. */
function watchTxLang() {
  getTxLang().then(updateTxBadges).catch(() => {});
  chrome.storage?.onChanged?.addListener?.((changes, area) => {
    if (area !== "local" || !changes[TX_LANG_KEY]) return;
    txLangCache = normTxLang(changes[TX_LANG_KEY].newValue);
    updateTxBadges();
  });
}

let txLangMenu = null;
let txLangOutside = null;

function closeTxLangMenu() {
  if (txLangOutside) {
    document.removeEventListener("pointerdown", txLangOutside, true);
    window.removeEventListener("blur", closeTxLangMenu);
    window.removeEventListener("scroll", closeTxLangMenu, true);
    txLangOutside = null;
  }
  if (txLangMenu) {
    txLangMenu.remove();
    txLangMenu = null;
  }
}

/**
 * Open the BR/EN menu for `btn`; `onPick(lang)` runs after the choice is saved.
 * A busy button is ignored — its job is already in flight.
 */
function openTxLangMenu(btn, onPick) {
  if (!btn || btn.classList.contains("busy")) return;
  ensureTxLangStyle();
  closeTxLangMenu();
  const pos = txLangMenuPos(btn.getBoundingClientRect(), {
    width: window.innerWidth,
    height: window.innerHeight,
  });
  const menu = document.createElement("div");
  menu.className = "fbw-lang-menu";
  menu.setAttribute("role", "menu");
  menu.style.top = `${pos.top}px`;
  menu.style.left = `${pos.left}px`;
  for (const opt of TX_LANG_OPTIONS) {
    const item = document.createElement("button");
    item.type = "button";
    item.className = opt.value === txLangCache ? "active" : "";
    item.textContent = opt.label;
    // The host page (FB's reel player, IG's story viewer) toggles playback on the
    // pointer sequence, so the whole sequence is swallowed — not just the click.
    item.addEventListener("pointerdown", (e) => { e.preventDefault(); e.stopPropagation(); });
    item.addEventListener("click", async (e) => {
      e.preventDefault();
      e.stopPropagation();
      const lang = await setTxLang(opt.value);
      btn.dataset.lang = lang;
      closeTxLangMenu();
      onPick(lang);
    });
    menu.appendChild(item);
  }
  txLangMenu = menu;
  document.documentElement.appendChild(menu);
  // Next tick: the click that OPENED the menu is still travelling, and a listener
  // armed synchronously would see it as an outside click and close immediately.
  setTimeout(() => {
    txLangOutside = (e) => {
      if (menu.contains(e.target) || btn.contains(e.target)) return;
      closeTxLangMenu();
    };
    document.addEventListener("pointerdown", txLangOutside, true);
    window.addEventListener("blur", closeTxLangMenu, { once: true });
    window.addEventListener("scroll", closeTxLangMenu, { once: true, capture: true });
  }, 0);
}
// >>> inline:end
  watchTxLang();
  // Bumped on every ingest. The panel sends its last seen value and we answer
  // { unchanged: true } when nothing moved, instead of structured-cloning the whole
  // store across processes every 2.5s.
  // One counter per store. A single shared counter meant a video ingest — which
  // happens constantly while the FYP streams — invalidated the comments, stories and
  // lists polls as well, so each of those re-serialised its whole payload every
  // 2.5s even though nothing in it had changed.
  const ver = { videos: 0, comments: 0, stories: 0, lists: 0 };
  const bump = (k) => { ver[k] += 1; };
  // Local mirror of the saved-post ids, kept in sync by one storage.onChanged
  // listener. The overlay used to chrome.storage.local.get("fbw_saved") on EVERY
  // 1s tick, deserializing the entire saved map (base64 thumbs included) into the
  // page process once a second.
  let savedIds = new Set();
  // The video whose comments were most recently fetched == the one you're viewing.
  // Lets the panel auto-follow the current video instead of sticking on a stale one.
  let lastCommentAweme = null;

  // Every store is capped — outer AND inner. Capping only the outer Map (as an
  // earlier version did) still lets a single scraped thread or a huge playlist grow
  // without limit, and the panel serializes all of it on every poll.
  const cap = (m, n) => { while (m.size > n) m.delete(m.keys().next().value); };

  function ingestStory(r) {
    const owner = r.reel_owner || r.username || "unknown";
    let S = stories.get(owner);
    if (!S) { S = new Map(); stories.set(owner, S); }
    bump("stories");
    const prev = S.get(r.id) || {};
    for (const k in r) if (r[k] != null || !(k in prev)) prev[k] = r[k];
    S.set(r.id, prev);
    cap(S, 100);
    cap(stories, 40);
  }
  function ingestListMeta(r) {
    let L = lists.get(r.list_id);
    if (!L) { L = { meta: {}, items: new Map() }; lists.set(r.list_id, L); }
    bump("lists");
    for (const k in r) if (r[k] != null) L.meta[k] = r[k];
    cap(lists, 60);
  }
  function ingestListVideo(r) {
    let L = lists.get(r.list_id);
    if (!L) { L = { meta: { list_id: r.list_id }, items: new Map() }; lists.set(r.list_id, L); }
    bump("lists");
    L.items.set(r.id, r);
    cap(L.items, 300);
    cap(lists, 60); // this path creates entries too, so it must cap as well
  }

  function surfaceKey() {
    const p = location.pathname;
    let m;
    if ((m = p.match(/^\/@([^/]+)/))) return "profile:" + decodeURIComponent(m[1]).toLowerCase();
    if ((m = p.match(/^\/tag\/([^/]+)/))) return "tag:" + decodeURIComponent(m[1]).toLowerCase();
    if (p.startsWith("/search")) {
      const q = new URLSearchParams(location.search).get("q");
      return "search:" + (q ? q.toLowerCase() : "");
    }
    if (p.startsWith("/foryou") || p === "/") return "feed";
    if (p.startsWith("/explore")) return "explore";
    return "feed";
  }

  // The aweme id of the video the user is currently on. URL first (detail pages +
  // FYP once TikTok rewrites the path), then the most-centered <video>'s nearest
  // /video/<id> link, then the last video whose comments loaded.
  function currentAwemeId(centered) {
    const m = location.pathname.match(/\/video\/(\d+)/);
    if (m) return m[1];
    const v = centered !== undefined ? centered : mostCenteredVideo();
    if (v) {
      let el = v;
      for (let i = 0; i < 8 && el; i++) {
        const a = el.querySelector?.('a[href*="/video/"]');
        const mm = a && (a.getAttribute("href") || "").match(/\/video\/(\d+)/);
        if (mm) return mm[1];
        el = el.parentElement;
      }
    }
    return lastCommentAweme;
  }

  function mostCenteredVideo() {
    let best = null, bestScore = -Infinity;
    for (const v of document.querySelectorAll("video")) {
      const r = v.getBoundingClientRect();
      if (r.width < 120 || r.height < 120) continue;
      const visible = Math.min(r.bottom, innerHeight) - Math.max(r.top, 0);
      if (visible <= 0) continue;
      const score = visible - Math.abs(r.top + r.height / 2 - innerHeight / 2);
      if (score > bestScore) { bestScore = score; best = v; }
    }
    return best;
  }

  function ingestComment(r) {
    if (!r.aweme_id || !r.cid) return;
    lastCommentAweme = r.aweme_id;
    let C = comments.get(r.aweme_id);
    if (!C) { C = { aweme_id: r.aweme_id, items: new Map() }; comments.set(r.aweme_id, C); }
    bump("comments");
    const prev = C.items.get(r.cid) || {};
    for (const k in r) if (r[k] != null || !(k in prev)) prev[k] = r[k];
    C.items.set(r.cid, prev);
    cap(C.items, 500); // a scraped thread is unbounded upstream
    cap(comments, 60);
  }

  const onRelay = (e) => {
    if (e.source !== window || !e.data || !e.data.__fbwTt) return;
    if (disabled) return;
    const surface = surfaceKey();
    for (const r of e.data.records || []) {
      if (r.__kind === "comment") { ingestComment(r); continue; }
      if (r.__kind === "tt_list") { ingestListMeta(r); continue; }
      if (r.__kind === "tt_story") { ingestStory(r); continue; }
      if (!r.id) continue;
      r.surface = surface;
      if (!r.username && surface.startsWith("profile:")) r.username = surface.slice("profile:".length);
      const prev = byId.get(r.id) || {};
      for (const k in r) if (r[k] != null || !(k in prev)) prev[k] = r[k];
      byId.set(r.id, prev);
      if (r.list_id) ingestListVideo(prev); // playlist/collection membership
    }
    while (byId.size > 500) byId.delete(byId.keys().next().value);
    bump("videos"); // lets the panel poll short-circuit when nothing changed
    scheduleOverlay();
  };
  window.addEventListener("message", onRelay);

  // Mirror fbw_saved ids locally (see savedIds above).
  const refreshSaved = (map) => { savedIds = new Set(Object.keys(map || {})); };
  chrome.storage?.local?.get("fbw_saved").then((r) => refreshSaved(r?.fbw_saved)).catch(() => {});
  const onSavedChanged = (ch, area) => {
    if (area === "local" && ch.fbw_saved) { refreshSaved(ch.fbw_saved.newValue); scheduleOverlay(); }
  };
  chrome.storage?.onChanged?.addListener(onSavedChanged);

  let lastReplayReq = 0;
  function requestReplay() {
    const now = Date.now();
    if (now - lastReplayReq < 600) return;
    lastReplayReq = now;
    window.postMessage({ __fbwTtReq: true }, location.origin);
  }
  requestReplay();
  setTimeout(requestReplay, 700);
  setTimeout(requestReplay, 1800);

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    // Every poll carries the panel's last seen `version`; when nothing has been
    // ingested since, answer with a tiny {unchanged} instead of structured-cloning
    // the whole store across processes.
    if (msg?.type === "FBW_TT_LIST") {
      if (msg.since === ver.videos) {
        // surface/current are cheap and CHANGE without a new capture (SPA nav,
        // scrolling the feed), so they ship even when the store has not moved.
        sendResponse({ unchanged: true, version: ver.videos, surface: surfaceKey(), current: currentAwemeId() });
        return;
      }
      sendResponse({ records: Array.from(byId.values()), surface: surfaceKey(), current: currentAwemeId(), version: ver.videos });
      return;
    }
    if (msg?.type === "FBW_TT_COMMENTS") {
      if (msg.since === ver.comments) {
        sendResponse({ unchanged: true, version: ver.comments, current: lastCommentAweme || currentAwemeId() });
        return;
      }
      const videos = [];
      for (const C of comments.values()) {
        videos.push({ aweme_id: C.aweme_id, meta: byId.get(C.aweme_id) || null, comments: Array.from(C.items.values()) });
      }
      // `current` = the video the user is viewing → the panel auto-selects it.
      sendResponse({ videos, current: lastCommentAweme || currentAwemeId(), version: ver.comments });
      return;
    }
    if (msg?.type === "FBW_TT_STORIES") {
      if (msg.since === ver.stories) { sendResponse({ unchanged: true, version: ver.stories }); return; }
      const out = [];
      for (const [owner, S] of stories) out.push({ owner, items: Array.from(S.values()) });
      sendResponse({ owners: out, version: ver.stories });
      return;
    }
    if (msg?.type === "FBW_TT_LISTS") {
      if (msg.since === ver.lists) { sendResponse({ unchanged: true, version: ver.lists }); return; }
      const out = [];
      for (const [, L] of lists) out.push({ ...L.meta, items: Array.from(L.items.values()) });
      sendResponse({ lists: out, version: ver.lists });
      return;
    }
    if (msg?.type === "FBW_TT_CLEAR") {
      byId.clear();
      comments.clear();
      stories.clear();
      lists.clear();
      lastCommentAweme = null;
      bump("videos"); bump("comments"); bump("stories"); bump("lists");
      requestReplay(); // re-pull the current surface so the panel isn't left empty
      sendResponse?.({ ok: true });
      return;
    }
    if (msg?.type === "FBW_PING") { sendResponse?.({ ok: true }); }
  });

  // ============================================================
  // On-page action overlay — a floating stack pinned to the window's right edge
  // (clear of TikTok's own action rail, which hugs the video). Acts on the current
  // video: save / download / transcribe (need the captured record for the media
  // URL), scrape-comments (open + auto-scroll the comment panel → passive capture),
  // like (click TikTok's native control). No blur (repaints jank the feed).
  // ============================================================
  // Icons and the ok/err flash are GENERATED from src/lib/shared/overlayUi.js —
  // the same set the Instagram and Pinterest overlays draw from (this script cannot
  // import; run `npm run gen:inline` after editing the source).
// <<< inline:src/lib/shared/overlayUi.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/overlayUi.js and run `npm run gen:inline`.
// The button machinery behind the injected page overlays: one icon vocabulary and
// one state machine. INLINED into content scripts — see src/lib/shared/README.md
// before editing (no imports allowed in this file).
//
// Instagram, TikTok and Pinterest each grew their own copy of both and the copies
// had already drifted: three stroke widths for the same lucide glyphs, two
// orderings of the same file-text paths, and 1200 / 1300 / 2500ms for the same
// "did it work?" flash.
//
// What is deliberately NOT here: the CSS and the render loops. Those are genuinely
// per-platform (different tile structures, different mutation patterns) and each
// overlay keeps its own button class — .sw-actbtn, .sw-ttbtn, .sw-pinbtn — so the
// state machine below only ever touches the element it is handed.

// lucide-style 24×24 stroked glyphs, rendered by overlayIcon().
const OVERLAY_ICONS = {
  dl: '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/>',
  save: '<path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>',
  img: '<rect width="18" height="18" x="3" y="3" rx="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.1-3.1a2 2 0 0 0-2.8 0L6 21"/>',
  tx: '<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/>',
  layers: '<path d="M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z"/><path d="M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12"/><path d="M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17"/>',
  msg: '<path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/>',
  heart: '<path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/>',
  ok: '<polyline points="20 6 9 17 4 12"/>',
  err: '<line x1="18" x2="6" y1="6" y2="18"/><line x1="6" x2="18" y1="6" y2="18"/>',
  // Instagram's stats rail only. Kept here so there is one place to look up a
  // glyph, rather than one shared map plus a private map for the odd ones out.
  eye: '<circle cx="12" cy="12" r="3"/><path d="M2.06 12.35a1 1 0 0 1 0-.7 10.75 10.75 0 0 1 19.88 0 1 1 0 0 1 0 .7 10.75 10.75 0 0 1-19.88 0"/>',
  zap: '<path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"/>',
  repost: '<path d="m17 2 4 4-4 4"/><path d="M3 11v-1a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v1a4 4 0 0 1-4 4H3"/>',
  cal: '<path d="M8 2v4"/><path d="M16 2v4"/><rect width="18" height="18" x="3" y="4" rx="2"/><path d="M3 10h18"/>',
  // Follower count — how big the account behind the post is.
  user: '<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
  // The sound a reel rides, so a trend can be traced to its audio.
  audio: '<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',
};

// 15px is the tile-action button's glyph; the floating rails pass their own size.
// An unknown name renders an empty <svg> rather than the string "undefined".
function overlayIcon(name, size = 15) {
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" width="${size}" height="${size}">${OVERLAY_ICONS[name] || ""}</svg>`;
}

// How long ok/err feedback stays before the button goes back to idle. Pinterest's
// 2.5s is the one long enough to be read on a grid that is still mutating.
const OVERLAY_FLASH_MS = 2500;

/**
 * busy / ok / err / idle for one overlay button. Only the STATE classes are
 * shared; the button's own class is the platform's business, so this takes the
 * element and never a class prefix.
 *
 * A button that names its idle glyph in `data-kind` also gets the glyph swapped
 * (Pinterest's spinner and ✓/✗); one that doesn't just recolours, which is what
 * the Instagram and TikTok rails have always done.
 */
function setOverlayBtnState(btn, state) {
  // Clear any pending flash first. Without this a flash armed by an earlier click
  // fires mid-way through a later one, strips the `busy` class and defeats the
  // re-entrancy guard that class IS on Pinterest (pin-api.js checks it before
  // starting a download).
  if (btn.__swFlashTimer) {
    clearTimeout(btn.__swFlashTimer);
    btn.__swFlashTimer = null;
  }
  btn.classList.remove("busy", "ok", "err");
  if (state === "busy" || state === "ok" || state === "err") btn.classList.add(state);
  const kind = btn.dataset.kind;
  if (!kind) return;
  btn.innerHTML = overlayIcon(state === "ok" || state === "err" ? state : kind);
}

/**
 * Show how an action actually ended, then return the button to idle. The timer is
 * kept on the button so a second click restarts it — otherwise the first click's
 * timer resets a button the second one has just put back into busy.
 */
function flashOverlayBtn(btn, state) {
  setOverlayBtnState(btn, state);
  clearTimeout(btn.__swFlashTimer);
  btn.__swFlashTimer = setTimeout(() => {
    if (btn.isConnected) setOverlayBtnState(btn, "idle");
  }, OVERLAY_FLASH_MS);
}
// >>> inline:end

  let styleAdded = false;
  function ensureStyle() {
    if (styleAdded) return;
    styleAdded = true;
    const s = document.createElement("style");
    s.textContent = `
      #sw-tt-acts{position:fixed;top:50%;right:16px;transform:translateY(-50%);z-index:2147482000;
        display:flex;flex-direction:column;gap:9px}
      .sw-ttbtn{position:relative;display:grid;place-items:center;width:42px;height:42px;border-radius:12px;cursor:pointer;color:#fff;
        background:rgba(20,20,24,.92);border:1px solid rgba(150,185,255,.45);box-shadow:0 2px 10px rgba(0,0,0,.4);
        transition:background .15s,color .15s,transform .1s}
      .sw-ttbtn:hover{background:rgba(40,44,60,.96);transform:translateY(-1px)}
      .sw-ttbtn.ok{color:#34d399;border-color:rgba(52,211,153,.6)}
      .sw-ttbtn.err{color:#f87171;border-color:rgba(248,113,113,.6)}
      .sw-ttbtn.on{color:#facc15;border-color:rgba(250,204,21,.6)}
      .sw-ttbtn.on svg{fill:#facc15}
      .sw-ttbtn[disabled]{opacity:.4;cursor:default}
      .sw-ttbtn[data-tip]:hover::after{content:attr(data-tip);position:absolute;right:calc(100% + 8px);top:50%;
        transform:translateY(-50%);background:rgba(17,20,32,.97);color:#fff;font:600 11px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
        padding:5px 8px;border-radius:6px;white-space:nowrap;pointer-events:none;box-shadow:0 2px 8px rgba(0,0,0,.5);border:1px solid rgba(150,185,255,.28)}`;
    (document.head || document.documentElement).appendChild(s);
  }

  const ext = (url, kind) => {
    const m = String(url || "").match(/\.(mp4|mov|webm|jpg|jpeg|png|webp)(\?|$)/i);
    if (m) { const e = m[1].toLowerCase(); return e === "jpeg" ? "jpg" : e; }
    return kind === "video" ? "mp4" : "jpg";
  };
  const sanit = (s) => String(s || "").replace(/[\\/:*?"<>|]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 40);
  const ttName = (rec, e) => `tt-${sanit(rec.username || rec.nickname)}-${rec.id}.${e}`;

  // Video-detail pages don't fetch the open video via item_list (its data is in the
  // SSR hydration blob), so byId won't have it. Map the blob's itemStruct as a
  // fallback (id-matched so a stale blob after SPA nav is ignored).
  function mapItem(it) {
    const v = it.video || {}, a = it.author || {}, s = it.statsV2 || it.stats || {};
    const n = (x) => (x == null ? null : typeof x === "number" ? x : Number.isFinite(+x) ? +x : null);
    // highest-res gear
    let hd = null;
    for (const g of (Array.isArray(v.bitrateInfo) ? v.bitrateInfo : [])) {
      const pa = g.PlayAddr || {}, url = (pa.UrlList && pa.UrlList[0]) || null;
      if (!url) continue;
      const score = (n(pa.Width) || 0) * (n(pa.Height) || 0) * 1e6 + (n(g.Bitrate) || 0);
      if (!hd || score > hd.score) hd = { url, res: `${n(pa.Width)}x${n(pa.Height)}`, score };
    }
    const subs = Array.isArray(v.subtitleInfos) ? v.subtitleInfos : [];
    const sp = subs.find((x) => /eng/i.test(x.LanguageCodeName || "")) || subs[0];
    const sub = sp ? { url: sp.Url || (sp.UrlList && sp.UrlList[0]) || null, lang: sp.LanguageCodeName || null, format: (sp.Format || "webvtt").toLowerCase() } : null;
    return {
      id: String(it.id || v.id || ""), username: a.uniqueId || null, nickname: a.nickname || null,
      play_count: n(s.playCount), digg_count: n(s.diggCount), comment_count: n(s.commentCount),
      share_count: n(s.shareCount), collect_count: n(s.collectCount), repost_count: n(s.repostCount),
      video: v.playAddr || null, download_url: v.downloadAddr || v.playAddr || null,
      hd_url: (hd && hd.url) || v.downloadAddr || v.playAddr || null, hd_res: hd ? hd.res : null,
      subtitle: sub && sub.url ? sub : null,
      cover: v.cover || v.originCover || null, dynamic_cover: v.dynamicCover || null,
      duration: n(v.duration), desc: (it.desc || "").slice(0, 500) || null, create_time: n(it.createTime),
      hashtags: Array.isArray(it.challenges) ? it.challenges.map((c) => c && c.title).filter(Boolean) : [],
      pinned: !!it.isPinnedItem, surface: surfaceKey(),
    };
  }
  // Memoized per aweme id INCLUDING failures. The blob is hundreds of KB to a few
  // MB; on the FYP feed (or after any SPA nav) the id never matches, so an unmemoized
  // version re-parsed the whole thing on every 1s tick, forever.
  const ssrTried = new Set();
  function ssrRecord(awemeId) {
    if (ssrTried.has(awemeId)) return null; // already parsed once for this id
    ssrTried.add(awemeId);
    cap(ssrTried, 200);
    try {
      const el = document.getElementById("__UNIVERSAL_DATA_FOR_REHYDRATION__");
      if (!el) return null;
      const scope = (JSON.parse(el.textContent).__DEFAULT_SCOPE__) || {};
      const it = scope["webapp.video-detail"]?.itemInfo?.itemStruct;
      if (!it || String(it.id) !== String(awemeId)) return null;
      const r = mapItem(it);
      return r.id ? r : null;
    } catch {
      return null;
    }
  }
  function currentRecord(centered) {
    const id = currentAwemeId(centered);
    if (!id) return null;
    let rec = byId.get(id);
    if (!rec || !(rec.video || rec.download_url)) {
      const ssr = ssrRecord(id);
      if (ssr) { rec = { ...(rec || {}), ...ssr }; byId.set(id, rec); } // cache so the panel sees it too
    }
    return rec || null;
  }

  // Library record shape — GENERATED from src/lib/shared/savedEntry.js (this
  // script cannot import; run `npm run gen:inline`). The background owns and
  // serializes the write, so a panel toggle and a page toggle can't clobber.
// <<< inline:src/lib/shared/counts.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/counts.js and run `npm run gen:inline`.
// Localized count parsing/formatting. INLINED into content scripts — see
// src/lib/shared/README.md before editing (no imports allowed in this file).

// Localized abbreviated-count multipliers. FB/IG/TikTok render counts abbreviated
// with a locale word or suffix: pt-br "mil"/"mi", en "K"/"M", plus other locales'
// short forms. A missing entry here means a real count parses as null, which is
// how the comment scraper used to lose reaction counts on non-pt/en UIs.
const COUNT_UNITS = {
  k: 1e3, mil: 1e3, rb: 1e3, tis: 1e3, tys: 1e3, tusen: 1e3,
  m: 1e6, mi: 1e6, mio: 1e6, jt: 1e6, mln: 1e6, mn: 1e6,
  b: 1e9, mrd: 1e9, bi: 1e9,
};

/**
 * Parse a localized count string into a number, or null.
 *   "14 mil" -> 14000   "1,5 mil" -> 1500   "1.2M" -> 1200000   "543" -> 543
 * When a unit word/suffix is present the numeric part is a small decimal, so a
 * comma is the decimal separator (pt-br "1,5"). Without a unit the value is a
 * plain integer whose separators are thousands groups and are stripped.
 */
function parseCount(text) {
  if (text == null) return null;
  if (typeof text === "number") return Number.isFinite(text) ? text : null;
  // A trailing period is an abbreviation mark in some locales ("1,2 mil.").
  const s = String(text).trim().toLowerCase().replace(/\s+/g, "").replace(/\.$/, "");
  if (!s) return null;
  const m = s.match(/^([\d.,]+)([a-zçã]+)?$/);
  if (!m) return null;
  const rawNum = m[1];
  const unitWord = m[2] || "";
  const mult = unitWord ? COUNT_UNITS[unitWord] : 1;
  if (unitWord && mult == null) return null; // unknown suffix → not a count
  // Separator rules, in order of how much they tell us:
  //   both present   → the LAST one is the decimal, the other is grouping.
  //                    "1.234,5" is 1234.5 (pt-BR) and "1,234.5" is 1234.5 (en).
  //   one + a unit   → that one is the decimal ("76,8 mil", "1.2M").
  //   one, no unit   → grouping; strip it ("1.234" is 1234, "76.800" is 76800).
  const hasDot = rawNum.includes(".");
  const hasComma = rawNum.includes(",");
  let norm;
  if (hasDot && hasComma) {
    const decimal = rawNum.lastIndexOf(".") > rawNum.lastIndexOf(",") ? "." : ",";
    const grouping = decimal === "." ? "," : ".";
    norm = rawNum.split(grouping).join("").replace(decimal, ".");
  } else if (unitWord) {
    norm = rawNum.replace(",", ".");
  } else {
    norm = rawNum.replace(/[.,]/g, "");
  }
  const num = parseFloat(norm);
  if (!Number.isFinite(num)) return null;
  return Math.round(num * mult);
}

// Display formatting. 964490 -> "964.5K". Null renders as an em dash rather than
// "0" — an unknown count and a zero count are different facts. Counts are stored
// raw and formatted here at render time.
function fmtCount(n) {
  if (n == null) return "—";
  if (n >= 1e6) return (n / 1e6).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1e3) return (n / 1e3).toFixed(1).replace(/\.0$/, "") + "K";
  return String(n);
}
// >>> inline:end

// <<< inline:src/lib/shared/savedEntry.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/savedEntry.js and run `npm run gen:inline`.
// The ONE shape of a saved-Library record, and the permalink rules behind it.
// INLINED into content scripts — see src/lib/shared/README.md before editing
// (no imports allowed in this file).
//
// This exists because `fbw_saved` used to be written from ten places (six panel
// tools, three page overlays, the transcription rail) with five different shapes:
//
//   * counts were pre-formatted strings, sometimes via an UNGUARDED fmtCount(null)
//     (so whatever that returned got persisted instead of null), and Pinterest
//     stored the literal string "—" for views where everything else stored null;
//   * `sourceUrl` was present in some and absent in others, and VideoCard falls
//     back to `facebook.com/reel/<id>` when it's missing — a dead link for a
//     TikTok or Pinterest item;
//   * TikTok stored a signed, expiring CDN URL as `thumb`.
//
// Counts are stored as RAW NUMBERS (or null) — never formatted. Formatting is a
// render-time concern, and storing numbers keeps the Library sortable. VideoCard
// tolerates strings for records written before schema 2.

const SAVED_SCHEMA = 2;

// Absolute permalink back to the item, per platform. Centralized because a
// missing sourceUrl silently degrades into a wrong Facebook link.
function savedSourceUrl(platform, { code, id, username } = {}) {
  const key = code || id;
  switch (platform) {
    case "instagram":
      return key ? `https://www.instagram.com/p/${key}/` : null;
    case "tiktok":
      return username && id ? `https://www.tiktok.com/@${username}/video/${id}` : null;
    case "facebook":
      return key ? `https://www.facebook.com/reel/${key}` : null;
    case "pinterest":
      return key ? `https://www.pinterest.com/pin/${key}/` : null;
    default:
      return null;
  }
}

// Profile URL. FB/IG are stored relative (VideoCard prepends the origin);
// TikTok/Pinterest are absolute, and prepending an origin to those would nest one
// URL inside another and produce a dead link.
function savedAuthorUrl(platform, username) {
  if (!username) return null;
  switch (platform) {
    case "instagram":
      return `/${username}/`;
    case "tiktok":
      return `https://www.tiktok.com/@${username}`;
    case "pinterest":
      return `https://www.pinterest.com/${username}/`;
    case "facebook":
      return null; // FB reels grids expose no reliable author URL
    default:
      return null;
  }
}

function num(v) {
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

/**
 * Build a Library record. `id` and `platform` are required; everything else
 * degrades to null rather than to a wrong value.
 *
 * counts: { like, comment, view, share, save } — raw numbers or null.
 * Pass `sourceUrl` to override the derived permalink (Pinterest carries its own).
 */
function buildSavedEntry({
  id,
  platform,
  thumb = null,
  caption = null,
  authorName = null,
  username = null,
  authorUrl,
  counts = {},
  code = null,
  pk = null,
  mediaType = null,
  sourceUrl,
  now = Date.now(),
} = {}) {
  if (!id || !platform) return null;
  return {
    schema: SAVED_SCHEMA,
    videoId: String(id),
    platform,
    thumb: thumb || null,
    caption: caption || null,
    author: {
      name: authorName || username || "desconhecido",
      url: authorUrl !== undefined ? authorUrl : savedAuthorUrl(platform, username),
    },
    // `views` keeps its legacy key so existing VideoCard markup is unchanged.
    counts: {
      like: num(counts.like),
      comment: num(counts.comment),
      views: num(counts.view ?? counts.views),
      share: num(counts.share),
      save: num(counts.save),
    },
    code: code || null,
    pk: pk || null,
    media_type: mediaType || null,
    sourceUrl:
      sourceUrl !== undefined
        ? sourceUrl
        : savedSourceUrl(platform, { code, id, username }),
    updatedAt: now,
  };
}
// >>> inline:end

  async function ttSave(rec) {
    const entry = buildSavedEntry({
      id: rec.id,
      platform: "tiktok",
      thumb: rec.cover || rec.dynamic_cover || null,
      caption: rec.desc || null,
      authorName: rec.username || rec.nickname || null,
      username: rec.username || null,
      counts: {
        like: rec.digg_count,
        comment: rec.comment_count,
        view: rec.play_count,
        share: rec.share_count,
        save: rec.collect_count,
      },
      code: rec.id,
    });
    if (!entry) throw new Error("registro sem id");
    const res = await chrome.runtime.sendMessage({ type: "FBW_SAVED_TOGGLE", entry });
    if (!res || res.ok === false) throw new Error(res?.error || "falha ao salvar");
    return res.saved;
  }
  // Returns only after the background has actually answered: its { ok:false }
  // reply used to be dropped, so a failed download still flashed green.
  async function ttDownload(rec) {
    // Always the highest-quality rendition available.
    const url = rec.hd_url || rec.download_url || rec.video;
    if (!url) return false;
    try {
      const res = await chrome.runtime.sendMessage({ type: "FBW_DL_MEDIA", platform: "tiktok", kind: "video", url, filename: ttName(rec, ext(url, "video")) });
      return !(!res || res.ok === false);
    } catch {
      return false;
    }
  }
  async function ttTranscribe(rec, language) {
    if (!rec.video && !rec.subtitle) return false;
    chrome.runtime.sendMessage({
      type: "FBW_TRANSCRIBE", videoId: rec.id, mediaUrl: rec.video, platform: "tiktok",
      // The language just picked on the button; the stored choice only when a
      // caller had no menu to offer.
      language: language ? normTxLang(language) : await getTxLang(),
      // Caption-first: if TikTok ships an ASR track, transcribe from it (no Whisper).
      captionUrl: rec.subtitle && rec.subtitle.url ? rec.subtitle.url : null,
      captionFormat: rec.subtitle && rec.subtitle.format ? rec.subtitle.format : null,
      // TikTok names its own track (LanguageCodeName, e.g. "eng-US"). The record
      // must be labelled with THAT, not with the BR/EN pick — Whisper never ran.
      captionLang: rec.subtitle && rec.subtitle.lang ? rec.subtitle.lang : null,
      caption: rec.desc || null,
      author: { name: rec.username || rec.nickname || "unknown", url: rec.username ? `https://www.tiktok.com/@${rec.username}` : null },
      thumb: rec.cover || rec.dynamic_cover || null,
      sourceUrl: rec.username ? `https://www.tiktok.com/@${rec.username}/video/${rec.id}` : null,
      // Raw numbers — VideoCard formats at render time (schema 2).
      counts: { like: rec.digg_count ?? null, comment: rec.comment_count ?? null, views: rec.play_count ?? null },
    }).catch(() => {});
    return true;
  }
  function nativeClick(el) {
    if (!el) return false;
    const b = el.closest('button,[role="button"],a') || el;
    b.dispatchEvent(new PointerEvent("pointerdown", { bubbles: true }));
    b.dispatchEvent(new MouseEvent("mousedown", { bubbles: true }));
    b.dispatchEvent(new MouseEvent("mouseup", { bubbles: true }));
    b.click();
    return true;
  }
  function ttLike() {
    const el = document.querySelector('[data-e2e="like-icon"], [data-e2e="browse-like-icon"]');
    return nativeClick(el);
  }
  // Open the comment panel and auto-scroll it a few times so the passive fetch hook
  // bulk-captures the thread (top-level + reply pages) into the store.
  async function ttScrape() {
    const open = document.querySelector('[data-e2e="comment-icon"], [data-e2e="browse-comment-icon"]');
    if (open) nativeClick(open);
    await new Promise((r) => setTimeout(r, 900));
    const box = document.querySelector('[data-e2e="comment-list"], [class*="CommentListContainer"], [class*="DivCommentListContainer"]');
    for (let i = 0; i < 8; i++) {
      if (box) box.scrollTop = box.scrollHeight;
      else window.scrollBy(0, 700);
      // expand a couple of "view replies" toggles if present
      document.querySelectorAll('[data-e2e="view-more-1"], [class*="DivViewRepliesContainer"] span').forEach((n, idx) => { if (idx < 4) nativeClick(n); });
      await new Promise((r) => setTimeout(r, 650));
    }
    return true;
  }

  let overlayTimer = null;
  function scheduleOverlay() {
    clearTimeout(overlayTimer);
    overlayTimer = setTimeout(maintainOverlay, 250);
  }
  function buildOverlay() {
    ensureStyle();
    const wrap = document.createElement("div");
    wrap.id = "sw-tt-acts";
    const mk = (name, tip, fn) => {
      const b = document.createElement("button");
      b.className = "sw-ttbtn";
      b.type = "button";
      b.dataset.act = name;
      b.setAttribute("data-tip", tip);
      b.innerHTML = overlayIcon(name, 19);
      b.addEventListener("click", (ev) => { ev.preventDefault(); ev.stopPropagation(); fn(b); });
      return b;
    };
    wrap.appendChild(mk("save", "Salvar na Biblioteca", async (b) => {
      const rec = currentRecord(); if (!rec) return flashOverlayBtn(b, "err");
      try {
        const saved = await ttSave(rec);
        b.classList.toggle("on", saved);
        flashOverlayBtn(b, "ok");
      } catch (e) {
        flashOverlayBtn(b, "err");
        console.warn("[fbw] tt save failed", e);
      }
    }));
    wrap.appendChild(mk("dl", "Baixar vídeo", async (b) => flashOverlayBtn(b, (await ttDownload(currentRecord() || {})) ? "ok" : "err")));
    // BR/EN first, then the job — same two taps as the Facebook rail. A caption
    // track still wins over Whisper, and then the pick simply does not apply.
    const ttTxBtn = mk("tx", "Transcrever", (b) =>
      openTxLangMenu(b, async (lang) =>
        flashOverlayBtn(b, (await ttTranscribe(currentRecord() || {}, lang)) ? "ok" : "err"),
      ),
    );
    enableTxBadge(ttTxBtn);
    wrap.appendChild(ttTxBtn);
    wrap.appendChild(mk("msg", "Coletar comentários", async (b) => { await ttScrape(); flashOverlayBtn(b, "ok"); }));
    wrap.appendChild(mk("heart", "Curtir", (b) => flashOverlayBtn(b, ttLike() ? "ok" : "err")));
    return wrap;
  }
  function maintainOverlay() {
    if (disabled || document.visibilityState !== "visible") return;
    // ONE layout pass per tick: mostCenteredVideo() reads a rect per <video>, and it
    // used to run twice (once here, once inside currentAwemeId()). Resolve it here
    // and thread it down.
    const centered = mostCenteredVideo();
    const onVideo = /\/video\/\d+/.test(location.pathname) || location.pathname.startsWith("/foryou") || location.pathname === "/" || !!centered;
    let wrap = document.getElementById("sw-tt-acts");
    if (!onVideo) { if (wrap) wrap.remove(); return; }
    if (!wrap) { wrap = buildOverlay(); (document.body || document.documentElement).appendChild(wrap); }
    // Reflect saved state + enable/disable media actions for the current record.
    const rec = currentRecord(centered);
    const sb = wrap.querySelector('[data-act="save"]');
    if (sb) sb.classList.toggle("on", !!(rec && savedIds.has(rec.id))); // mirrored, no storage read
    const hasMedia = !!(rec && (rec.video || rec.download_url));
    updateTxBadges(); // this tick is also the BR/EN badge's repaint loop
    for (const act of ["dl", "tx"]) {
      const b = wrap.querySelector(`[data-act="${act}"]`);
      if (b) b.toggleAttribute("disabled", !hasMedia);
    }
  }
  const overlayInterval = setInterval(maintainOverlay, 2000);
  window.addEventListener("scroll", scheduleOverlay, { passive: true });
  document.addEventListener("visibilitychange", scheduleOverlay);
  scheduleOverlay();
}
