// FB research-feed engagement filter — isolated content script.
//
// On /search/* and /hashtag/* it keeps only the posts whose engagement clears the
// rule set in the side panel ("≥ 2000 comments OR ≥ 200 shares"), and takes the
// rest out of the page as they scroll into range.
//
// WHAT THE PAGE ALREADY DOES FOR US (probed live, 2026-08-15):
//   • the results feed is [role="feed"] and each post is a DIRECT CHILD of it;
//   • Facebook virtualizes it ITSELF: an off-screen child unmounts its content but
//     keeps its height, and children are only ever appended, never removed. So a
//     child element is a stable SLOT for one post — which is the post identity this
//     script uses. Permalinks are not: two different posts on the same page were
//     seen carrying the same /stories/… href;
//   • the mount band is roughly −0.5 to +2.3 viewports, so a post is readable about
//     two screens before it is seen — enough lead time to judge it silently;
//   • display:none on a failing child shrinks the page by exactly its height,
//     leaves window.scrollY alone, and does NOT stop the feed paginating (verified:
//     38 → 54 children with 47 of them hidden, through to "End of results").
//
// Import-free (like reels-capture.js): the pure helpers are INLINED from
// src/lib/shared/ at build time by `npm run gen:inline`. Edit the source there,
// never the generated regions below.

if (location.hostname.endsWith("facebook.com") && !window.__fbwFeedFilterInit) {
  window.__fbwFeedFilterInit = true;

  // ---- generation takeover. An extension reload re-injects into a FRESH isolated
  // world while this one keeps running (only its chrome.* dies), so the init guard
  // above cannot stop the old copy — it would keep hiding posts against the new
  // one, with its own verdict cache. Newer generation announces; older stands down
  // and puts every post it hid back. Same pattern as reels-capture.js.
  const GEN = Date.now() + ":" + Math.random();
  let disabled = false;
  window.addEventListener("message", (e) => {
    if (
      e.source === window &&
      e.data &&
      e.data.__fbwFilterTakeover &&
      e.data.__fbwFilterTakeover !== GEN &&
      !disabled
    ) {
      disabled = true;
      teardown();
      // teardown() leaves the SPA-navigation watcher running so a live script can
      // re-arm itself. A stood-down generation has nothing to re-arm: stop its
      // timer too, or every extension reload leaves another one ticking forever.
      clearInterval(navTimer);
    }
  });
  window.postMessage({ __fbwFilterTakeover: GEN }, "*");

  // pure helpers — GENERATED from src/lib/shared/ (see that dir's README; this
  // script cannot import). Run `npm run gen:inline` after editing the source.
// <<< inline:src/lib/shared/counts.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/counts.js and run `npm run gen:inline`.
// Localized count parsing/formatting. INLINED into content scripts — see
// src/lib/shared/README.md before editing (no imports allowed in this file).

// Localized abbreviated-count multipliers. FB/IG/TikTok render counts abbreviated
// with a locale word or suffix: pt-br "mil"/"mi", en "K"/"M", plus other locales'
// short forms. A missing entry here means a real count parses as null, which is
// how the comment scraper used to lose reaction counts on non-pt/en UIs.
const COUNT_UNITS = {
  k: 1e3, mil: 1e3, rb: 1e3, tis: 1e3, tys: 1e3, tusen: 1e3,
  m: 1e6, mi: 1e6, mio: 1e6, jt: 1e6, mln: 1e6, mn: 1e6,
  b: 1e9, mrd: 1e9, bi: 1e9,
};

/**
 * Parse a localized count string into a number, or null.
 *   "14 mil" -> 14000   "1,5 mil" -> 1500   "1.2M" -> 1200000   "543" -> 543
 * When a unit word/suffix is present the numeric part is a small decimal, so a
 * comma is the decimal separator (pt-br "1,5"). Without a unit the value is a
 * plain integer whose separators are thousands groups and are stripped.
 */
function parseCount(text) {
  if (text == null) return null;
  if (typeof text === "number") return Number.isFinite(text) ? text : null;
  // A trailing period is an abbreviation mark in some locales ("1,2 mil.").
  const s = String(text).trim().toLowerCase().replace(/\s+/g, "").replace(/\.$/, "");
  if (!s) return null;
  const m = s.match(/^([\d.,]+)([a-zçã]+)?$/);
  if (!m) return null;
  const rawNum = m[1];
  const unitWord = m[2] || "";
  const mult = unitWord ? COUNT_UNITS[unitWord] : 1;
  if (unitWord && mult == null) return null; // unknown suffix → not a count
  // Separator rules, in order of how much they tell us:
  //   both present   → the LAST one is the decimal, the other is grouping.
  //                    "1.234,5" is 1234.5 (pt-BR) and "1,234.5" is 1234.5 (en).
  //   one + a unit   → that one is the decimal ("76,8 mil", "1.2M").
  //   one, no unit   → grouping; strip it ("1.234" is 1234, "76.800" is 76800).
  const hasDot = rawNum.includes(".");
  const hasComma = rawNum.includes(",");
  let norm;
  if (hasDot && hasComma) {
    const decimal = rawNum.lastIndexOf(".") > rawNum.lastIndexOf(",") ? "." : ",";
    const grouping = decimal === "." ? "," : ".";
    norm = rawNum.split(grouping).join("").replace(decimal, ".");
  } else if (unitWord) {
    norm = rawNum.replace(",", ".");
  } else {
    norm = rawNum.replace(/[.,]/g, "");
  }
  const num = parseFloat(norm);
  if (!Number.isFinite(num)) return null;
  return Math.round(num * mult);
}

// Display formatting. 964490 -> "964.5K". Null renders as an em dash rather than
// "0" — an unknown count and a zero count are different facts. Counts are stored
// raw and formatted here at render time.
function fmtCount(n) {
  if (n == null) return "—";
  if (n >= 1e6) return (n / 1e6).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1e3) return (n / 1e3).toFixed(1).replace(/\.0$/, "") + "K";
  return String(n);
}
// >>> inline:end
// <<< inline:src/lib/shared/fbCounts.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fbCounts.js and run `npm run gen:inline`.
// Engagement counts (reactions / comments / shares / views) read off a Facebook
// post or reel unit. Canonical source — inlined verbatim into the import-free
// capture scripts by scripts/gen-inline.mjs, see ./README.md.
//
// Two layouts exist:
//   • feed / reel rail: a bare number next to each action control, in the order
//     [reactions, comments, shares];
//   • watch theater: a word summary ("2 · 1 comentário · 103 visualizações")
//     rendered after the Share control, with no per-control numbers.
//
// Two things this deliberately does NOT do the obvious way:
//   1. It anchors on the COMMENT control, not the Like one. "Curtir" is the only
//      label that changes with state — once the account has reacted it reads
//      "Amei" / "Remover Curtir", and a like-anchored scan then found no row and
//      returned null, so the reel was filed with no counts at all.
//   2. It collects TEXT NODES, not leaf elements. FB ships variants where the
//      number shares its span with an icon; a leaf-elements-only scan skips that
//      element and silently drops the count.
const COUNT_RE = /^\d[\d.,]*\s?(mil|k|m|mi|rb|jt|tis)?$/i;
const COUNT_LBL = {
  like: /^(like|curtir|gostei|me gusta|j'aime|mi piace|gefällt mir)$/i,
  comment: /leave a comment|comentar|coment[áa]rio|escrever|kommentar|commenter|commenta/i,
  share: /^(share|compartilhar|compartir|partager|teilen|condividi)$/i,
};

function actionControls(root) {
  return [...root.querySelectorAll('[aria-label][role="button"]')];
}
function hasLabel(root, re) {
  return actionControls(root).some((b) => re.test(b.getAttribute("aria-label") || ""));
}
// Every text node under `el`, trimmed. Text nodes have no children by
// definition, so this reaches numbers an element-leaf scan cannot see.
function textNodes(el, out = []) {
  for (const n of el.childNodes) {
    if (n.nodeType === 3) {
      const t = (n.nodeValue || "").trim();
      if (t) out.push(t);
    } else if (n.nodeType === 1) textNodes(n, out);
  }
  return out;
}

// The Share control's label is only the bare word "Compartilhar" on a reel rail.
// In the search / hashtag feed the same control reads "Send this to friends or
// post it on your profile." (pt-BR: "Envie para seus amigos…"), which the exact
// COUNT_LBL.share above deliberately does not match. This wider form is used only
// by readCountsByControl, so the reel scrapers keep their tighter matching.
const SHARE_LBL_WIDE =
  /^(share|compartilhar|compartir|partager|teilen|condividi)\b|send this to|envie para|env[íi]a esto|envoyer|invia questo|sende dies/i;

// A reaction-count tooltip ("Like: 295 people", "Amei: 3,3 mil pessoas") is also a
// [role="button"][aria-label] inside the action row. Every one of them carries a
// colon; no action control does.
const isTooltipCtrl = (b) => (b.getAttribute("aria-label") || "").indexOf(":") >= 0;

function centerOf(node) {
  const el = node.nodeType === 1 ? node : node.parentElement;
  if (!el || !el.getBoundingClientRect) return null;
  const b = el.getBoundingClientRect();
  if (!b.width && !b.height) return null; // never laid out (unmounted, or jsdom)
  return { x: b.left + b.width / 2, y: b.top + b.height / 2 };
}

/**
 * The action row's counts, each filed under the control it belongs to.
 *
 * WHY THIS EXISTS BESIDE readPostCounts: that one reads the row's bare numbers
 * POSITIONALLY, as [reactions, comments, shares]. Facebook prints NO number beside
 * a control whose count is zero, so a post with no comments renders "4 … 2" and the
 * positional read files its 2 shares as 2 comments — which silently passes a
 * "≥ 2 comments" filter. Verified live on /search/top?q=%23auralytrend
 * (2026-08-15): numbers at x≈1027 and x≈1131 against controls at like x≈1013,
 * comment x≈1065, share x≈1117.
 *
 * So each number is filed by WHERE IT IS, not by how many came before it:
 *   1. inside one of the three controls → that control (survives any layout);
 *   2. otherwise the nearest control by centre distance;
 *   3. and if nothing was ever laid out (an unmounted post, or a test DOM), a
 *      3-number row falls back to the positional reading.
 *
 * Returns the raw localized strings — parse with parseCount from ./counts.js —
 * or null when the post has no action row yet, which on a virtualized feed means
 * "not mounted", not "no engagement".
 */
function readCountsByControl(container) {
  if (!container) return null;
  const anchor = actionControls(container).find((b) =>
    COUNT_LBL.comment.test(b.getAttribute("aria-label") || ""),
  );
  if (!anchor) return null;

  // Climb to the smallest ancestor holding the whole action row, and never past
  // the post itself — on a reacted post the "Like" label is gone, and an unbounded
  // climb would walk into the neighbouring post's row.
  let row = anchor;
  for (let i = 0; i < 7 && row.parentElement && row !== container; i++) {
    row = row.parentElement;
    if (actionControls(row).filter((b) => !isTooltipCtrl(b)).length >= 2) break;
  }

  const controls = actionControls(row).filter((b) => !isTooltipCtrl(b));
  const at = controls.indexOf(anchor);
  const share = controls.find((b) => SHARE_LBL_WIDE.test(b.getAttribute("aria-label") || ""));
  // The like control is whatever action sits before Comment in the bar. Matching
  // it by label would need every reaction word in every locale ("Amei", "Remover
  // Curtir", "Change Like reaction"); its POSITION never changes.
  const like = at > 0 ? controls[0] : null;
  const slots = [
    ["like", like],
    ["comment", anchor],
    ["share", share || null],
  ].filter(([, el]) => el);

  const out = { like: null, comment: null, share: null };
  const numbers = [];
  (function walk(el) {
    for (const n of el.childNodes) {
      if (n.nodeType === 3) {
        const t = (n.nodeValue || "").trim();
        if (t && t.length <= 8 && COUNT_RE.test(t)) numbers.push(n);
      } else if (n.nodeType === 1) walk(n);
    }
  })(row);

  let placed = 0;
  for (const node of numbers) {
    let kind = null;
    for (const [k, el] of slots) if (el.contains(node)) kind = k;
    if (!kind) {
      const c = centerOf(node);
      let best = Infinity;
      if (c)
        for (const [k, el] of slots) {
          const cc = centerOf(el);
          if (!cc) continue;
          // Vertical distance is weighted: a wrapped row stacks the controls, and
          // a number one line down belongs to the control above it, not to the one
          // that happens to share its column.
          const d = Math.hypot(c.x - cc.x, (c.y - cc.y) * 3);
          if (d < best) {
            best = d;
            kind = k;
          }
        }
    }
    if (kind && out[kind] == null) {
      out[kind] = (node.nodeValue || "").trim();
      placed++;
    }
  }

  // Nothing could be placed by containment OR geometry (never laid out): fall back
  // to the positional reading, which is right whenever all three numbers are shown.
  if (!placed && numbers.length === 3) {
    const t = (n) => (n.nodeValue || "").trim();
    return { like: t(numbers[0]), comment: t(numbers[1]), share: t(numbers[2]) };
  }
  return out;
}

function readPostCounts(container) {
  if (!container) return null;
  // (a) bare numbers from the action row
  const bare = [];
  const controls = actionControls(container);
  const anchor =
    controls.find((b) => COUNT_LBL.comment.test(b.getAttribute("aria-label") || "")) ||
    controls.find((b) => COUNT_LBL.like.test(b.getAttribute("aria-label") || ""));
  if (anchor) {
    // Climb to the smallest ancestor holding the whole action row. "Holds the
    // row" = it carries the comment control plus at least one of the other two,
    // so it works whether we anchored on Comment or on Like.
    let row = anchor;
    for (let i = 0; i < 7 && row.parentElement; i++) {
      row = row.parentElement;
      if (
        hasLabel(row, COUNT_LBL.comment) &&
        (hasLabel(row, COUNT_LBL.like) || hasLabel(row, COUNT_LBL.share))
      )
        break;
    }
    for (const t of textNodes(row)) if (t.length <= 8 && COUNT_RE.test(t)) bare.push(t);
  }
  // (b) word summary after the Share control
  const text = (container.innerText || container.textContent || "").replace(/\s+/g, " ");
  const SHARE_W =
    /\b(?:share|compartilhar|compartilhamentos?|compartir|partager|condividi|teilen)\b/i;
  const af = SHARE_W.test(text) ? text.split(SHARE_W).pop() : "";
  const num = "([\\d.,]+\\s?(?:mil|k|m|mi|rb|jt)?)";
  const w = (re) => {
    const m = af.match(new RegExp(re, "i"));
    return m ? m[1].trim() : null;
  };
  const reactW = (af.trim().match(/^(\d[\d.,]*\s?(?:mil|k|m|mi)?)/i) || [])[1];
  const counts = {
    like: bare[0] || (reactW ? reactW.trim() : null),
    comment:
      w(num + "\\s+(?:comments?|coment[áa]rios?|comentarios?|commentaires?|commenti|kommentare?)\\b") ||
      bare[1] ||
      null,
    share:
      w(num + "\\s+(?:shares?|compartilhamentos?|compartidos?|partages?|condivisioni|freigaben)\\b") ||
      bare[2] ||
      null,
    views: w(num + "\\s*(?:views?|visualiz\\w*)\\b"),
  };
  return counts.like || counts.comment || counts.share || counts.views ? counts : null;
}
// >>> inline:end
// <<< inline:src/lib/shared/feedFilter.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/feedFilter.js and run `npm run gen:inline`.
// The engagement rule behind the Facebook research filter: "show me only the
// posts with at least N comments / N shares / N reactions". Pure and DOM-free, so
// the side panel that EDITS the rule and the page script that ENFORCES it agree on
// what passes — there is no second copy to drift.
//
// INLINED into content scripts — see src/lib/shared/README.md before editing (no
// imports allowed in this file).

// chrome.storage.local key. The rule is stored, not just messaged, so a page
// reload (or a second Facebook tab) keeps filtering without the panel being open.
const FB_FILTER_KEY = "sw_fb_filter";

// Order matters: it is the order the panel renders the three inputs in, and the
// order of Facebook's own action row (reactions · comments · shares).
const FILTER_METRICS = ["likes", "comments", "shares"];

function emptyRule() {
  return { on: false, mode: "or", min: { likes: null, comments: null, shares: null } };
}

// A minimum is a whole count ≥ 0, or null for "ignore this metric". The panel's
// inputs hand over strings, so "" (the user cleared the field), "1.2k" and a
// negative all have to degrade to null rather than to NaN — a NaN threshold
// compares false against everything and would silently hide the whole feed.
function normMin(v) {
  if (v == null || v === "" || typeof v === "boolean") return null;
  const n = typeof v === "number" ? v : parseInt(String(v).replace(/[^\d]/g, ""), 10);
  if (!Number.isFinite(n) || n < 0) return null;
  return Math.floor(n);
}

// Anything that arrives from storage or a message goes through here first.
function normalizeRule(raw) {
  const r = raw && typeof raw === "object" ? raw : {};
  const min = r.min && typeof r.min === "object" ? r.min : {};
  return {
    on: !!r.on,
    mode: r.mode === "and" ? "and" : "or",
    min: {
      likes: normMin(min.likes),
      comments: normMin(min.comments),
      shares: normMin(min.shares),
    },
  };
}

// The metrics the rule actually looks at (a blank field is not a "≥ 0" test).
function activeMetrics(rule) {
  const min = (rule && rule.min) || {};
  return FILTER_METRICS.filter((m) => min[m] != null);
}

/**
 * Does this post's engagement clear the rule?
 *
 * A missing count is a ZERO, not an unknown: Facebook prints no number at all
 * beside a control whose count is 0 (verified live on /search/top, 2026-08-15), so
 * `null` here means "nobody did it" and must fail a positive minimum.
 *
 * An empty rule passes everything. Filtering the entire feed away because the
 * user has not typed a threshold yet would read as a broken tool.
 */
function passesRule(counts, rule) {
  const active = activeMetrics(rule);
  if (!active.length) return true;
  const min = rule.min;
  const ok = (m) => ((counts && counts[m] != null ? counts[m] : 0) >= min[m]);
  return rule.mode === "and" ? active.every(ok) : active.some(ok);
}

/**
 * Identity of a rule's FILTERING behaviour, used by the page script to decide
 * whether a post's cached verdict is still valid.
 *
 * `on` is deliberately excluded: switching the filter off and back on must not
 * force every post in a long feed to be re-read, because the answer cannot have
 * changed. Only the thresholds and the combinator can change a verdict.
 */
function ruleKey(rule) {
  const r = normalizeRule(rule);
  return `${r.mode}:${r.min.likes}/${r.min.comments}/${r.min.shares}`;
}
// >>> inline:end

  // ---------------------------------------------------------------- surface ----
  // Only the two research surfaces. The home feed, groups and watch use the same
  // [role="feed"] container but a different action-bar layout, and filtering the
  // feed a user did not go looking through is not what this tool is for.
  function surfaceOf() {
    const p = location.pathname;
    if (p.startsWith("/search")) return "search";
    if (p.startsWith("/hashtag")) return "hashtag";
    return null;
  }
  const feedEl = () => document.querySelector('[role="feed"]');

  // ------------------------------------------------------------------ state ----
  let rule = emptyRule();
  let rkey = ruleKey(rule);
  // element → { key, pass, counts, at }. WeakMap so a slot Facebook does drop is
  // collectible, and so a feed that has grown to hundreds of posts costs nothing
  // to remember.
  const verdicts = new WeakMap();
  const hidden = new Set(); // the slots WE hid — never touch anything else's display
  // The slots the IntersectionObserver currently reports inside its margin. This is
  // what a pass walks — NOT every child of the feed. A hashtag session accumulates
  // hundreds of posts and every one of them would otherwise cost a
  // getBoundingClientRect on every scroll frame (measured: 0.4ms per 33 children,
  // so ~4ms/frame at 300 posts) to re-learn what the observer already knows.
  const near = new Set();
  // Slots owed a second read: the action bar was there but carried no numbers, so
  // the first verdict may have been built on a post caught mid-paint.
  const recheck = new Set();
  let judged = 0; // slots that have ever produced a verdict → `pending` needs no scan
  let stats = { shown: 0, hidden: 0, pending: 0, total: 0 };
  let io = null;
  let mo = null;
  let tick = null;
  let navTimer = null;
  let scheduled = false;
  let lastHref = location.href;

  // A passing post stays on screen, so its counts keep ticking up and its slot
  // could in principle be re-used. Re-read it at most this often — it is one or
  // two mounted posts at a time, ~0.05ms each.
  const REVALIDATE_MS = 2000;
  // …and a numberless first read gets this many confirmations before its zeros are
  // believed. Bounded, or a genuinely 0-engagement post would be re-read forever.
  const RECHECK_MS = 1200;
  const RECHECK_TRIES = 3;

  // -------------------------------------------------------------- judgement ----
  // null = undecidable right now (the post has not mounted); the caller leaves it
  // visible and tries again on the next wake-up.
  function judge(el, now, visible) {
    let v = verdicts.get(el);
    // A new threshold does not change what a post's counts ARE. Re-run the stored
    // numbers against the new rule instead of waiting for Facebook to mount the
    // post again — otherwise raising the bar mid-session brings the whole feed
    // back unfiltered until the user has scrolled past every post a second time.
    if (v && v.key !== rkey) {
      v = { ...v, key: rkey, pass: passesRule(v.counts, rule) };
      verdicts.set(el, v);
    }
    if (v) {
      // Counts climb while a post is on screen, so a PASS is worth re-reading.
      const revalidate = visible && v.pass && now - v.at > REVALIDATE_MS;
      // A FAIL never got that treatment, and one built on a numberless read is the
      // one verdict that can be wrong for the rest of the page's life: the post is
      // hidden, so nothing ever looks at it again. Facebook renders the action bar
      // and its numbers together in every sample taken, but "together" is not
      // "atomically", and the cost of being wrong is a post silently deleted from
      // the user's search. Confirm it instead.
      const confirm = v.blank && v.tries < RECHECK_TRIES && now - v.at > RECHECK_MS;
      if (!revalidate && !confirm) return v.pass;
    }
    const raw = readCountsByControl(el);
    if (!raw) return v ? v.pass : null; // no action row → not mounted yet
    const counts = {
      likes: parseCount(raw.like) || 0,
      comments: parseCount(raw.comment) || 0,
      shares: parseCount(raw.share) || 0,
    };
    const blank = raw.like == null && raw.comment == null && raw.share == null;
    const tries = blank ? (v && v.tries ? v.tries : 0) + 1 : 0;
    const pass = passesRule(counts, rule);
    if (!v) judged++;
    verdicts.set(el, { key: rkey, pass, counts, at: now, blank, tries });
    if (blank && tries < RECHECK_TRIES) recheck.add(el);
    else recheck.delete(el);
    return pass;
  }

  // ------------------------------------------------------------------ paint ----
  function hide(el, rect) {
    if (hidden.has(el)) return;
    hidden.add(el);
    el.style.display = "none";
    // Hiding a post the user has already scrolled PAST pulls everything below it
    // up by its height, which yanks the page under their eyes. Give the scroll
    // position the same distance back. (A post still below the fold needs no
    // compensation — nothing the user is reading moves.)
    if (rect && rect.bottom <= 0 && rect.height) window.scrollBy(0, -rect.height);
  }
  function unhide(el) {
    if (!hidden.has(el)) return;
    hidden.delete(el);
    el.style.display = "";
    // Mirror of the hide compensation: a post reappearing ABOVE the viewport pushes
    // everything the user is reading down by its height. Relaxing the rule (or
    // switching the filter off) puts many of them back at once, and without this
    // the page lurches by a screenful per restored post.
    const r = el.getBoundingClientRect();
    if (r.bottom <= 0 && r.height) window.scrollBy(0, r.height);
  }
  function unhideAll() {
    for (const el of [...hidden]) unhide(el);
  }

  // Read every rect and every count BEFORE the first display write: one layout per
  // pass instead of one per post.
  function commit(plan) {
    for (const [el, pass, rect] of plan) {
      if (pass) unhide(el);
      else hide(el, rect);
    }
  }
  function countStats(feed) {
    const total = feed.children.length;
    stats = {
      shown: total - hidden.size,
      hidden: hidden.size,
      pending: Math.max(0, total - judged),
      total,
    };
    paintChip();
  }

  /**
   * One pass, over the slots near the viewport (plus the handful owed a second
   * read) — never over the whole feed. Steady-state cost measured on the live
   * page: 0.2–0.3ms, and now flat in the number of posts already scrolled past.
   */
  function apply() {
    if (disabled) return;
    const feed = feedEl();
    if (!feed) {
      stats = { shown: 0, hidden: 0, pending: 0, total: 0 };
      paintChip();
      return;
    }
    if (!surfaceOf() || !rule.on) {
      unhideAll();
      countStats(feed);
      return;
    }

    const now = Date.now();
    const vh = window.innerHeight || 800;
    const plan = [];
    const cands = new Set(near);
    for (const el of recheck) cands.add(el);
    for (const el of cands) {
      // A slot Facebook dropped (or that belongs to a feed we have navigated away
      // from) must not keep us holding a reference to it.
      if (!el.isConnected || el.parentElement !== feed) {
        near.delete(el);
        recheck.delete(el);
        hidden.delete(el);
        continue;
      }
      const rect = hidden.has(el) ? null : el.getBoundingClientRect();
      const visible = !!rect && rect.bottom > 0 && rect.top < vh;
      const pass = judge(el, now, visible);
      if (pass === null) continue; // undecidable → stays visible, like an unfiltered feed
      plan.push([el, pass, rect]);
    }
    commit(plan);
    countStats(feed);
  }

  /**
   * Re-apply the current rule to EVERY slot, including the ones far off screen.
   *
   * Only worth doing when the rule itself changed: a post's counts are already
   * cached, so judge() re-decides it without touching the DOM, and the whole feed
   * re-filters at once instead of post by post as the user scrolls back through it.
   */
  function sweepAll() {
    if (disabled) return;
    const feed = feedEl();
    if (!feed || !surfaceOf() || !rule.on) return;
    const now = Date.now();
    const plan = [];
    for (const el of feed.children) {
      if (!verdicts.get(el)) continue; // never read → nothing cached to re-decide
      const pass = judge(el, now, false);
      if (pass === null) continue;
      plan.push([el, pass, hidden.has(el) ? null : el.getBoundingClientRect()]);
    }
    commit(plan);
    countStats(feed);
  }

  // Coalesce every wake-up (intersection, mutation, tick) into one pass per frame.
  function schedule() {
    if (scheduled || disabled) return;
    scheduled = true;
    requestAnimationFrame(() => {
      scheduled = false;
      apply();
    });
  }

  // ------------------------------------------------------------- wake-ups -----
  // An IntersectionObserver with a 200% margin fires while a post is still two
  // screens away — which is inside Facebook's own mount band, so the post is
  // readable and can be dropped before it is ever seen. A scroll listener would
  // fire hundreds of times for the same information.
  function watch(el) {
    if (io) io.observe(el);
  }
  function setup() {
    if (io || disabled) return;
    const feed = feedEl();
    if (!feed) return;
    // The observer is also the pass's WORK LIST: what it reports as intersecting is
    // exactly what is worth reading, so a pass never has to measure the posts the
    // user scrolled past an hour ago.
    io = new IntersectionObserver((entries) => {
      for (const e of entries) {
        if (e.isIntersecting) near.add(e.target);
        else near.delete(e.target);
      }
      schedule();
    }, { rootMargin: "200% 0px 200% 0px" });
    for (const el of feed.children) watch(el);
    // childList only, no subtree: the feed appends a post as one child, and a
    // subtree observer on a feed with playing video fires constantly for nothing.
    mo = new MutationObserver((records) => {
      for (const r of records) for (const n of r.addedNodes) if (n.nodeType === 1) watch(n);
      schedule();
    });
    mo.observe(feed, { childList: true });
    // The safety net: a post can MOUNT without its intersection changing (it was
    // already in range, empty, and Facebook hydrated it a moment later). Only runs
    // a pass while something is actually undecided.
    tick = setInterval(() => {
      if (stats.pending) schedule();
    }, 500);
    schedule();
  }
  function teardown() {
    io?.disconnect();
    io = null;
    mo?.disconnect();
    mo = null;
    clearInterval(tick);
    tick = null;
    unhideAll();
    // Both sets hold STRONG references to feed children (unlike `verdicts`), so a
    // feed we are done with has to release them or every post of every search this
    // tab ever ran stays reachable for the life of the page.
    near.clear();
    recheck.clear();
    judged = 0;
    removeChip();
  }

  // Facebook is a single-page app: leaving the search results for a permalink must
  // put every hidden post back and stop the observers. There is no event for it —
  // the URL is the only signal — and 700ms is well below human navigation speed.
  navTimer = setInterval(() => {
    if (disabled) return;
    const href = location.href;
    const feedGone = !!io && !feedEl();
    if (href === lastHref && !feedGone) return;
    lastHref = href;
    teardown();
    if (surfaceOf()) setup();
  }, 700);

  // ------------------------------------------------------------------- chip ----
  // A small counter on the page itself, so the filter can be switched off without
  // going back to the panel — and so a feed that has gone quiet never looks broken.
  //
  // Parented on <html>, OUTSIDE Facebook's React root: anything appended inside the
  // feed is destroyed the next time Facebook re-renders that subtree (the same
  // reason the transcription rails live there).
  let chip = null;
  function removeChip() {
    chip?.remove();
    chip = null;
  }
  function paintChip() {
    if (disabled || !surfaceOf() || !feedEl()) return removeChip();
    // The chip stays while a rule EXISTS, on or off. Switching the filter off used
    // to remove the chip that switches it back on — which left the page with no way
    // to re-arm it. A page with no rule set gets no chip at all.
    if (!rule.on && !activeMetrics(rule).length) return removeChip();
    if (!chip) {
      chip = document.createElement("div");
      chip.id = "sw-fbfilter-chip";
      chip.style.cssText = [
        "position:fixed",
        "left:16px",
        "bottom:16px",
        "z-index:2147483000",
        "display:flex",
        "align-items:center",
        "gap:8px",
        "padding:8px 12px",
        "border-radius:999px",
        "font:600 12px/1.2 system-ui,-apple-system,Segoe UI,sans-serif",
        "color:#fff",
        "background:linear-gradient(135deg,#3c7cfc 0%,#59c0e8 100%)",
        "box-shadow:0 6px 20px rgba(0,0,0,.25)",
        "cursor:pointer",
        "user-select:none",
      ].join(";");
      chip.title = "socialMate — clique para ligar/desligar o filtro";
      chip.addEventListener("click", () => {
        setRule({ ...rule, on: !rule.on }, true);
      });
      document.documentElement.appendChild(chip);
    }
    chip.textContent = rule.on
      ? `${stats.shown} exibidos · ${stats.hidden} ocultos`
      : `filtro desligado · ${stats.total} posts`;
    chip.style.opacity = rule.on ? "1" : "0.6";
  }

  // ------------------------------------------------------------------ rule -----
  // Persisted, not just messaged: a reload (or a second Facebook tab) keeps
  // filtering with the panel closed. storage is also the sync channel between the
  // panel, this tab and any other Facebook tab.
  function setRule(next, persist) {
    const prev = rkey;
    rule = normalizeRule(next);
    rkey = ruleKey(rule);
    // A changed threshold does NOT unhide everything first: the sweep below
    // re-judges every post from its cached counts and unhides only the ones that
    // now pass. Restoring the whole feed and re-hiding it would be two page-length
    // lurches for a change that usually moves a handful of posts.
    if (!rule.on) unhideAll();
    if (persist) {
      try {
        chrome.storage?.local?.set({ [FB_FILTER_KEY]: rule });
      } catch {
        /* the filter still applies in this tab; only the sync is lost */
      }
    }
    if (surfaceOf()) setup();
    // The ordinary pass only looks at what is near the viewport, so a new rule has
    // to be carried to the rest of the feed explicitly — once, here.
    if (rkey !== prev || rule.on) sweepAll();
    schedule();
  }

  try {
    chrome.storage?.local?.get(FB_FILTER_KEY, (r) => {
      if (disabled) return;
      setRule(r?.[FB_FILTER_KEY], false);
    });
    chrome.storage?.onChanged?.addListener((c, area) => {
      if (disabled || area !== "local" || !c[FB_FILTER_KEY]) return;
      setRule(c[FB_FILTER_KEY].newValue, false);
    });
  } catch {
    /* no storage in this context — the panel can still drive it by message */
  }

  if (surfaceOf()) setup();

  // ----------------------------------------------------------------- panel -----
  const state = () => ({
    ok: true,
    surface: surfaceOf(),
    hasFeed: !!feedEl(),
    rule,
    stats,
  });

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (disabled) return;
    if (msg?.type === "FBW_FBFILTER_STATE") {
      sendResponse(state());
      return; // sync
    }
    if (msg?.type === "FBW_FBFILTER_SET") {
      setRule(msg.rule, true);
      apply();
      sendResponse(state());
      return; // sync
    }
  });
}
