// Facebook profile reels: captured records, shared query and in-page research actions.
if (location.hostname.endsWith("facebook.com") && !window.__fbwFbReelsInit) {
  window.__fbwFbReelsInit = true;

  // ---- generation takeover. An extension reload re-injects into a FRESH isolated
  // world while this one keeps running (only its chrome.* dies), so the init guard
  // above cannot stop the old copy — its in-flight harvest would keep scrolling the
  // grid against the new one. Newer generation announces; older stands down. Same
  // pattern as comments-scrape.js / photos-scrape.js.
  const GEN = Date.now() + ":" + Math.random();
  let disabled = false;
  let harvesting = false;   // one scroll loop at a time
  let cancelFlag = false;   // FBW_FB_REELS_STOP / takeover
  window.addEventListener("message", (e) => {
    if (
      e.source === window &&
      e.data &&
      e.data.__fbwReelsTakeover &&
      e.data.__fbwReelsTakeover !== GEN &&
      !disabled
    ) {
      disabled = true;
      cancelFlag = true;
    }
  });
  window.postMessage({ __fbwReelsTakeover: GEN }, "*");

  // pure helpers — GENERATED from src/lib/shared/ (see that dir's README; this
  // script cannot import). Run `npm run gen:inline` after editing the source.
// <<< inline:src/lib/shared/counts.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/counts.js and run `npm run gen:inline`.
// Localized count parsing/formatting. INLINED into content scripts — see
// src/lib/shared/README.md before editing (no imports allowed in this file).

// Localized abbreviated-count multipliers. FB/IG/TikTok render counts abbreviated
// with a locale word or suffix: pt-br "mil"/"mi", en "K"/"M", plus other locales'
// short forms. A missing entry here means a real count parses as null, which is
// how the comment scraper used to lose reaction counts on non-pt/en UIs.
const COUNT_UNITS = {
  k: 1e3, mil: 1e3, rb: 1e3, tis: 1e3, tys: 1e3, tusen: 1e3,
  m: 1e6, mi: 1e6, mio: 1e6, jt: 1e6, mln: 1e6, mn: 1e6,
  b: 1e9, mrd: 1e9, bi: 1e9,
};

/**
 * Parse a localized count string into a number, or null.
 *   "14 mil" -> 14000   "1,5 mil" -> 1500   "1.2M" -> 1200000   "543" -> 543
 * When a unit word/suffix is present the numeric part is a small decimal, so a
 * comma is the decimal separator (pt-br "1,5"). Without a unit the value is a
 * plain integer whose separators are thousands groups and are stripped.
 */
function parseCount(text) {
  if (text == null) return null;
  if (typeof text === "number") return Number.isFinite(text) ? text : null;
  // A trailing period is an abbreviation mark in some locales ("1,2 mil.").
  const s = String(text).trim().toLowerCase().replace(/\s+/g, "").replace(/\.$/, "");
  if (!s) return null;
  const m = s.match(/^([\d.,]+)([a-zçã]+)?$/);
  if (!m) return null;
  const rawNum = m[1];
  const unitWord = m[2] || "";
  const mult = unitWord ? COUNT_UNITS[unitWord] : 1;
  if (unitWord && mult == null) return null; // unknown suffix → not a count
  // Separator rules, in order of how much they tell us:
  //   both present   → the LAST one is the decimal, the other is grouping.
  //                    "1.234,5" is 1234.5 (pt-BR) and "1,234.5" is 1234.5 (en).
  //   one + a unit   → that one is the decimal ("76,8 mil", "1.2M").
  //   one, no unit   → grouping; strip it ("1.234" is 1234, "76.800" is 76800).
  const hasDot = rawNum.includes(".");
  const hasComma = rawNum.includes(",");
  let norm;
  if (hasDot && hasComma) {
    const decimal = rawNum.lastIndexOf(".") > rawNum.lastIndexOf(",") ? "." : ",";
    const grouping = decimal === "." ? "," : ".";
    norm = rawNum.split(grouping).join("").replace(decimal, ".");
  } else if (unitWord) {
    norm = rawNum.replace(",", ".");
  } else {
    norm = rawNum.replace(/[.,]/g, "");
  }
  const num = parseFloat(norm);
  if (!Number.isFinite(num)) return null;
  return Math.round(num * mult);
}

// Display formatting. 964490 -> "964.5K". Null renders as an em dash rather than
// "0" — an unknown count and a zero count are different facts. Counts are stored
// raw and formatted here at render time.
function fmtCount(n) {
  if (n == null) return "—";
  if (n >= 1e6) return (n / 1e6).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1e3) return (n / 1e3).toFixed(1).replace(/\.0$/, "") + "K";
  return String(n);
}
// >>> inline:end
// <<< inline:src/lib/shared/fbReelThumb.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fbReelThumb.js and run `npm run gen:inline`.
// Facebook reel COVER images: which surfaces carry the grid, and how to ask the
// CDN for the native frame instead of the cropped one it paints.
// INLINED into content scripts — see src/lib/shared/README.md before editing
// (no imports allowed in this file).
//
// A reel tile's <img> src looks like:
//   .../t15.5256-10/791436480_..._n.jpg?stp=dst-jpg_tt6&cstp=mx1080x1920&ctp=s960x960&...&oh=...&oe=...
// which serves 540x960 even though the reel itself is 1080x1920. Probed live on
// 2026-09-06 (facebook.com/profile.php?id=61592820645925&sk=owner_reels):
//
//   ctp removed / ctp=s1080x1920 -> 1080x1920, HTTP 200
//   ctp=s2000x2000               -> 403 (past the cstp cap)
//   cstp=mx2000x2000             -> 403
//   stp removed                  -> 403
//
// So `stp` and `cstp` are covered by the `oh` HMAC and `cstp=mx1080x1920` is the
// signed ceiling, while `ctp` is a free client-side crop hint. Dropping it is
// enough — and it is the whole trick. (This does NOT generalise to profile
// photos on t39: that CDN signs the crop, which is why the photos harvester goes
// through the lightbox instead.)

/**
 * The same cover image at its native resolution (1080x1920 for a reel).
 * Byte-exact on every other parameter: the query is edited as a string rather
 * than round-tripped through URLSearchParams, because re-encoding a signed
 * parameter would invalidate `oh` and earn a 403.
 * Returns the input untouched when there is nothing to strip.
 */
function fullResThumb(url) {
  if (typeof url !== "string" || !url) return url;
  const q = url.indexOf("?");
  if (q < 0) return url;
  const kept = url
    .slice(q + 1)
    .split("&")
    .filter((p) => !/^ctp=/.test(p));
  return kept.length ? url.slice(0, q) + "?" + kept.join("&") : url.slice(0, q);
}

/**
 * Is this URL a profile's REELS GRID (the tile wall), rather than the
 * /reel/<id> player or any other tab?
 *
 * Facebook serves the same grid under three shapes, and they are not
 * interchangeable — `sk=owner_reels` is the one a profile.php URL gets, and it
 * used to fall through every check we had because its path is `/profile.php`:
 *
 *   /profile.php?id=<id>&sk=owner_reels     numeric profile
 *   /profile.php?id=<id>&sk=reels_tab       older alias, still linked in-page
 *   /<vanity>/reels/  |  /<vanity>/reels_tab   vanity profile / page
 */
function isReelsGridUrl(href) {
  let path, search;
  try {
    const u = new URL(String(href || ""), "https://www.facebook.com");
    path = u.pathname;
    search = u.search;
  } catch {
    return false;
  }
  if (/\/reel\/\d/.test(path)) return false; // the player owns its own rail
  if (/[?&]sk=(reels_tab|owner_reels)(&|$)/.test(search)) return true;
  return /\/reels(_tab)?\/?$/.test(path);
}

/** The reel id inside a grid tile's href, or null. */
function reelIdFromHref(href) {
  const m = String(href || "").match(/\/reel\/(\d+)/);
  return m ? m[1] : null;
}
// >>> inline:end

  // <<< inline:src/lib/shared/fbVideoMedia.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fbVideoMedia.js and run `npm run gen:inline`.
// Facebook search hydration and streamed GraphQL → bounded, per-video records.
// Inlined into MAIN capture and the isolated transcription script.
function fbSearchVideosSurface(path) {
  return /^\/search\/(top|posts|videos)\/?$/.test(path);
}

function fbMediaUrl(value) {
  if (typeof value !== "string" || value.length > 16000) return null;
  try {
    const u = new URL(value);
    return u.protocol === "https:" && u.hostname.endsWith(".fbcdn.net") ? value : null;
  } catch { return null; }
}

function fbCoverKey(url) {
  const safe = fbMediaUrl(url);
  // CDN hosts and crop/signature parameters vary; the asset path does not.
  return safe ? new URL(safe).pathname : null;
}

function mergeFbVideo(prev, next) {
  return {
    id: next.id,
    durationS: next.durationS || prev?.durationS || null,
    permalink: next.permalink || prev?.permalink || null,
    audio: next.audio || prev?.audio || null,
    progressive: next.progressive || prev?.progressive || null,
    thumbs: [...new Set([...(prev?.thumbs || []), ...(next.thumbs || [])])].slice(-12),
    captions: [...new Map([...(prev?.captions || []), ...(next.captions || [])].map(c => [c.lang, c])).values()].slice(-30),
  };
}

function collectFbVideos(root) {
  const records = new Map();
  const seen = new WeakSet();
  let budget = 180000;
  function walk(o, depth) {
    if (!o || typeof o !== "object" || depth > 60 || budget-- <= 0 || seen.has(o)) return;
    seen.add(o);
    if (o.__typename === "Video" && /^\d{6,}$/.test(o.id || "")) {
      const result = o.videoDeliveryResponseFragment?.videoDeliveryResponseResult;
      const legacy = o.videoDeliveryLegacyFields;
      const thumbs = [o.first_frame_thumbnail, o.preferred_thumbnail?.image?.uri,
        o.thumbnailImage?.uri, o.image?.uri, o.imageLargeAspect?.uri,
        o.imageFlexible?.uri, o.imageServerSelected?.uri].map(fbMediaUrl).filter(Boolean);
      let audio = null;
      let progressive = null;
      for (const row of result?.progressive_urls || []) {
        const url = fbMediaUrl(row.progressive_url);
        if (url && (!progressive || /hd/i.test(row.metadata?.quality || ""))) progressive = url;
      }
      for (const row of result?.dash_manifests || []) {
        if (typeof row.manifest_xml !== "string") continue;
        try {
          const xml = new DOMParser().parseFromString(row.manifest_xml, "application/xml");
          for (const rep of xml.querySelectorAll("Representation")) {
            const mime = rep.getAttribute("mimeType") || rep.parentElement?.getAttribute("mimeType");
            if (mime?.startsWith("audio/")) audio ||= fbMediaUrl(rep.querySelector("BaseURL")?.textContent?.trim());
          }
        } catch { /* Keep progressive/fallback when a manifest is malformed. */ }
      }
      // Older delivery payloads still occur on other Facebook surfaces.
      if (legacy) {
        progressive ||= fbMediaUrl(legacy.browser_native_hd_url) || fbMediaUrl(legacy.browser_native_sd_url);
      }
      const captions = (o.video_available_captions_locales || []).flatMap(c => {
        const url = fbMediaUrl(c.captions_url);
        return url && typeof c.locale === "string" ? [{ url, lang: c.locale.slice(0, 20) }] : [];
      });
      let permalink = null;
      try {
        const u = new URL(o.permalink_url);
        if (u.protocol === "https:" && /(^|\.)facebook\.com$/.test(u.hostname) &&
          (u.pathname.includes(`/reel/${o.id}`) || u.pathname.includes(`/videos/${o.id}`) || u.searchParams.get("v") === o.id))
          permalink = u.origin + u.pathname + (u.searchParams.get("v") ? `?v=${o.id}` : "");
      } catch {}
      const durationS = Number.isFinite(o.playable_duration_in_ms) && o.playable_duration_in_ms > 0
        ? o.playable_duration_in_ms / 1000 : null;
      if (audio || progressive || thumbs.length || durationS || captions.length) {
        const row = { id: o.id, durationS, permalink, audio, progressive, thumbs, captions };
        records.set(o.id, mergeFbVideo(records.get(o.id), row));
      }
    }
    for (const v of Object.values(o)) walk(v, depth + 1);
  }
  walk(root, 0);
  return [...records.values()];
}

function parseFbVideoResponse(text) {
  const records = new Map();
  for (const line of String(text).split("\n")) {
    try {
      const data = JSON.parse(line.replace(/^for\s*\(;;\);\s*/, ""));
      for (const row of collectFbVideos(data)) records.set(row.id, mergeFbVideo(records.get(row.id), row));
    } catch { /* A broken deferred part must not discard the other parts. */ }
  }
  return [...records.values()];
}

function matchFbVideo(records, hint = {}) {
  const rows = [...records];
  const covers = new Set((hint.thumbs || []).map(fbCoverKey).filter(Boolean));
  if (hint.id) {
    const record = rows.find(r => r.id === hint.id);
    // A caption may link to a different reel. A conflicting cover vetoes that
    // link instead of silently using the linked video's audio for this post.
    return record && (!covers.size || record.thumbs.some(t => covers.has(fbCoverKey(t)))) ? record : null;
  }
  if (!covers.size) return null; // duration/recency alone is never an identity
  const matches = rows.filter(r => r.thumbs.some(t => covers.has(fbCoverKey(t))) &&
    !(r.durationS && Number.isFinite(hint.durationS) && Math.abs(r.durationS - hint.durationS) > 1.5));
  return matches.length === 1 ? matches[0] : null;
}

function fbCaptionFor(record, language) {
  // Auto is resolved by Whisper from the post text. Do not silently substitute
  // a translated or unknown-language caption when the user chose Auto/BR/EN.
  const lang = language === "br" || language === "pt" ? "pt" : language === "en" ? "en" : null;
  return lang ? record?.captions?.find(c => c.lang.split(/[-_]/)[0].toLowerCase() === lang) || null : null;
}
// >>> inline:end
  // <<< inline:src/lib/shared/fbReelsData.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fbReelsData.js and run `npm run gen:inline`.
// Compact Facebook reel records from hydration and streamed GraphQL. No requests.

function fbReelsSurface(href) {
  try {
    const u = new URL(href, "https://www.facebook.com");
    if (!/(^|\.)facebook\.com$/.test(u.hostname)) return null;
    const reel = u.pathname.match(/^\/reel\/(\d+)/);
    if (reel) return `reel:${reel[1]}`;
    if (u.pathname === '/profile.php' && /^(reels_tab|owner_reels)$/.test(u.searchParams.get('sk')) && /^\d+$/.test(u.searchParams.get('id')))
      return `profile:${u.searchParams.get('id')}`;
    const profile = u.pathname.match(/^\/([^/]+)\/(?:reels|reels_tab)\/?$/);
    return profile ? `profile:${profile[1].toLowerCase()}` : null;
  } catch { return null; }
}

function mergeFbReel(prev, next) {
  const out = { ...prev };
  for (const [k, v] of Object.entries(next || {})) {
    if (v != null && v !== '' && (!Array.isArray(v) || v.length)) out[k] = v;
    else if (!(k in out)) out[k] = v;
  }
  return out;
}

function fbReelUrlId(url) {
  try {
    const u = new URL(url, 'https://www.facebook.com');
    return /(^|\.)facebook\.com$/.test(u.hostname) ? u.pathname.match(/^\/reel\/(\d+)/)?.[1] || null : null;
  } catch { return null; }
}

function parseFbReels(input, activeId = null) {
  const parts = typeof input === 'string' ? input.split('\n').flatMap(line => {
    try { return [JSON.parse(line.replace(/^for\s*\(;;\);\s*/, ''))]; } catch { return []; }
  }) : Array.isArray(input) ? input : [input];
  const records = new Map(), videos = new Map(), edgeIds = new Map();
  const empty = id => ({ id, views: null, likes: null, comments: null, shares: null,
    taken_at: null, created_at: null, duration: null, caption: null, authorName: null,
    authorId: null, authorUrl: null, thumb: null, progressive: null, audio: null, captions: [],
    sourceUrl: `https://www.facebook.com/reel/${id}`, media_type: 'video' });
  function put(id, row) {
    if (!/^\d{6,}$/.test(id || '')) return;
    records.set(id, mergeFbReel(records.get(id) || empty(id), { ...row, id }));
  }
  function stats(o) {
    return { likes: parseCount(o.fb_reel_react_button?.story?.feedback?.likers?.count),
      comments: parseCount(o.feedback?.total_comment_count), shares: parseCount(o.feedback?.share_count_reduced) };
  }
  let budget = 220000;
  function walk(o, depth = 0) {
    if (!o || typeof o !== 'object' || depth > 60 || --budget < 0) return;
    if (o.aggregated_fb_shorts?.edges) {
      o.aggregated_fb_shorts.edges.forEach((e, i) => {
        const id = e.profile_reel_node?.node?.attachments?.find(a => a.media?.__typename === 'Video')?.media?.id;
        if (id) edgeIds.set(i, id);
      });
    }
    const media = o.attachments?.find?.(a => a.media?.__typename === 'Video')?.media;
    if (media?.id && (o.__typename === 'Story' || o.actors || o.creation_time)) {
      const actor = o.actors?.[0];
      put(media.id, { taken_at: Number.isFinite(o.creation_time) ? o.creation_time : null,
        caption: o.message?.text || null, authorName: actor?.name || null,
        authorId: actor?.id || null, authorUrl: actor?.id ? `https://www.facebook.com/profile.php?id=${actor.id}` : null });
    }
    const id = fbReelUrlId(o.url);
    if (id && (o.feedback || o.fb_reel_react_button)) put(id, stats(o));
    if (o.__typename === 'Video' && /^\d{6,}$/.test(o.id || '')) {
      const delivery = collectFbVideos(o).find(r => r.id === o.id);
      videos.set(o.id, mergeFbReel(videos.get(o.id), {
        id: o.id, views: parseCount(o.play_count_reduced ?? o.play_count),
        created_at: Number.isFinite(o.created_time) ? o.created_time : null,
        duration: delivery?.durationS || null, thumb: delivery?.thumbs?.[0] || null,
        progressive: delivery?.progressive || null, audio: delivery?.audio || null, captions: delivery?.captions || [],
        authorName: o.owner?.name || null, authorId: o.owner?.id || null,
        authorUrl: o.owner?.id ? `https://www.facebook.com/profile.php?id=${o.owner.id}` : null,
      }));
    }
    for (const v of Object.values(o)) if (typeof v === 'object') walk(v, depth + 1);
  }
  // Base connections must be indexed before any out-of-order deferred part.
  for (const p of parts) if (!p?.path) walk(p);
  for (const p of parts) {
    if (!p?.path) continue;
    const at = p.path.indexOf('edges');
    const id = at >= 0 ? edgeIds.get(p.path[at + 1]) : null;
    const urlId = fbReelUrlId(p.data?.url);
    if (id && urlId && id !== urlId) continue;
    if (id) put(id, stats(p.data || {}));
    walk(p.data);
  }
  if (activeId && videos.has(activeId)) put(activeId, {});
  for (const [id, row] of records) {
    const merged = mergeFbReel(videos.get(id), row);
    // Null placeholders in a partial story must not erase the video delivery.
    records.set(id, merged);
  }
  return [...records.values()];
}
// >>> inline:end
  // <<< inline:src/lib/shared/savedEntry.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/savedEntry.js and run `npm run gen:inline`.
// The ONE shape of a saved-Library record, and the permalink rules behind it.
// INLINED into content scripts — see src/lib/shared/README.md before editing
// (no imports allowed in this file).
//
// This exists because `fbw_saved` used to be written from ten places (six panel
// tools, three page overlays, the transcription rail) with five different shapes:
//
//   * counts were pre-formatted strings, sometimes via an UNGUARDED fmtCount(null)
//     (so whatever that returned got persisted instead of null), and Pinterest
//     stored the literal string "—" for views where everything else stored null;
//   * `sourceUrl` was present in some and absent in others, and VideoCard falls
//     back to `facebook.com/reel/<id>` when it's missing — a dead link for a
//     TikTok or Pinterest item;
//   * TikTok stored a signed, expiring CDN URL as `thumb`.
//
// Counts are stored as RAW NUMBERS (or null) — never formatted. Formatting is a
// render-time concern, and storing numbers keeps the Library sortable. VideoCard
// tolerates strings for records written before schema 2.

const SAVED_SCHEMA = 2;

// Absolute permalink back to the item, per platform. Centralized because a
// missing sourceUrl silently degrades into a wrong Facebook link.
function savedSourceUrl(platform, { code, id, username } = {}) {
  const key = code || id;
  switch (platform) {
    case "instagram":
      return key ? `https://www.instagram.com/p/${key}/` : null;
    case "tiktok":
      return username && id ? `https://www.tiktok.com/@${username}/video/${id}` : null;
    case "facebook":
      return key ? `https://www.facebook.com/reel/${key}` : null;
    case "pinterest":
      return key ? `https://www.pinterest.com/pin/${key}/` : null;
    default:
      return null;
  }
}

// Profile URL. FB/IG are stored relative (VideoCard prepends the origin);
// TikTok/Pinterest are absolute, and prepending an origin to those would nest one
// URL inside another and produce a dead link.
function savedAuthorUrl(platform, username) {
  if (!username) return null;
  switch (platform) {
    case "instagram":
      return `/${username}/`;
    case "tiktok":
      return `https://www.tiktok.com/@${username}`;
    case "pinterest":
      return `https://www.pinterest.com/${username}/`;
    case "facebook":
      return null; // FB reels grids expose no reliable author URL
    default:
      return null;
  }
}

function num(v) {
  return typeof v === "number" && Number.isFinite(v) ? v : null;
}

/**
 * Build a Library record. `id` and `platform` are required; everything else
 * degrades to null rather than to a wrong value.
 *
 * counts: { like, comment, view, share, save } — raw numbers or null.
 * Pass `sourceUrl` to override the derived permalink (Pinterest carries its own).
 */
function buildSavedEntry({
  id,
  platform,
  thumb = null,
  caption = null,
  authorName = null,
  username = null,
  authorUrl,
  counts = {},
  code = null,
  pk = null,
  mediaType = null,
  sourceUrl,
  now = Date.now(),
} = {}) {
  if (!id || !platform) return null;
  return {
    schema: SAVED_SCHEMA,
    videoId: String(id),
    platform,
    thumb: thumb || null,
    caption: caption || null,
    author: {
      name: authorName || username || "desconhecido",
      url: authorUrl !== undefined ? authorUrl : savedAuthorUrl(platform, username),
    },
    // `views` keeps its legacy key so existing VideoCard markup is unchanged.
    counts: {
      like: num(counts.like),
      comment: num(counts.comment),
      views: num(counts.view ?? counts.views),
      share: num(counts.share),
      save: num(counts.save),
    },
    code: code || null,
    pk: pk || null,
    media_type: mediaType || null,
    sourceUrl:
      sourceUrl !== undefined
        ? sourceUrl
        : savedSourceUrl(platform, { code, id, username }),
    updatedAt: now,
  };
}
// >>> inline:end
  // <<< inline:src/lib/shared/txLang.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/txLang.js and run `npm run gen:inline`.
// The BR/EN transcription-language control that lives ON the page: the persisted
// choice, the little badge on a Transcribe button, and the two-item menu that opens
// when you press one. INLINED into content scripts — see src/lib/shared/README.md
// before editing (no imports allowed in this file).
//
// Facebook grew this first and Instagram/TikTok only got the storage half of it:
// they read `fbw_transcript_language` but had no way to SET it, so on Instagram the
// language was whatever the Facebook rail had last been left on. The three scripts
// also carried three hand-copied `normTxLang`/`getTxLang` pairs — the same drift
// this directory exists to stop.
//
// Deliberately NOT here: which button gets a badge, and when the badge is
// repainted. Each overlay has its own button class and its own render loop, so a
// platform opts a button in with enableTxBadge() and calls updateTxBadges() from
// whatever loop it already runs.

const TX_LANG_KEY = "fbw_transcript_language";
// English since 0.97.1. Only the fallback: a stored pick (BR or EN) still wins.
// lib/transcriptionLanguage.js re-exports it, so this is the one place it lives.
const TX_LANG_DEFAULT = "en";
// "auto" is resolved by the background from the post's caption (lib/
// captionLanguage.js) — Whisper itself only ever receives en or pt.
const TX_LANG_OPTIONS = [
  { value: "br", label: "Português", short: "BR" },
  { value: "en", label: "English", short: "EN" },
  { value: "auto", label: "Automático", short: "AUTO" },
];

function normTxLang(value) {
  const lang = String(value || "").trim().toLowerCase();
  if (lang === "en") return "en";
  if (lang === "br" || lang === "pt") return "br";
  if (lang === "auto") return "auto";
  return TX_LANG_DEFAULT;
}

function txLangInfo(value) {
  const lang = normTxLang(value);
  return TX_LANG_OPTIONS.find((o) => o.value === lang) || TX_LANG_OPTIONS[0];
}

// Where the menu goes for a button at `rect`, inside a `view` of {width,height}.
//
// Preferred side is LEFT of the button — the Facebook rail sits on the video's left
// edge and a menu opening rightwards would cover the video. A button too close to
// the left edge for that (Instagram's tile actions sit at left:7px) flips to the
// right instead of being clamped into a strip overlapping itself.
const TX_LANG_MENU_W = 124;
// Three 30px items + gaps + padding + border ≈ 112px, plus a margin.
const TX_LANG_MENU_H = 126;
function txLangMenuPos(rect, view) {
  const preferred = rect.left - 102;
  const left = preferred < 8 ? rect.right + 6 : preferred;
  return {
    top: Math.max(8, Math.min(view.height - TX_LANG_MENU_H, rect.top)),
    left: Math.max(8, Math.min(view.width - 132, left)),
  };
}

const TX_LANG_CSS = `
.fbw-lang-host{position:relative}
.fbw-lang-badge{position:absolute;right:-5px;bottom:-5px;min-width:18px;height:14px;padding:0 3px;border-radius:5px;
  display:grid;place-items:center;background:rgba(15,23,42,.96);color:#dbeafe;border:1px solid rgba(150,185,255,.55);
  font:800 8px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:0;pointer-events:none}
.fbw-lang-menu{position:fixed;z-index:2147483600;display:grid;gap:4px;width:${TX_LANG_MENU_W}px;padding:6px;border-radius:9px;
  background:rgba(17,24,44,.98);border:1px solid rgba(150,185,255,.42);box-shadow:0 8px 24px rgba(0,0,0,.45);
  font:600 12px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#fff}
.fbw-lang-menu button{height:30px;border:0;border-radius:6px;background:transparent;color:#e5e7eb;text-align:left;
  padding:0 8px;cursor:pointer;font:inherit}
.fbw-lang-menu button:hover,.fbw-lang-menu button.active{background:rgba(59,130,246,.24);color:#fff}`;

// On <html>, not <body>: the menu itself is appended there (outside the page's
// React root, which reconciles <body> children away), so its rules must survive
// the same way.
function ensureTxLangStyle() {
  if (document.getElementById("fbw-lang-style")) return;
  const s = document.createElement("style");
  s.id = "fbw-lang-style";
  s.textContent = TX_LANG_CSS;
  (document.head || document.documentElement).appendChild(s);
}

let txLangCache = TX_LANG_DEFAULT;
// The buttons that asked for a badge. A Set (not a selector) because each overlay
// names its buttons differently, and pruning on the way past keeps rails that FB
// remounts constantly from leaking entries.
const txBadged = new Set();

async function getTxLang() {
  try {
    const r = await chrome.storage.local.get(TX_LANG_KEY);
    txLangCache = normTxLang(r?.[TX_LANG_KEY]);
  } catch {
    /* storage gone (extension reloaded under us) — keep the cached value */
  }
  return txLangCache;
}

async function setTxLang(value) {
  txLangCache = normTxLang(value);
  try {
    await chrome.storage.local.set({ [TX_LANG_KEY]: txLangCache });
  } catch {
    /* the caller still gets the normalized value for THIS job */
  }
  updateTxBadges();
  return txLangCache;
}

/** Opt a Transcribe button in: it gets the badge now and on every refresh. */
function enableTxBadge(btn) {
  if (!btn) return;
  ensureTxLangStyle();
  btn.classList.add("fbw-lang-host");
  txBadged.add(btn);
  paintTxBadge(btn);
}

/** Repaint one button's badge — a no-op for buttons that never opted in, so a
 *  platform's shared "button changed state" hook can call it blindly. */
function addTxBadge(btn) {
  if (btn && txBadged.has(btn)) paintTxBadge(btn);
}

function paintTxBadge(btn) {
  let badge = btn.querySelector(".fbw-lang-badge");
  if (!badge) {
    badge = document.createElement("span");
    badge.className = "fbw-lang-badge";
    btn.appendChild(badge);
  }
  badge.textContent = txLangInfo(btn.dataset.lang || txLangCache).short;
}

/** Repaint every opted-in badge, dropping buttons whose rail has been torn down.
 *  Busy buttons are skipped: their glyph is a spinner the badge would sit on. */
function updateTxBadges() {
  for (const btn of txBadged) {
    if (!btn.isConnected) {
      txBadged.delete(btn);
      continue;
    }
    if (!btn.classList.contains("busy")) paintTxBadge(btn);
  }
}

/** Load the stored choice and keep every badge in step with it — including when
 *  the OTHER platform's rail changes it in another tab. */
function watchTxLang() {
  getTxLang().then(updateTxBadges).catch(() => {});
  chrome.storage?.onChanged?.addListener?.((changes, area) => {
    if (area !== "local" || !changes[TX_LANG_KEY]) return;
    txLangCache = normTxLang(changes[TX_LANG_KEY].newValue);
    updateTxBadges();
  });
}

let txLangMenu = null;
let txLangOutside = null;

function closeTxLangMenu() {
  if (txLangOutside) {
    document.removeEventListener("pointerdown", txLangOutside, true);
    window.removeEventListener("blur", closeTxLangMenu);
    window.removeEventListener("scroll", closeTxLangMenu, true);
    txLangOutside = null;
  }
  if (txLangMenu) {
    txLangMenu.remove();
    txLangMenu = null;
  }
}

/**
 * Open the BR/EN menu for `btn`; `onPick(lang)` runs after the choice is saved.
 * A busy button is ignored — its job is already in flight.
 */
function openTxLangMenu(btn, onPick) {
  if (!btn || btn.classList.contains("busy")) return;
  ensureTxLangStyle();
  closeTxLangMenu();
  const pos = txLangMenuPos(btn.getBoundingClientRect(), {
    width: window.innerWidth,
    height: window.innerHeight,
  });
  const menu = document.createElement("div");
  menu.className = "fbw-lang-menu";
  menu.setAttribute("role", "menu");
  menu.style.top = `${pos.top}px`;
  menu.style.left = `${pos.left}px`;
  for (const opt of TX_LANG_OPTIONS) {
    const item = document.createElement("button");
    item.type = "button";
    item.className = opt.value === txLangCache ? "active" : "";
    item.textContent = opt.label;
    // The host page (FB's reel player, IG's story viewer) toggles playback on the
    // pointer sequence, so the whole sequence is swallowed — not just the click.
    item.addEventListener("pointerdown", (e) => { e.preventDefault(); e.stopPropagation(); });
    item.addEventListener("click", async (e) => {
      e.preventDefault();
      e.stopPropagation();
      const lang = await setTxLang(opt.value);
      btn.dataset.lang = lang;
      closeTxLangMenu();
      onPick(lang);
    });
    menu.appendChild(item);
  }
  txLangMenu = menu;
  document.documentElement.appendChild(menu);
  // Next tick: the click that OPENED the menu is still travelling, and a listener
  // armed synchronously would see it as an outside click and close immediately.
  setTimeout(() => {
    txLangOutside = (e) => {
      if (menu.contains(e.target) || btn.contains(e.target)) return;
      closeTxLangMenu();
    };
    document.addEventListener("pointerdown", txLangOutside, true);
    window.addEventListener("blur", closeTxLangMenu, { once: true });
    window.addEventListener("scroll", closeTxLangMenu, { once: true, capture: true });
  }, 0);
}
// >>> inline:end
  // <<< inline:src/lib/shared/fbReelActions.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fbReelActions.js and run `npm run gen:inline`.

function fbReelEntry(rec) {
  if (!rec?.id) return null;
  return { ...buildSavedEntry({ id: rec.id, platform: 'facebook', mediaType: 'video',
    thumb: rec.thumb, caption: rec.caption, authorName: rec.authorName, authorUrl: rec.authorUrl,
    counts: { view: rec.views, like: rec.likes, comment: rec.comments, share: rec.shares } }),
    videoKind: 'reel', takenAt: rec.taken_at ?? null, durationS: rec.duration ?? null, followers: rec.followers ?? null };
}

function fbReelJob(rec, action, language = 'en') {
  if (!/^\d{6,}$/.test(rec?.id || '')) throw new Error('Reel indisponível. Recarregue a página.');
  const name = (rec.authorName || 'facebook').replace(/[^\p{L}\p{N} _-]/gu, '').trim().slice(0,60) || 'facebook';
  const base = `${name}-fb-${rec.id}`;
  if (action === 'download' || action === 'thumb') {
    const url = fbMediaUrl(action === 'thumb' ? fullResThumb(rec.thumb) : rec.progressive);
    if (!url) throw new Error('Mídia ainda indisponível. Abra o reel e tente novamente.');
    return { type: 'FBW_DL_MEDIA', platform: 'facebook', kind: action === 'thumb' ? 'image' : 'video',
      ...(action === 'thumb' ? { folder: 'thumb' } : {}), url, filename: `${base}${action === 'thumb' ? '-thumb.jpg' : '.mp4'}` };
  }
  const mediaUrl = fbMediaUrl(rec.audio) || fbMediaUrl(rec.progressive);
  if (!mediaUrl) throw new Error('Áudio ainda indisponível. Abra o reel e tente novamente.');
  if (action === 'voice') return { type: 'FBW_EXTRACT_VOICE', videoId: rec.id, mediaUrl, jobId: crypto.randomUUID(), filename: `${base}-voz.mp3` };
  if (action !== 'transcribe') throw new Error('Ação desconhecida');
  const lang = normTxLang(language);
  const caption = fbCaptionFor(rec, lang);
  return { ...fbReelEntry(rec), type: 'FBW_TRANSCRIBE', mediaUrl, idConfident: true, language: lang,
    ...(caption ? { captionUrl: caption.url, captionLang: caption.lang, captionFormat: 'srt' } : {}) };
}
// >>> inline:end
  // <<< inline:src/lib/shared/fmt.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fmt.js and run `npm run gen:inline`.
// Formatters every platform needs: a date, an engagement rate and the view
// velocity. INLINED into content scripts — see ./README.md before editing (no
// imports allowed beyond a sibling: fmtCount comes from ./counts.js, which every
// target inlines first).
//
// These lived in igFormat.js and were hand-copied into ttMedia.js. Same numbers,
// two implementations, and only one of them was tested — exactly the drift this
// directory exists to stop. (Count formatting is next door, in counts.js.)

/** Unix SECONDS → "YYYY-MM-DD" (empty string when missing/invalid). */
function fmtDate(unixSeconds) {
  if (!unixSeconds) return "";
  const d = new Date(unixSeconds * 1000);
  return Number.isNaN(d.getTime()) ? "" : d.toISOString().slice(0, 10);
}

// Engagement-rate label. Never collapses to "0.0%": 1 decimal ≥10, 2 decimals
// ≥0.1, else 2 significant figures (e.g. "0.06%", "0.004%").
function fmtER(er) {
  if (er == null) return null;
  if (er === 0) return "0%";
  if (er >= 10) return er.toFixed(1) + "%";
  if (er >= 0.1) return er.toFixed(2) + "%";
  return Number(er.toPrecision(2)) + "%";
}

// ---- velocity -------------------------------------------------------------
// Views per day since the post went up. Unlike reach (views ÷ followers) it needs
// nothing but the post itself, so it exists on EVERY video — including hashtag
// and search results, where Instagram ships no follower count at all (measured
// on #soulmate, 2026-09-26: 0 of 28 posts). It answers "what is running right
// now": 1.2M views in 3 days (400K/dia) beats 6M in two years (8.2K/dia).
//
// A post younger than a day counts as one day: dividing by 2 hours would turn a
// fresh reel's first views into an absurd daily rate.

/** Views per day since `postedAt` (unix seconds or ms), or null when either is missing. */
function viewsPerDay(views, postedAt, nowSec = Math.floor(Date.now() / 1000)) {
  if (views == null || !Number.isFinite(views) || !postedAt) return null;
  const posted = postedAt > 1e11 ? postedAt / 1000 : postedAt;
  const days = Math.max((nowSec - posted) / 86400, 1);
  return views / days;
}

/** "400K/dia" — the rate in the rail's own count style. */
function fmtVelocity(v) {
  if (v == null || !Number.isFinite(v)) return null;
  return `${fmtCount(Math.round(v))}/dia`;
}
// >>> inline:end
  // <<< inline:src/lib/shared/fbQuery.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fbQuery.js and run `npm run gen:inline`.

// Shares on Facebook are not Instagram reposts. Keep the formula explicit and
// return unknown until every input has arrived (including the deferred likes).
function fbEngagement(r) {
  return r.views > 0 && [r.likes, r.comments, r.shares].every(Number.isFinite)
    ? (r.likes + 4 * r.comments + 4 * r.shares) / r.views * 100 : null;
}
const fbRate = (n, d) => n != null && d > 0 ? n / d * 100 : null;
const FB_QUERY_FIELDS = {
  views: { label: 'Visualizações', short: 'Views', kind: 'number', get: r => r.views },
  likes: { label: 'Curtidas', kind: 'number', get: r => r.likes },
  comments: { label: 'Comentários', kind: 'number', get: r => r.comments },
  shares: { label: 'Compartilhamentos', short: 'Compart.', kind: 'number', get: r => r.shares },
  date: { label: 'Publicação', kind: 'date', get: r => r.taken_at },
  velocity: { label: 'Views/dia', kind: 'number', get: r => viewsPerDay(r.views, r.taken_at) },
  er: { label: 'Engajamento %', kind: 'number', get: fbEngagement },
  likeRate: { label: 'Curtidas / views %', kind: 'number', get: r => fbRate(r.likes, r.views) },
  commentRate: { label: 'Comentários / views %', kind: 'number', get: r => fbRate(r.comments, r.views) },
  shareRate: { label: 'Compart. / views %', kind: 'number', get: r => fbRate(r.shares, r.views) },
  duration: { label: 'Duração (s)', kind: 'number', sortable: false, get: r => r.duration },
  followers: { label: 'Seguidores', kind: 'number', sortable: false, get: r => r.followers },
  reach: { label: 'Views / seguidores', kind: 'number', get: r => r.followers > 0 && r.views != null ? r.views / r.followers : null },
  caption: { label: 'Descrição', kind: 'text', get: r => r.caption },
  author: { label: 'Autor', kind: 'text', get: r => r.authorName },
};
// >>> inline:end
  // <<< inline:src/lib/shared/feedQuery.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/feedQuery.js and run `npm run gen:inline`.
// The feed query: which posts to keep and in what order. Canonical source —
// INLINED into the Instagram bridge and the TikTok relay (see ./README.md: no
// imports allowed here), and imported by the panel, so the side panel's list and
// the site's own grid (reordered in place) always agree.
//
// Shape, as stored in chrome.storage.local (sw_ig_query / sw_tt_query):
//   { version: 1, join: "all" | "any",
//     sorts:   [{ key, dir: "asc" | "desc" }, …],        // first = primary
//     filters: [{ field, op, value, valueTo }, …] }
//
// The engine knows nothing about a platform. A FIELD MAP does
// ({ key: { kind: "number" | "text" | "date" | "enum", get(rec, ctx), values? } }),
// see igQuery.js / ttQuery.js; `ctx` carries whatever a derived field needs (the
// user's ER weights).

const QUERY_OPS = {
  number: ["gte", "lte", "gt", "lt", "between", "eq", "neq", "notEmpty"],
  date: ["gte", "lte", "between", "notEmpty"],
  text: ["contains", "notContains", "notEmpty"],
  enum: ["isAnyOf"],
};

/**
 * Can this field order a list? Numbers and dates can, unless the field map says
 * `sortable: false` — follower count and duration filter well ("accounts under
 * 10K", "videos under 30 s") but make no sense as an order for a grid of posts.
 */
function isSortableField(def) {
  return !!def && (def.kind === "number" || def.kind === "date") && def.sortable !== false;
}

function emptyQuery() {
  return { version: 1, join: "all", sorts: [], filters: [] };
}

const isBlank = (v) => v == null || v === "" || (Array.isArray(v) && v.length === 0);

/** Drop what the field map doesn't know, duplicate sort keys and bad values. */
function normalizeQuery(q, fields) {
  const out = emptyQuery();
  if (!q || typeof q !== "object") return out;
  out.join = q.join === "any" ? "any" : "all";
  const seen = new Set();
  for (const s of Array.isArray(q.sorts) ? q.sorts : []) {
    if (!s || !fields[s.key] || seen.has(s.key) || (s.dir !== "asc" && s.dir !== "desc")) continue;
    seen.add(s.key);
    out.sorts.push({ key: s.key, dir: s.dir });
  }
  for (const f of Array.isArray(q.filters) ? q.filters : []) {
    const def = f && fields[f.field];
    if (!def || !(QUERY_OPS[def.kind] || []).includes(f.op)) continue;
    out.filters.push({ field: f.field, op: f.op, value: f.value ?? null, valueTo: f.valueTo ?? null });
  }
  return out;
}

function valueOf(rec, key, fields, ctx) {
  const def = fields[key];
  if (!def) return null;
  const v = def.get(rec, ctx || {});
  if (v == null || v === "") return null;
  if (typeof v === "number") return Number.isFinite(v) ? v : null;
  if (Array.isArray(v)) return v.length ? v : null;
  return v;
}

/**
 * Does one record pass one rule? A rule still missing its value (mid-typing)
 * passes everything, so the list doesn't blank while the user types.
 */
function matchesFilter(rec, f, fields, ctx) {
  const def = fields[f.field];
  if (!def) return true;
  const v = valueOf(rec, f.field, fields, ctx);
  if (f.op === "notEmpty") return v != null;
  if (isBlank(f.value) || (f.op === "between" && isBlank(f.valueTo))) return true;
  if (v == null) return false;
  if (def.kind === "text") {
    const hay = (Array.isArray(v) ? v.join(" ") : String(v)).toLowerCase();
    const needle = String(f.value).toLowerCase();
    return f.op === "contains" ? hay.includes(needle) : f.op === "notContains" ? !hay.includes(needle) : true;
  }
  if (def.kind === "enum") {
    const want = (Array.isArray(f.value) ? f.value : [f.value]).map(String);
    return (Array.isArray(v) ? v : [v]).some((x) => want.includes(String(x)));
  }
  const n = Number(v);
  const a = Number(f.value);
  if (!Number.isFinite(n) || !Number.isFinite(a)) return true;
  switch (f.op) {
    case "gt": return n > a;
    case "gte": return n >= a;
    case "lt": return n < a;
    case "lte": return n <= a;
    case "eq": return n === a;
    case "neq": return n !== a;
    case "between": {
      const b = Number(f.valueTo);
      if (!Number.isFinite(b)) return true;
      return n >= Math.min(a, b) && n <= Math.max(a, b);
    }
    default: return true;
  }
}

function matchesQuery(rec, q, fields, ctx) {
  if (!q.filters.length) return true;
  return q.join === "any"
    ? q.filters.some((f) => matchesFilter(rec, f, fields, ctx))
    : q.filters.every((f) => matchesFilter(rec, f, fields, ctx));
}

/**
 * Comparator for the query's sorts. A missing value sorts last whichever the
 * direction; a full tie returns 0, so Array#sort (stable) keeps capture order.
 */
function compareByQuery(q, fields, ctx) {
  return (a, b) => {
    for (const s of q.sorts) {
      const av = valueOf(a, s.key, fields, ctx);
      const bv = valueOf(b, s.key, fields, ctx);
      if (av == null && bv == null) continue;
      if (av == null) return 1;
      if (bv == null) return -1;
      const d =
        typeof av === "number" && typeof bv === "number"
          ? av - bv
          : String(av).localeCompare(String(bv));
      if (d) return s.dir === "asc" ? d : -d;
    }
    return 0;
  };
}

/** Filter, then sort. No sorts = input (capture) order. */
function applyQuery(records, q, fields, ctx) {
  const kept = records.filter((r) => matchesQuery(r, q, fields, ctx));
  return q.sorts.length ? kept.sort(compareByQuery(q, fields, ctx)) : kept;
}

/** The first sort as the classic select + direction pair ("default" = none). */
function primarySort(q) {
  const s = q && q.sorts && q.sorts[0];
  return s ? { key: s.key, dir: s.dir } : { key: "default", dir: "desc" };
}

/** Replace the primary sort, keeping the tie-breakers after it. */
function withPrimarySort(q, key, dir) {
  if (key === "default") return { ...q, sorts: [] };
  const rest = (q.sorts || []).slice(1).filter((s) => s.key !== key);
  return { ...q, sorts: [{ key, dir }, ...rest] };
}

/** Cheap identity for "did the query change?" checks. */
function querySignature(q) {
  return JSON.stringify([q.join, q.sorts, q.filters]);
}
// >>> inline:end
  // <<< inline:src/lib/shared/gridSort.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/gridSort.js and run `npm run gen:inline`.
// Reordering a site's own grid in place. Canonical source — INLINED into the
// Instagram bridge and the TikTok relay (see ./README.md: no imports here).
//
// The unit that moves is the grid CELL: the outermost box around one tile that
// holds no other tile. On TikTok the cells are siblings; on Instagram's profile
// grid they sit in rows of three, so a sort has to move cells ACROSS parents. It
// does that by dropping a comment marker in front of every cell (one marker per
// slot), putting the i-th sorted cell after the i-th marker, and removing the
// markers — rows keep their three children, and anything that is not a tile (an
// ad, a "load more" row) never moves. When every cell is a contiguous sibling
// run, one DocumentFragment insert does it instead.
//
// Every cell is stamped with the order it was first seen in, so "Padrão" can
// put the grid back exactly as the site drew it.

const ORIG_KEY = "__swOrigIndex";
let swOrigCounter = 0;

/**
 * The grid cell around a tile link: climb while the parent still holds only
 * links to this same post (a tile often carries two — the thumbnail and the
 * caption line).
 */
function gridCellOf(link, linkSelector, keyOf, maxUp = 8) {
  const key = keyOf(link);
  let cell = link;
  for (let i = 0; i < maxUp; i++) {
    const p = cell.parentElement;
    if (!p || p === document.body || p === document.documentElement) break;
    let other = false;
    for (const a of p.querySelectorAll(linkSelector)) {
      const k = keyOf(a);
      if (k && k !== key) { other = true; break; }
    }
    if (other) break;
    cell = p;
  }
  return cell;
}

/** Give every not-yet-seen cell its first-seen position (document order in). */
function stampOrigIndex(cells) {
  for (const c of cells) if (c[ORIG_KEY] == null) c[ORIG_KEY] = swOrigCounter++;
}

function origIndexOf(cell) {
  return cell[ORIG_KEY] == null ? Number.MAX_SAFE_INTEGER : cell[ORIG_KEY];
}

function contiguousSiblings(cells) {
  const parent = cells[0].parentElement;
  if (!parent) return false;
  const set = new Set(cells);
  let n = cells[0];
  let seen = 0;
  while (n && seen < cells.length) {
    if (n.nodeType === 1) {
      if (!set.has(n)) return false;
      seen++;
    }
    n = n.nextSibling;
  }
  return seen === cells.length && cells.every((c) => c.parentElement === parent);
}

/**
 * Put `ordered` into the slots `cells` occupy now (both in any order; `cells`
 * is read in document order). Returns how many slots changed.
 */
function reorderCells(cells, ordered) {
  const slots = [...cells].sort((a, b) =>
    a === b ? 0 : a.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1,
  );
  let changed = 0;
  for (let i = 0; i < slots.length; i++) if (slots[i] !== ordered[i]) changed++;
  if (!changed) return 0;
  if (contiguousSiblings(slots)) {
    const parent = slots[0].parentElement;
    const after = slots[slots.length - 1].nextSibling;
    const frag = document.createDocumentFragment();
    for (const c of ordered) frag.appendChild(c);
    parent.insertBefore(frag, after);
    return changed;
  }
  const markers = slots.map((c) => {
    const m = document.createComment("sw-slot");
    c.parentNode.insertBefore(m, c);
    return m;
  });
  for (let i = 0; i < ordered.length; i++) markers[i].parentNode.insertBefore(ordered[i], markers[i].nextSibling);
  for (const m of markers) m.remove();
  return changed;
}

/** Hide a cell a filter rejects, remembering its own inline display. */
function setCellHidden(cell, hide) {
  if (hide) {
    if (cell.dataset.swHidden === "1") return;
    cell.dataset.swHidden = "1";
    cell.dataset.swPrevDisplay = cell.style.display || "";
    cell.style.display = "none";
  } else if (cell.dataset.swHidden === "1") {
    cell.style.display = cell.dataset.swPrevDisplay || "";
    delete cell.dataset.swHidden;
    delete cell.dataset.swPrevDisplay;
  }
}
// >>> inline:end
  // <<< inline:src/lib/shared/pageSorter.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/pageSorter.js and run `npm run gen:inline`.
// The site's own grid, sorted and filtered in place — plus the little bar on the
// page that drives it. Canonical source — INLINED into the Instagram bridge and
// the TikTok relay (see ./README.md), after ./feedQuery.js and ./gridSort.js.
//
// ONE query per platform lives in chrome.storage.local (sw_ig_query /
// sw_tt_query). The side panel's sort tool and this bar both read and write it,
// so changing the order in either place reorders the other: the panel list and
// the page grid never disagree.
//
// Everything platform-specific comes in through `opts`:
//   storage       { get(key) → Promise<obj>, set(obj), onChanged(fn(changes)) }
//   storageKey    "sw_ig_query" | "sw_tt_query"
//   fields        IG_QUERY_FIELDS | TT_QUERY_FIELDS
//   ctx()         → { weights } for derived fields (ER)
//   linkSelector  what a tile link looks like
//   keyOf(a)      → the post key a tile link points at
//   recordOf(key) → the captured record, or null
//   linkOk(a)     → false for links outside the grid (hovercards, rails…)
//   routeOk(path) → is this page a grid at all?


const PS_BAR_ID = "sw-psort";
const PS_STYLE_ID = "sw-psort-style";
const PS_CSS = `
#${PS_BAR_ID}{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:2147482500;display:flex;
  align-items:center;gap:6px;padding:6px 8px 6px 10px;border-radius:999px;background:rgba(17,20,32,.92);
  border:1px solid rgba(150,185,255,.35);box-shadow:0 6px 24px rgba(0,0,0,.45);backdrop-filter:blur(8px);
  font:600 12px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#fff}
#${PS_BAR_ID} .ps-lbl{opacity:.7;font-weight:600}
#${PS_BAR_ID} select{appearance:none;background:rgba(255,255,255,.08);color:#fff;border:1px solid rgba(255,255,255,.14);
  border-radius:999px;padding:6px 10px;font:inherit;cursor:pointer;max-width:170px}
#${PS_BAR_ID} select option{color:#111}
#${PS_BAR_ID} button{display:grid;place-items:center;height:26px;min-width:26px;padding:0 8px;border-radius:999px;cursor:pointer;
  background:rgba(255,255,255,.08);color:#fff;border:1px solid rgba(255,255,255,.14);font:inherit}
#${PS_BAR_ID} button:hover,#${PS_BAR_ID} select:hover{background:rgba(255,255,255,.16)}
#${PS_BAR_ID} .ps-flt{color:#facc15;border-color:rgba(250,204,21,.45)}
#${PS_BAR_ID}[data-min="1"] .ps-full{display:none}
#${PS_BAR_ID}:not([data-min="1"]) .ps-mini{display:none}
`;

function makePageSorter(opts) {
  const { storage, storageKey, fields, linkSelector, keyOf, recordOf } = opts;
  const ctx = opts.ctx || (() => ({}));
  const linkOk = opts.linkOk || (() => true);
  const routeOk = opts.routeOk || (() => true);
  const routeKey = opts.routeKey || (() => location.pathname);
  let query = emptyQuery();
  let timer = null;
  let dead = false;
  let touched = false; // has this page's grid been moved or filtered by us?
  let minimized = false;
  // Every time a grid page opens (load, new tab, SPA hop to another profile or
  // search) the sort starts at the site's own order — a sort picked yesterday must
  // not greet today's page reordered. Filters are kept. A post modal (/p/…) is not
  // a grid route, so opening and closing one does not count as a new page.
  let loaded = false;
  let gridPath = null;

  function collect() {
    const byKey = new Map();
    for (const a of document.querySelectorAll(linkSelector)) {
      if (!linkOk(a)) continue;
      const key = keyOf(a);
      if (!key || byKey.has(key)) continue;
      byKey.set(key, gridCellOf(a, linkSelector, keyOf));
    }
    const entries = [...byKey.entries()].map(([key, cell]) => ({ key, cell }));
    entries.sort((x, y) =>
      x.cell === y.cell ? 0 : x.cell.compareDocumentPosition(y.cell) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1,
    );
    stampOrigIndex(entries.map((e) => e.cell));
    return entries;
  }

  /** One pass: filter (hide), then sort (reorder). Returns cells moved. */
  function applyNow() {
    timer = null;
    if (dead) return 0;
    const onRoute = routeOk(location.pathname);
    if (loaded && onRoute && routeKey() !== gridPath) {
      gridPath = routeKey();
      if (query.sorts.length) {
        query = { ...query, sorts: [] };
        storage.set({ [storageKey]: query });
        renderBarState();
      }
    }
    const entries = onRoute ? collect() : [];
    renderBar(onRoute && entries.length >= 2);
    if (!entries.length) return 0;
    const active = query.sorts.length > 0 || query.filters.length > 0;
    if (!active && !touched) return 0;
    const c = ctx();
    for (const e of entries) {
      const rec = recordOf(e.key);
      // A tile with no captured record stays visible: "not known yet" is not "rejected".
      setCellHidden(e.cell, !!(rec && query.filters.length && !matchesQuery(rec, query, fields, c)));
    }
    let ordered;
    if (!query.sorts.length) {
      ordered = entries.map((e) => e.cell).sort((x, y) => origIndexOf(x) - origIndexOf(y));
    } else {
      const cmp = compareByQuery(query, fields, c);
      ordered = [...entries]
        .sort((x, y) => {
          const rx = recordOf(x.key);
          const ry = recordOf(y.key);
          if (rx && ry) return cmp(rx, ry) || origIndexOf(x.cell) - origIndexOf(y.cell);
          if (rx) return -1;
          if (ry) return 1;
          return origIndexOf(x.cell) - origIndexOf(y.cell);
        })
        .map((e) => e.cell);
    }
    const moved = reorderCells(entries.map((e) => e.cell), ordered);
    touched = active;
    return moved;
  }

  // A pending pass is NOT pushed back by later calls (the page mutates without
  // pause — a resetting debounce would never fire); only an immediate request
  // (ms = 0: the query changed) jumps the queue.
  function schedule(ms = 250) {
    if (dead) return;
    if (timer) {
      if (ms > 0) return;
      clearTimeout(timer);
    }
    timer = setTimeout(applyNow, ms);
  }

  function setQuery(q) {
    query = normalizeQuery(q, fields);
    storage.set({ [storageKey]: query });
    renderBarState();
    schedule(0);
  }

  // ---- the bar ----
  function sortableKeys() {
    return Object.keys(fields).filter((k) => isSortableField(fields[k]));
  }
  function ensureBar() {
    let bar = document.getElementById(PS_BAR_ID);
    if (bar) return bar;
    if (!document.getElementById(PS_STYLE_ID)) {
      const st = document.createElement("style");
      st.id = PS_STYLE_ID;
      st.textContent = PS_CSS;
      (document.head || document.documentElement).appendChild(st);
    }
    bar = document.createElement("div");
    bar.id = PS_BAR_ID;
    const opt = (v, l) => `<option value="${v}">${l}</option>`;
    bar.innerHTML =
      `<button type="button" class="ps-mini" data-ps="expand" title="Ordenar a grade">⇅</button>` +
      `<span class="ps-full ps-lbl">Ordenar</span>` +
      `<select class="ps-full" data-ps="key" title="Ordenar a grade por">${opt("default", "Padrão do site")}${sortableKeys()
        .map((k) => opt(k, fields[k].label))
        .join("")}</select>` +
      `<button type="button" class="ps-full" data-ps="dir"></button>` +
      `<button type="button" class="ps-full ps-flt" data-ps="flt" title="Filtros ativos — edite no painel"></button>` +
      `<button type="button" class="ps-full" data-ps="min" title="Recolher">–</button>`;
    for (const ev of ["pointerdown", "mousedown", "click", "keydown", "wheel"])
      bar.addEventListener(ev, (e) => e.stopPropagation());
    bar.querySelector('[data-ps="key"]').addEventListener("change", (e) => {
      setQuery(withPrimarySort(query, e.target.value, primarySort(query).dir));
    });
    bar.querySelector('[data-ps="dir"]').addEventListener("click", () => {
      const p = primarySort(query);
      if (p.key === "default") return;
      setQuery(withPrimarySort(query, p.key, p.dir === "desc" ? "asc" : "desc"));
    });
    bar.querySelector('[data-ps="flt"]').addEventListener("click", () => setQuery({ ...query, filters: [] }));
    bar.querySelector('[data-ps="min"]').addEventListener("click", () => { minimized = true; renderBarState(); });
    bar.querySelector('[data-ps="expand"]').addEventListener("click", () => { minimized = false; renderBarState(); });
    (document.body || document.documentElement).appendChild(bar);
    return bar;
  }
  function renderBarState() {
    const bar = document.getElementById(PS_BAR_ID);
    if (!bar) return;
    const p = primarySort(query);
    bar.dataset.min = minimized ? "1" : "";
    const sel = bar.querySelector('[data-ps="key"]');
    if (sel.value !== p.key) sel.value = p.key;
    const dir = bar.querySelector('[data-ps="dir"]');
    dir.textContent = p.dir === "desc" ? "↓" : "↑";
    dir.title = p.dir === "desc" ? "Maior → menor" : "Menor → maior";
    dir.style.display = minimized || p.key === "default" ? "none" : "";
    const flt = bar.querySelector('[data-ps="flt"]');
    const n = query.filters.length;
    flt.textContent = n ? `${n} filtro${n > 1 ? "s" : ""} ✕` : "";
    flt.style.display = minimized || !n ? "none" : "";
  }
  function renderBar(show) {
    const bar = document.getElementById(PS_BAR_ID);
    if (!show || opts.barEnabled === false || (opts.barVisible && !opts.barVisible())) {
      if (bar) bar.remove();
      return;
    }
    ensureBar();
    renderBarState();
  }

  storage.get(storageKey).then((r) => {
    query = normalizeQuery(r && r[storageKey], fields);
    loaded = true;
    renderBarState();
    schedule(0);
  });
  storage.onChanged((changes) => {
    if (!changes[storageKey]) return;
    const next = normalizeQuery(changes[storageKey].newValue, fields);
    if (querySignature(next) === querySignature(query)) return;
    query = next;
    renderBarState();
    schedule(0);
  });

  return {
    schedule,
    applyNow,
    getQuery: () => query,
    destroy() {
      dead = true;
      if (timer) clearTimeout(timer);
      document.getElementById(PS_BAR_ID)?.remove();
    },
  };
}

/** The chrome.storage.local adapter the content scripts hand to makePageSorter. */
function chromeQueryStorage() {
  return {
    get: (k) => chrome.storage.local.get(k).catch(() => ({})),
    set: (obj) => { chrome.storage.local.set(obj).catch(() => {}); },
    onChanged: (fn) =>
      chrome.storage.onChanged.addListener((changes, area) => { if (area === "local") fn(changes); }),
  };
}
// >>> inline:end
  // <<< inline:src/lib/shared/overlayUi.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/overlayUi.js and run `npm run gen:inline`.
// The button machinery behind the injected page overlays: one icon vocabulary and
// one state machine. INLINED into content scripts — see src/lib/shared/README.md
// before editing (no imports allowed in this file).
//
// Instagram, TikTok and Pinterest each grew their own copy of both and the copies
// had already drifted: three stroke widths for the same lucide glyphs, two
// orderings of the same file-text paths, and 1200 / 1300 / 2500ms for the same
// "did it work?" flash.
//
// What is deliberately NOT here: the CSS and the render loops. Those are genuinely
// per-platform (different tile structures, different mutation patterns) and each
// overlay keeps its own button class — .sw-actbtn, .sw-ttbtn, .sw-pinbtn — so the
// state machine below only ever touches the element it is handed.

// lucide-style 24×24 stroked glyphs, rendered by overlayIcon().
const OVERLAY_ICONS = {
  voice: '<path d="M2 10v3"/><path d="M6 6v11"/><path d="M10 3v18"/><path d="M14 8v7"/><path d="M18 5v13"/><path d="M22 10v3"/>',
  dl: '<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" x2="12" y1="15" y2="3"/>',
  save: '<path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/>',
  img: '<rect width="18" height="18" x="3" y="3" rx="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.1-3.1a2 2 0 0 0-2.8 0L6 21"/>',
  tx: '<path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M10 9H8"/><path d="M16 13H8"/><path d="M16 17H8"/>',
  link: '<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>',
  layers: '<path d="M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83Z"/><path d="M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12"/><path d="M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17"/>',
  msg: '<path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z"/>',
  heart: '<path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"/>',
  ok: '<polyline points="20 6 9 17 4 12"/>',
  err: '<line x1="18" x2="6" y1="6" y2="18"/><line x1="6" x2="18" y1="6" y2="18"/>',
  // Instagram's stats rail only. Kept here so there is one place to look up a
  // glyph, rather than one shared map plus a private map for the odd ones out.
  eye: '<circle cx="12" cy="12" r="3"/><path d="M2.06 12.35a1 1 0 0 1 0-.7 10.75 10.75 0 0 1 19.88 0 1 1 0 0 1 0 .7 10.75 10.75 0 0 1-19.88 0"/>',
  zap: '<path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"/>',
  repost: '<path d="m17 2 4 4-4 4"/><path d="M3 11v-1a4 4 0 0 1 4-4h14"/><path d="m7 22-4-4 4-4"/><path d="M21 13v1a4 4 0 0 1-4 4H3"/>',
  cal: '<path d="M8 2v4"/><path d="M16 2v4"/><rect width="18" height="18" x="3" y="4" rx="2"/><path d="M3 10h18"/>',
  // Follower count — how big the account behind the post is.
  user: '<path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>',
  // Reach multiplier: views divided by the creator's followers. A separate glyph
  // from `user` on purpose — the two used to share a row behind the follower
  // icon, which said "followers" over a number that is not a follower count.
  trend: '<polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/>',
  // Reach (views ÷ followers): how far past its own audience a post travelled.
  // lucide "radio-tower". The trend arrow above is velocity (views per day).
  tower: '<path d="M4.9 16.1C1 12.2 1 5.8 4.9 1.9"/><path d="M7.8 4.7a6.14 6.14 0 0 0-.8 7.5"/><circle cx="12" cy="9" r="2"/><path d="M16.2 4.8c2 2 2.26 5.11.8 7.47"/><path d="M19.1 1.9a9.96 9.96 0 0 1 0 14.1"/><path d="M9.5 18h5"/><path d="m8 22 4-11 4 11"/>',
  // The sound a reel rides, so a trend can be traced to its audio.
  audio: '<path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>',
};

// 15px is the tile-action button's glyph; the floating rails pass their own size.
// An unknown name renders an empty <svg> rather than the string "undefined".
function overlayIcon(name, size = 15) {
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" width="${size}" height="${size}">${OVERLAY_ICONS[name] || ""}</svg>`;
}

// How long ok/err feedback stays before the button goes back to idle. Pinterest's
// 2.5s is the one long enough to be read on a grid that is still mutating.
const OVERLAY_FLASH_MS = 2500;

/**
 * busy / ok / err / idle for one overlay button. Only the STATE classes are
 * shared; the button's own class is the platform's business, so this takes the
 * element and never a class prefix.
 *
 * A button that names its idle glyph in `data-kind` also gets the glyph swapped
 * (Pinterest's spinner and ✓/✗); one that doesn't just recolours, which is what
 * the Instagram and TikTok rails have always done.
 */
function setOverlayBtnState(btn, state) {
  // Clear any pending flash first. Without this a flash armed by an earlier click
  // fires mid-way through a later one, strips the `busy` class and defeats the
  // re-entrancy guard that class IS on Pinterest (pin-api.js checks it before
  // starting a download).
  if (btn.__swFlashTimer) {
    clearTimeout(btn.__swFlashTimer);
    btn.__swFlashTimer = null;
  }
  btn.classList.remove("busy", "ok", "err");
  if (state === "busy" || state === "ok" || state === "err") btn.classList.add(state);
  const kind = btn.dataset.kind;
  if (!kind) return;
  btn.innerHTML = overlayIcon(state === "ok" || state === "err" ? state : kind);
}

/**
 * Show how an action actually ended, then return the button to idle. The timer is
 * kept on the button so a second click restarts it — otherwise the first click's
 * timer resets a button the second one has just put back into busy.
 */
function flashOverlayBtn(btn, state) {
  setOverlayBtnState(btn, state);
  clearTimeout(btn.__swFlashTimer);
  btn.__swFlashTimer = setTimeout(() => {
    if (btn.isConnected) setOverlayBtnState(btn, "idle");
  }, OVERLAY_FLASH_MS);
}
// >>> inline:end
  // <<< inline:src/lib/shared/fbReelsDom.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fbReelsDom.js and run `npm run gen:inline`.

function fbTileCount(anchor) {
  const clone = anchor.cloneNode(true);
  clone.querySelectorAll('.sw-fbr, .fbw-acts, button').forEach(e => e.remove());
  return parseCount(clone.textContent.trim());
}

function fbPlayerMatches(record, video, routeId) {
  return !!record && record.id === routeId && !!video &&
    Number.isFinite(video.duration) && video.duration > 0 &&
    (!record.duration || Math.abs(record.duration - video.duration) < 1.5);
}
// >>> inline:end
  // A numeric profile's reels grid is /profile.php?id=…&sk=owner_reels — its path
  // is /profile.php, so the old path-and-"reels_tab" test said "not the reels tab"
  // and collect() returned an empty list on the exact URL the panel was pointed at.
  // isReelsGridUrl (inlined above) knows all three shapes.
  const isReelsTab = () => isReelsGridUrl(location.href);

  // The reels-tab has no <h1>; the profile name is a span inside a link back to
  // this same profile. Resolve the profile identifier from the URL (id= or the
  // vanity path segment), then take the highest name-like link that points to
  // it. Skips the follower/tab links that also point at the profile.
  const TAB_WORDS = /^(all|tudo|sobre|reels|fotos|mais|amigos|seguidores|posts|about|photos|more|friends|followers|videos|v[íi]deos)$/i;
  function ownerName() {
    const u = new URL(location.href);
    let key = u.searchParams.get("id");
    if (!key) {
      const m = u.pathname.match(/^\/([^/]+)/);
      if (m && m[1] !== "profile.php") key = m[1];
    }
    const main = document.querySelector('[role="main"]') || document;
    let best = null;
    for (const a of main.querySelectorAll("a[href]")) {
      const href = a.getAttribute("href") || "";
      if (key && href.indexOf(key) < 0) continue;
      let t = (a.textContent || "").replace(/\s+/g, " ").trim();
      t = t.replace(/\s*(conta verificada|verified account)$/i, "").trim();
      if (!t || t.length < 2 || t.length > 50) continue;
      if (TAB_WORDS.test(t) || /seguidor|follower|seguindo|following|\d/.test(t)) continue;
      const top = a.getBoundingClientRect().top;
      if (!best || top < best.top) best = { t, top };
    }
    return best ? best.t.slice(0, 60) : null;
  }

  const captured = new Map();
  const tiles = new Map();
  let previousTiles = new WeakMap();
  let surface = null;
  let routeChangedAt = 0;
  let savedIds = new Set();
  const jobs = new Map();
  const voices = new Map();
  const TILE_LINK = 'a[href*="/reel/"]';
  document.documentElement.dataset.swFbReelsUi = '1';

  function currentSurface() {
    const next = fbReelsSurface(location.href);
    if (next !== surface) {
      previousTiles = new WeakMap();
      if (surface?.startsWith('profile:')) {
        for (const a of document.querySelectorAll(TILE_LINK)) previousTiles.set(a,reelIdFromHref(a.getAttribute('href')));
      }
      surface = next; routeChangedAt = Date.now(); tiles.clear();
      document.querySelectorAll('.sw-fbr').forEach(removeReelUi);
      window.postMessage({ type: '__fbwReelRecordsRequest' }, location.origin);
    }
    return surface;
  }
  window.addEventListener('message', e => {
    if (disabled || e.source !== window || e.data?.type !== '__fbwReelRecords' || !Array.isArray(e.data.rows)) return;
    for (const r of e.data.rows.slice(0,1000)) {
      if (!/^\d{6,}$/.test(r?.id || '')) continue;
      captured.set(r.id, mergeFbReel(captured.get(r.id), r));
    }
    while (captured.size > 1000) captured.delete(captured.keys().next().value);
  });
  function collect() {
    if (!currentSurface()?.startsWith('profile:')) return [];
    const owner = ownerName();
    for (const a of document.querySelectorAll(TILE_LINK)) {
      const id = reelIdFromHref(a.getAttribute('href'));
      const img = a.querySelector('img');
      if (!id || !img || previousTiles.get(a) === id) continue;
      // Hidden-by-filter cards still belong to the collection and can be restored.
      const rect = a.getBoundingClientRect();
      if (!tiles.has(id) && !a.closest('[data-sw-hidden="1"]') && (rect.width < 100 || rect.height < 150)) continue;
      const prev = tiles.get(id);
      tiles.set(id, mergeFbReel(prev, { id, views: fbTileCount(a), thumb: img.currentSrc || img.src,
        authorName: owner, sourceUrl: `https://www.facebook.com/reel/${id}` }));
    }
    return [...tiles.values()].map(r => mergeFbReel(r, captured.get(r.id)));
  }
  const recordOf = id => mergeFbReel(tiles.get(id), captured.get(id));
  const sorter = makePageSorter({ storage: chromeQueryStorage(), storageKey: 'sw_fb_query', fields: FB_QUERY_FIELDS,
    linkSelector: TILE_LINK, keyOf: a => reelIdFromHref(a.getAttribute('href')),
    recordOf: id => tiles.has(id) ? recordOf(id) : null,
    linkOk: a => tiles.has(reelIdFromHref(a.getAttribute('href'))),
    routeOk: () => fbReelsSurface(location.href)?.startsWith('profile:'),
    routeKey: () => fbReelsSurface(location.href),
  });
  chrome.storage.local.get('fbw_saved').then(r => { savedIds = new Set(Object.keys(r.fbw_saved || {})); }).catch(() => {});
  chrome.storage.onChanged.addListener((c, area) => {
    if (area === 'local' && c.fbw_saved) savedIds = new Set(Object.keys(c.fbw_saved.newValue || {}));
  });

  async function performReelAction(id, action, language) {
    const scope = currentSurface();
    collect();
    if (!id || !(scope === `reel:${id}` || (scope?.startsWith('profile:') && tiles.has(id))))
      throw new Error('O reel mudou. Tente novamente.');
    const rec = recordOf(id);
    if (!rec.id) throw new Error('Os dados deste reel ainda estão carregando.');
    if (scope.startsWith('reel:')) {
      if (Date.now() - routeChangedAt < 400 || !fbPlayerMatches(rec, activeVideo(), id))
        throw new Error('Aguarde o player carregar este reel.');
    }
    if (action === 'copy') {
      await navigator.clipboard.writeText(`https://www.facebook.com/reel/${id}`);
      return { ok: true };
    }
    if (action === 'save') {
      const res = await chrome.runtime.sendMessage({type:'FBW_SAVED_TOGGLE',entry:fbReelEntry(rec)});
      if (!res?.ok) throw new Error(res?.error || 'Falha ao salvar');
      res.saved ? savedIds.add(id) : savedIds.delete(id);
      return res;
    }
    const running = voices.get(id);
    if (action === 'voice' && running && !['done','error','cancelled'].includes(running.phase)) {
      const res = await chrome.runtime.sendMessage({type:'FBW_CANCEL_VOICE',jobId:running.jobId});
      if (!res?.ok) throw new Error(res?.error || 'Falha ao cancelar');
      return res;
    }
    const key = `${id}:${action}`;
    if (jobs.get(key)?.busy) throw new Error('Este trabalho já está em andamento.');
    const msg = fbReelJob(rec, action, language || await getTxLang());
    jobs.set(key,{busy:true});
    try {
      const res = await chrome.runtime.sendMessage(msg);
      if (!res || res.ok === false || (['transcribe','voice'].includes(action) && !res.started))
        throw new Error(res?.error || 'Não foi possível iniciar a ação');
      if (action === 'voice' && !voices.has(id)) voices.set(id,{...msg,phase:'fetch',pct:0});
      if (action !== 'transcribe') jobs.set(key,{done:true});
      return {ok:true,...res};
    } catch(e) { jobs.set(key,{error:e.message}); throw e; }
  }
  function activeVideo() {
    return [...document.querySelectorAll('video')].map(v => {const r=v.getBoundingClientRect();return {v,area:Math.max(0,Math.min(r.bottom,innerHeight)-Math.max(r.top,0))*r.width};})
      .sort((a,b)=>b.area-a.area).find(r=>r.area>0)?.v || null;
  }

  // Auto-scroll the lazy grid to the bottom until it stops growing, then collect
  // every tile. FB's grid is scroll-driven, so this is the only way to get the
  // full reel list (the initial DOM holds ~20).
  async function harvest() {
    // FB appends the next batch after a network round-trip, which lags a short
    // poll — so wait generously per step and require several consecutive
    // no-growth reads before calling it done (a single slow batch mustn't end it).
    harvesting = true;
    cancelFlag = false;
    // Restore where the user actually was, instead of dumping them at the top of
    // the profile (the photos harvester already did this).
    const startY = window.scrollY;
    const harvestSurface = currentSurface();
    try {
      let stable = 0, prev = -1;
      for (let i = 0; i < 80 && stable < 5 && !cancelFlag && !disabled && currentSurface() === harvestSurface; i++) {
        window.scrollTo({ top: document.body.scrollHeight });
        await new Promise((r) => setTimeout(r, 1400));
        const n = document.querySelectorAll('a[href*="/reel/"]').length;
        stable = n === prev ? stable + 1 : 0;
        prev = n;
      }
      if (currentSurface() === harvestSurface) window.scrollTo({ top: startY });
      await new Promise((r) => setTimeout(r, 400));
      return collect();
    } finally {
      harvesting = false;
    }
  }

  // Spy reel count: the worker asks for one page at a time; the MAIN-world
  // capture does the request with the page's own modules and tokens.
  function spyReelsPage(cursor, collectionId) {
    return new Promise((resolve) => {
      const reqId = Date.now() + ":" + Math.random();
      const timer = setTimeout(() => { window.removeEventListener("message", onResult); resolve({ ok: false, error: "timeout" }); }, 60000);
      function onResult(e) {
        if (e.source !== window || e.data?.type !== "__fbwSpyReelsPageResult" || e.data.reqId !== reqId) return;
        clearTimeout(timer);
        window.removeEventListener("message", onResult);
        const { type, reqId: _id, ...result } = e.data;
        resolve(result);
      }
      window.addEventListener("message", onResult);
      window.postMessage({ type: "__fbwSpyReelsPage", reqId, cursor, collectionId }, location.origin);
    });
  }

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (disabled) return;
    if (msg?.type === "FBW_SPY_REELS_PAGE") {
      if (!location.hash.includes("socialmate-reels")) { sendResponse({ ok: false, error: "not_spy_tab" }); return; }
      spyReelsPage(msg.cursor || null, msg.collectionId || null).then(sendResponse);
      return true;
    }
    if (msg?.type === 'FBW_FB_REEL_ACTION') {
      performReelAction(String(msg.id), msg.action, msg.language).then(sendResponse, e => sendResponse({ok:false,error:e.message}));
      return true;
    }
    if (msg?.type === 'FBW_TRANSCRIBE_RESULT') jobs.set(`${msg.videoId}:transcribe`,msg.success ? {done:true} : {error:msg.error});
    if (msg?.type === 'FBW_VOICE_STATUS') voices.set(String(msg.videoId),msg);
    if (msg?.type === "FBW_FB_REELS_LIST") {
      sendResponse({
        records: collect(),
        owner: ownerName(),
        onReelsTab: isReelsTab(),
        harvesting,
        jobs: Object.fromEntries(jobs),
        voices: Object.fromEntries(voices),
      });
      return; // sync
    }
    if (msg?.type === "FBW_FB_REELS_HARVEST") {
      // Two presses used to drive two concurrent ~112s scroll loops over the same
      // grid, fighting each other for the scroll position.
      if (harvesting) {
        sendResponse({ records: collect(), owner: ownerName(), onReelsTab: isReelsTab(), harvesting: true });
        return; // sync
      }
      harvest().then(
        (records) =>
          sendResponse({ records, owner: ownerName(), onReelsTab: isReelsTab(), harvesting: false }),
        // Without a rejection handler a throw inside harvest() left the port open
        // until it timed out, sticking the panel's "harvesting" flag on.
        (e) =>
          sendResponse({
            records: collect(),
            owner: ownerName(),
            onReelsTab: isReelsTab(),
            harvesting: false,
            error: String(e?.message || e),
          }),
      );
      return true; // async
    }
    if (msg?.type === "FBW_FB_REELS_STOP") {
      cancelFlag = true;
      sendResponse({ ok: true });
      return; // sync
    }
  });
  // Keep actions tied to IDs, never response order or a stale record closure.
  const uiStyle = document.createElement('style');
  uiStyle.id = 'sw-fbr-style';
  uiStyle.textContent = `
.sw-fbr{position:absolute;inset:0;pointer-events:none;z-index:8;font:600 11px/1.3 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#fff}
.sw-fbr-actions{position:absolute;left:6px;top:6px;display:flex;flex-direction:column;gap:3px;pointer-events:auto}
.sw-fbr-player .sw-fbr-actions{top:52px;left:10px}
.sw-fbr-button{pointer-events:auto;display:grid;place-items:center;width:26px;height:26px;padding:0;border-radius:7px;color:#fff;background:rgba(17,20,32,.9);border:1px solid rgba(150,185,255,.35);cursor:pointer;font:600 10px/1 system-ui;box-shadow:0 2px 8px #0005}
.sw-fbr-button:hover,.sw-fbr-button:focus-visible{background:#263b59;outline:2px solid #88c0d0;outline-offset:1px}
.sw-fbr-button[data-saved="1"]{color:#facc15}.sw-fbr-button[data-saved="1"] svg{fill:#facc15}
.sw-fbr-button[data-state="busy"]{color:#88c0d0}.sw-fbr-button[data-state="error"]{color:#fb7185}.sw-fbr-button[data-state="done"]{color:#a3be8c}
.sw-fbr-stats{position:absolute;right:6px;bottom:30px;display:flex;flex-direction:column;align-items:flex-end;gap:3px;padding:5px 6px;background:rgba(17,20,32,.85);border:1px solid rgba(150,185,255,.3);border-radius:7px;pointer-events:auto;max-width:100px}
.sw-fbr-stats span{display:flex;align-items:center;gap:4px;white-space:nowrap}.sw-fbr-stats svg{width:12px;height:12px;flex-shrink:0}
.sw-fbr-player .sw-fbr-stats{bottom:55px;right:10px}
`;
  document.getElementById(uiStyle.id)?.remove();
  document.documentElement.appendChild(uiStyle);
  let overlayOn = true;
  chrome.storage.local.get('sw_fb_overlay').then(r=>{overlayOn=r.sw_fb_overlay!==false;}).catch(()=>{});
  chrome.storage.onChanged.addListener((c,area)=>{if(area==='local'&&c.sw_fb_overlay)overlayOn=c.sw_fb_overlay.newValue!==false;});
  chrome.runtime.sendMessage({type:'FBW_GET_VOICE_STATUS'}).then(r=>{if(r?.job)voices.set(String(r.job.videoId),r.job);}).catch(()=>{});
  watchTxLang();
  const ACTIONS = {
    save: ['save','Salvar na biblioteca'], download: ['dl','Baixar vídeo'], thumb: ['img','Baixar miniatura'],
    transcribe: ['tx','Transcrever vídeo'], voice: ['voice','Extrair voz (remover música)'], copy: ['link','Copiar link'],
  };
  function paintActions(wrap) {
    for(const b of wrap._buttons || []) {
      const id=wrap.dataset.id, action=b.dataset.action;
      const st=jobs.get(`${id}:${action}`);
      const voice=voices.get(id);
      let title=st?.error || ACTIONS[action][1];
      b.dataset.state=st?.busy?'busy':st?.error?'error':st?.done?'done':'';
      if(action==='save') {
        b.dataset.saved=savedIds.has(id)?'1':'';
        b.setAttribute('aria-pressed',String(savedIds.has(id)));
        title=savedIds.has(id)?'Salvo — remover da biblioteca':ACTIONS.save[1];
      }
      if(action==='voice' && voice) {
        const running=!['done','cancelled','error'].includes(voice.phase);
        const sig=`${voice.phase}:${voice.pct}`;
        if(b.dataset.voice!==sig){b.dataset.voice=sig;b.innerHTML=running?`${Math.round(voice.pct||0)}%`:overlayIcon('voice');}
        title=running?`Extraindo voz (${voice.pct||0}%) — cancelar`:voice.error|| (voice.phase==='done'?'Voz enviada aos downloads':ACTIONS.voice[1]);
        b.dataset.state=running?'busy':voice.phase==='error'?'error':voice.phase==='done'?'done':'';
      }
      if(action==='transcribe'&&st?.busy)title='Transcrevendo — acompanhe na biblioteca';
      b.title=title; b.setAttribute('aria-label',title);
    }
  }
  function statsHtml(rec) {
    const rows=[['eye',`${fmtCount(rec.views)}`,'Visualizações'],
      ['heart',fmtCount(rec.likes),'Curtidas'],['msg',fmtCount(rec.comments),'Comentários'],
      ['repost',rec.shares==null?'—':`${fmtCount(rec.shares)}`,'Compartilhamentos']];
    const er=fmtER(fbEngagement(rec));if(er)rows.push(['zap',`${er}`,'(curtidas + 4×comentários + 4×compartilhamentos) / views']);
    const velocity=fmtVelocity(viewsPerDay(rec.views,rec.taken_at));if(velocity)rows.push(['trend',`${velocity}`,'Views por dia desde a publicação']);
    const reach=FB_QUERY_FIELDS.reach.get(rec);if(reach!=null)rows.push(['tower',`${reach.toFixed(2)}×`,'Views / seguidores']);
    const date=fmtDate(rec.taken_at);if(date)rows.push(['cal',date,'Data de publicação']);
    return rows.map(([icon,text,title])=>`<span title="${title}">${overlayIcon(icon,12)}${text}</span>`).join('');
  }
  function removeReelUi(wrap) {
    wrap._buttons?.forEach(b=>b.remove());
    wrap.remove();
  }
  function decorateReel(anchor, rec, player=false) {
    const nativeRail=player?anchor.querySelector(':scope > .fbw-acts.reel'):null;
    if(player&&!nativeRail)return;
    let wrap=[...anchor.children].find(e=>e.classList.contains('sw-fbr'));
    if(wrap&&(wrap.dataset.id!==rec.id||wrap._buttons?.some(b=>!b.isConnected))){removeReelUi(wrap);wrap=null;}
    if(!wrap) {
      wrap=document.createElement('div'); wrap.className=`sw-fbr${player?' sw-fbr-player':''}`;wrap.dataset.id=rec.id;
      const acts=nativeRail||document.createElement('div');
      if(!player)acts.className='sw-fbr-actions';
      wrap._buttons=[];
      // The native extension rail already supplies these three player actions.
      const actions=player?['save','thumb','voice','copy']:Object.keys(ACTIONS);
      for(const action of actions) {
        const b=document.createElement('button');b.type='button';b.className='sw-fbr-button';b.dataset.action=action;b.innerHTML=overlayIcon(ACTIONS[action][0]);
        for(const event of ['pointerdown','pointerup','mousedown','mouseup','dblclick'])b.addEventListener(event,e=>{e.preventDefault();e.stopPropagation();});
        b.addEventListener('click',e=>{
          e.preventDefault();e.stopPropagation();
          const run=async lang=>{try{await performReelAction(wrap.dataset.id,action,lang);if(action==='copy')jobs.set(`${wrap.dataset.id}:copy`,{done:true});}
            catch(err){jobs.set(`${wrap.dataset.id}:${action}`,{error:err.message});}paintActions(wrap);};
          if(action==='transcribe')openTxLangMenu(b,run);else run();
        });
        if(action==='transcribe')enableTxBadge(b);
        wrap._buttons.push(b);
        if(player&&action==='save')acts.prepend(b);else acts.appendChild(b);
      }
      const stats=document.createElement('div');stats.className='sw-fbr-stats';
      if(!player)wrap.append(acts);
      wrap.append(stats);
      if(getComputedStyle(anchor).position==='static')anchor.style.position='relative';
      anchor.appendChild(wrap);
    }
    const html=statsHtml(rec),stats=wrap.querySelector('.sw-fbr-stats');
    if(stats._html!==html){stats._html=html;stats.innerHTML=html;}
    paintActions(wrap);
  }
  let lastSweep=0;
  function tick() {
    if(disabled || !chrome.runtime?.id) {clearInterval(uiTimer);sorter.destroy();return;}
    if(document.visibilityState!=='visible')return;
    const scope=currentSurface();
    if(scope&&Date.now()-lastSweep>3500){lastSweep=Date.now();window.postMessage({type:'__fbwReelRecordsSweep'},location.origin);}
    const list=collect();
    sorter.applyNow();
    if(!scope||!overlayOn){document.querySelectorAll('.sw-fbr').forEach(removeReelUi);return;}
    if(scope.startsWith('profile:')) {
      const byId=new Map(list.map(r=>[r.id,r]));
      for(const a of document.querySelectorAll(TILE_LINK)) {
        const rec=byId.get(reelIdFromHref(a.getAttribute('href')));if(!rec)continue;
        const rect=a.getBoundingClientRect();if(!rect.width||rect.bottom<0||rect.top>innerHeight)continue;
        a.querySelectorAll('.fbw-acts').forEach(e=>e.remove());
        decorateReel(a,rec);
      }
    } else if(Date.now()-routeChangedAt>=400) {
      const id=scope.slice(5),rec=recordOf(id),video=activeVideo();
      document.querySelectorAll('.sw-fbr-player').forEach(e=>{if(e.parentElement!==video?.parentElement)removeReelUi(e);});
      if(fbPlayerMatches(rec,video,id))decorateReel(video.parentElement,rec,true);
    }
  }
  const uiTimer=setInterval(tick,700);
  currentSurface();
  tick();

}
