// FB Reels-tab capture — isolated content script.
//
// Facebook's profile reels grid paginates OFF the main thread (a JSON.parse hook
// captures nothing — verified live), so unlike Instagram we read the grid tiles
// straight from the DOM: reel id, thumbnail, and the localized VIEW COUNT text.
// The first batch's comment/share counts are enriched from the initial embedded
// <script type="application/json"> blocks. Likes/reactions aren't on the grid at
// all. The tool serves this as a sortable list to the side panel; no on-page UI.
//
// Import-free (like ig/bridge.js): FB's CSP can break a CRXJS module loader, so
// this stays a direct content script. The pure helpers are INLINED from
// src/lib/shared/ at build time by `npm run gen:inline` — edit the source there,
// never the generated region below.

if (location.hostname.endsWith("facebook.com") && !window.__fbwFbReelsInit) {
  window.__fbwFbReelsInit = true;

  // ---- generation takeover. An extension reload re-injects into a FRESH isolated
  // world while this one keeps running (only its chrome.* dies), so the init guard
  // above cannot stop the old copy — its in-flight harvest would keep scrolling the
  // grid against the new one. Newer generation announces; older stands down. Same
  // pattern as comments-scrape.js / photos-scrape.js.
  const GEN = Date.now() + ":" + Math.random();
  let disabled = false;
  let harvesting = false;   // one scroll loop at a time
  let cancelFlag = false;   // FBW_FB_REELS_STOP / takeover
  window.addEventListener("message", (e) => {
    if (
      e.source === window &&
      e.data &&
      e.data.__fbwReelsTakeover &&
      e.data.__fbwReelsTakeover !== GEN &&
      !disabled
    ) {
      disabled = true;
      cancelFlag = true;
    }
  });
  window.postMessage({ __fbwReelsTakeover: GEN }, "*");

  // pure helpers — GENERATED from src/lib/shared/ (see that dir's README; this
  // script cannot import). Run `npm run gen:inline` after editing the source.
// <<< inline:src/lib/shared/counts.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/counts.js and run `npm run gen:inline`.
// Localized count parsing/formatting. INLINED into content scripts — see
// src/lib/shared/README.md before editing (no imports allowed in this file).

// Localized abbreviated-count multipliers. FB/IG/TikTok render counts abbreviated
// with a locale word or suffix: pt-br "mil"/"mi", en "K"/"M", plus other locales'
// short forms. A missing entry here means a real count parses as null, which is
// how the comment scraper used to lose reaction counts on non-pt/en UIs.
const COUNT_UNITS = {
  k: 1e3, mil: 1e3, rb: 1e3, tis: 1e3, tys: 1e3, tusen: 1e3,
  m: 1e6, mi: 1e6, mio: 1e6, jt: 1e6, mln: 1e6, mn: 1e6,
  b: 1e9, mrd: 1e9, bi: 1e9,
};

/**
 * Parse a localized count string into a number, or null.
 *   "14 mil" -> 14000   "1,5 mil" -> 1500   "1.2M" -> 1200000   "543" -> 543
 * When a unit word/suffix is present the numeric part is a small decimal, so a
 * comma is the decimal separator (pt-br "1,5"). Without a unit the value is a
 * plain integer whose separators are thousands groups and are stripped.
 */
function parseCount(text) {
  if (text == null) return null;
  if (typeof text === "number") return Number.isFinite(text) ? text : null;
  // A trailing period is an abbreviation mark in some locales ("1,2 mil.").
  const s = String(text).trim().toLowerCase().replace(/\s+/g, "").replace(/\.$/, "");
  if (!s) return null;
  const m = s.match(/^([\d.,]+)([a-zçã]+)?$/);
  if (!m) return null;
  const rawNum = m[1];
  const unitWord = m[2] || "";
  const mult = unitWord ? COUNT_UNITS[unitWord] : 1;
  if (unitWord && mult == null) return null; // unknown suffix → not a count
  // Separator rules, in order of how much they tell us:
  //   both present   → the LAST one is the decimal, the other is grouping.
  //                    "1.234,5" is 1234.5 (pt-BR) and "1,234.5" is 1234.5 (en).
  //   one + a unit   → that one is the decimal ("76,8 mil", "1.2M").
  //   one, no unit   → grouping; strip it ("1.234" is 1234, "76.800" is 76800).
  const hasDot = rawNum.includes(".");
  const hasComma = rawNum.includes(",");
  let norm;
  if (hasDot && hasComma) {
    const decimal = rawNum.lastIndexOf(".") > rawNum.lastIndexOf(",") ? "." : ",";
    const grouping = decimal === "." ? "," : ".";
    norm = rawNum.split(grouping).join("").replace(decimal, ".");
  } else if (unitWord) {
    norm = rawNum.replace(",", ".");
  } else {
    norm = rawNum.replace(/[.,]/g, "");
  }
  const num = parseFloat(norm);
  if (!Number.isFinite(num)) return null;
  return Math.round(num * mult);
}

// Display formatting. 964490 -> "964.5K". Null renders as an em dash rather than
// "0" — an unknown count and a zero count are different facts. Counts are stored
// raw and formatted here at render time.
function fmtCount(n) {
  if (n == null) return "—";
  if (n >= 1e6) return (n / 1e6).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1e3) return (n / 1e3).toFixed(1).replace(/\.0$/, "") + "K";
  return String(n);
}
// >>> inline:end

  const isReelsTab = () =>
    /[?&]sk=reels_tab/.test(location.search) ||
    /reels_tab/.test(location.href) ||
    /\/reels(\/|$)/.test(location.pathname);

  // The reels-tab has no <h1>; the profile name is a span inside a link back to
  // this same profile. Resolve the profile identifier from the URL (id= or the
  // vanity path segment), then take the highest name-like link that points to
  // it. Skips the follower/tab links that also point at the profile.
  const TAB_WORDS = /^(tudo|sobre|reels|fotos|mais|amigos|seguidores|posts|about|photos|more|friends|followers|videos|v[íi]deos)$/i;
  function ownerName() {
    const u = new URL(location.href);
    let key = u.searchParams.get("id");
    if (!key) {
      const m = u.pathname.match(/^\/([^/]+)/);
      if (m && m[1] !== "profile.php") key = m[1];
    }
    const main = document.querySelector('[role="main"]') || document;
    let best = null;
    for (const a of main.querySelectorAll("a[href]")) {
      const href = a.getAttribute("href") || "";
      if (key && href.indexOf(key) < 0) continue;
      let t = (a.textContent || "").replace(/\s+/g, " ").trim();
      t = t.replace(/\s*(conta verificada|verified account)$/i, "").trim();
      if (!t || t.length < 2 || t.length > 50) continue;
      if (TAB_WORDS.test(t) || /seguidor|follower|seguindo|following|\d/.test(t)) continue;
      const top = a.getBoundingClientRect().top;
      if (!best || top < best.top) best = { t, top };
    }
    return best ? best.t.slice(0, 60) : null;
  }

  // Grid tiles: <a href="/reel/ID"> with an <img> thumbnail and the view-count
  // text. Size-gated to skip the tab-bar "Reels" link and other small anchors.
  function scanTiles() {
    const out = new Map();
    for (const a of document.querySelectorAll('a[href*="/reel/"]')) {
      const r = a.getBoundingClientRect();
      if (r.width < 100 || r.height < 150) continue;
      const id = (a.getAttribute("href").match(/\/reel\/(\d+)/) || [])[1];
      if (!id) continue;
      const img = a.querySelector("img");
      const thumb = (img && (img.currentSrc || img.src)) || null;
      const viewText = (a.innerText || "").trim().split("\n")[0].trim();
      const views = parseCount(viewText);
      const prev = out.get(id) || {};
      out.set(id, {
        id,
        thumb: thumb || prev.thumb || null,
        views: views != null ? views : prev.views ?? null,
        viewText: viewText || prev.viewText || null,
      });
    }
    return out;
  }

  // Enrich the first batch from embedded JSON: each reel node carries a
  // `feedback` object (total_comment_count, share_count_reduced) and a `url`
  // that names the reel id. Paginated reels aren't here (off-thread) → null.
  // Facebook embeds megabytes of <script type="application/json">. Parsing + walking
  // all of it once per poll (every 3s) was hundreds of ms of main-thread block on any
  // FB tab. These blobs are static after load, so parse each node at most once and
  // keep only the reel-id → stats result. WeakMap so a removed script is collectible.
  const embeddedCache = new WeakMap();
  function statsFromScript(node) {
    const hit = embeddedCache.get(node);
    if (hit) return hit;
    const out = {};
    const t = node.textContent || "";
    if (t.indexOf("total_comment_count") < 0) { embeddedCache.set(node, out); return out; }
    let data;
    try { data = JSON.parse(t); } catch { embeddedCache.set(node, out); return out; }
    // Node budget as well as a depth cap: a depth limit alone does not bound a wide
    // blob, and one pathological payload could block the main thread. Mirrors
    // NODE_BUDGET in photos-capture.js.
    let budget = 60000;
    (function walk(o, depth) {
      if (!o || typeof o !== "object" || depth > 32) return;
      if (--budget < 0) return;
      if (Array.isArray(o)) { for (const v of o) walk(v, depth + 1); return; }
      if (o.feedback && o.url) {
        const rid = (String(o.url).match(/\/reel\/(\d+)/) || [])[1];
        if (rid && !out[rid]) {
          const fb = o.feedback;
          out[rid] = {
            comments: fb.total_comment_count != null ? Number(fb.total_comment_count) : null,
            shares: fb.share_count_reduced != null ? parseInt(fb.share_count_reduced, 10) : null,
          };
        }
      }
      for (const k in o) walk(o[k], depth + 1);
    })(data, 0);
    embeddedCache.set(node, out);
    return out;
  }
  function scanEmbeddedStats(ids) {
    const map = {};
    for (const node of document.querySelectorAll('script[type="application/json"]')) {
      const found = statsFromScript(node);
      for (const rid in found) if (ids.has(rid) && !map[rid]) map[rid] = found[rid];
    }
    return map;
  }

  function collect() {
    // The poll fires every 3s on ANY facebook.com tab. Off the reels grid there is
    // nothing to collect, so don't pay for scanTiles + the embedded-JSON walk.
    if (!isReelsTab()) return [];
    const tiles = scanTiles();
    const stats = scanEmbeddedStats(new Set(tiles.keys()));
    const records = [];
    for (const [id, rec] of tiles) {
      const st = stats[id] || {};
      records.push({
        id,
        thumb: rec.thumb,
        views: rec.views,
        viewText: rec.viewText,
        comments: st.comments ?? null,
        shares: st.shares ?? null,
        taken_at: null,
      });
    }
    return records;
  }

  // Auto-scroll the lazy grid to the bottom until it stops growing, then collect
  // every tile. FB's grid is scroll-driven, so this is the only way to get the
  // full reel list (the initial DOM holds ~20).
  async function harvest() {
    // FB appends the next batch after a network round-trip, which lags a short
    // poll — so wait generously per step and require several consecutive
    // no-growth reads before calling it done (a single slow batch mustn't end it).
    harvesting = true;
    cancelFlag = false;
    // Restore where the user actually was, instead of dumping them at the top of
    // the profile (the photos harvester already did this).
    const startY = window.scrollY;
    try {
      let stable = 0, prev = -1;
      for (let i = 0; i < 80 && stable < 5 && !cancelFlag && !disabled; i++) {
        window.scrollTo({ top: document.body.scrollHeight });
        await new Promise((r) => setTimeout(r, 1400));
        const n = document.querySelectorAll('a[href*="/reel/"]').length;
        stable = n === prev ? stable + 1 : 0;
        prev = n;
      }
      window.scrollTo({ top: startY });
      await new Promise((r) => setTimeout(r, 400));
      return collect();
    } finally {
      harvesting = false;
    }
  }

  chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
    if (disabled) return;
    if (msg?.type === "FBW_FB_REELS_LIST") {
      sendResponse({
        records: collect(),
        owner: ownerName(),
        onReelsTab: isReelsTab(),
        harvesting,
      });
      return; // sync
    }
    if (msg?.type === "FBW_FB_REELS_HARVEST") {
      // Two presses used to drive two concurrent ~112s scroll loops over the same
      // grid, fighting each other for the scroll position.
      if (harvesting) {
        sendResponse({ records: collect(), owner: ownerName(), onReelsTab: isReelsTab(), harvesting: true });
        return; // sync
      }
      harvest().then(
        (records) =>
          sendResponse({ records, owner: ownerName(), onReelsTab: isReelsTab(), harvesting: false }),
        // Without a rejection handler a throw inside harvest() left the port open
        // until it timed out, sticking the panel's "harvesting" flag on.
        (e) =>
          sendResponse({
            records: collect(),
            owner: ownerName(),
            onReelsTab: isReelsTab(),
            harvesting: false,
            error: String(e?.message || e),
          }),
      );
      return true; // async
    }
    if (msg?.type === "FBW_FB_REELS_STOP") {
      cancelFlag = true;
      sendResponse({ ok: true });
      return; // sync
    }
  });
}
