// MAIN world: read the search requests Facebook already makes, including @defer
// lines. Only compact per-video records cross into the isolated content script.
(function () {
  if (window.__fbwFbVideoCapture) return;
  window.__fbwFbVideoCapture = true;
  // <<< inline:src/lib/shared/fbVideoMedia.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fbVideoMedia.js and run `npm run gen:inline`.
// Facebook search hydration and streamed GraphQL → bounded, per-video records.
// Inlined into MAIN capture and the isolated transcription script.
function fbSearchVideosSurface(path) {
  return /^\/search\/(top|posts|videos)\/?$/.test(path);
}

function fbMediaUrl(value) {
  if (typeof value !== "string" || value.length > 16000) return null;
  try {
    const u = new URL(value);
    return u.protocol === "https:" && u.hostname.endsWith(".fbcdn.net") ? value : null;
  } catch { return null; }
}

function fbCoverKey(url) {
  const safe = fbMediaUrl(url);
  // CDN hosts and crop/signature parameters vary; the asset path does not.
  return safe ? new URL(safe).pathname : null;
}

function mergeFbVideo(prev, next) {
  return {
    id: next.id,
    durationS: next.durationS || prev?.durationS || null,
    permalink: next.permalink || prev?.permalink || null,
    audio: next.audio || prev?.audio || null,
    progressive: next.progressive || prev?.progressive || null,
    thumbs: [...new Set([...(prev?.thumbs || []), ...(next.thumbs || [])])].slice(-12),
    captions: [...new Map([...(prev?.captions || []), ...(next.captions || [])].map(c => [c.lang, c])).values()].slice(-30),
  };
}

function collectFbVideos(root) {
  const records = new Map();
  const seen = new WeakSet();
  let budget = 180000;
  function walk(o, depth) {
    if (!o || typeof o !== "object" || depth > 60 || budget-- <= 0 || seen.has(o)) return;
    seen.add(o);
    if (o.__typename === "Video" && /^\d{6,}$/.test(o.id || "")) {
      const result = o.videoDeliveryResponseFragment?.videoDeliveryResponseResult;
      const legacy = o.videoDeliveryLegacyFields;
      const thumbs = [o.first_frame_thumbnail, o.preferred_thumbnail?.image?.uri,
        o.thumbnailImage?.uri, o.image?.uri, o.imageLargeAspect?.uri,
        o.imageFlexible?.uri, o.imageServerSelected?.uri].map(fbMediaUrl).filter(Boolean);
      let audio = null;
      let progressive = null;
      for (const row of result?.progressive_urls || []) {
        const url = fbMediaUrl(row.progressive_url);
        if (url && (!progressive || /hd/i.test(row.metadata?.quality || ""))) progressive = url;
      }
      for (const row of result?.dash_manifests || []) {
        if (typeof row.manifest_xml !== "string") continue;
        try {
          const xml = new DOMParser().parseFromString(row.manifest_xml, "application/xml");
          for (const rep of xml.querySelectorAll("Representation")) {
            const mime = rep.getAttribute("mimeType") || rep.parentElement?.getAttribute("mimeType");
            if (mime?.startsWith("audio/")) audio ||= fbMediaUrl(rep.querySelector("BaseURL")?.textContent?.trim());
          }
        } catch { /* Keep progressive/fallback when a manifest is malformed. */ }
      }
      // Older delivery payloads still occur on other Facebook surfaces.
      if (legacy) {
        progressive ||= fbMediaUrl(legacy.browser_native_hd_url) || fbMediaUrl(legacy.browser_native_sd_url);
      }
      const captions = (o.video_available_captions_locales || []).flatMap(c => {
        const url = fbMediaUrl(c.captions_url);
        return url && typeof c.locale === "string" ? [{ url, lang: c.locale.slice(0, 20) }] : [];
      });
      let permalink = null;
      try {
        const u = new URL(o.permalink_url);
        if (u.protocol === "https:" && /(^|\.)facebook\.com$/.test(u.hostname) &&
          (u.pathname.includes(`/reel/${o.id}`) || u.pathname.includes(`/videos/${o.id}`) || u.searchParams.get("v") === o.id))
          permalink = u.origin + u.pathname + (u.searchParams.get("v") ? `?v=${o.id}` : "");
      } catch {}
      const durationS = Number.isFinite(o.playable_duration_in_ms) && o.playable_duration_in_ms > 0
        ? o.playable_duration_in_ms / 1000 : null;
      if (audio || progressive || thumbs.length || durationS || captions.length) {
        const row = { id: o.id, durationS, permalink, audio, progressive, thumbs, captions };
        records.set(o.id, mergeFbVideo(records.get(o.id), row));
      }
    }
    for (const v of Object.values(o)) walk(v, depth + 1);
  }
  walk(root, 0);
  return [...records.values()];
}

function parseFbVideoResponse(text) {
  const records = new Map();
  for (const line of String(text).split("\n")) {
    try {
      const data = JSON.parse(line.replace(/^for\s*\(;;\);\s*/, ""));
      for (const row of collectFbVideos(data)) records.set(row.id, mergeFbVideo(records.get(row.id), row));
    } catch { /* A broken deferred part must not discard the other parts. */ }
  }
  return [...records.values()];
}

function matchFbVideo(records, hint = {}) {
  const rows = [...records];
  const covers = new Set((hint.thumbs || []).map(fbCoverKey).filter(Boolean));
  if (hint.id) {
    const record = rows.find(r => r.id === hint.id);
    // A caption may link to a different reel. A conflicting cover vetoes that
    // link instead of silently using the linked video's audio for this post.
    return record && (!covers.size || record.thumbs.some(t => covers.has(fbCoverKey(t)))) ? record : null;
  }
  if (!covers.size) return null; // duration/recency alone is never an identity
  const matches = rows.filter(r => r.thumbs.some(t => covers.has(fbCoverKey(t))) &&
    !(r.durationS && Number.isFinite(hint.durationS) && Math.abs(r.durationS - hint.durationS) > 1.5));
  return matches.length === 1 ? matches[0] : null;
}

function fbCaptionFor(record, language) {
  // Auto is resolved by Whisper from the post text. Do not silently substitute
  // a translated or unknown-language caption when the user chose Auto/BR/EN.
  const lang = language === "br" || language === "pt" ? "pt" : language === "en" ? "en" : null;
  return lang ? record?.captions?.find(c => c.lang.split(/[-_]/)[0].toLowerCase() === lang) || null : null;
}
// >>> inline:end

  // <<< inline:src/lib/shared/counts.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/counts.js and run `npm run gen:inline`.
// Localized count parsing/formatting. INLINED into content scripts — see
// src/lib/shared/README.md before editing (no imports allowed in this file).

// Localized abbreviated-count multipliers. FB/IG/TikTok render counts abbreviated
// with a locale word or suffix: pt-br "mil"/"mi", en "K"/"M", plus other locales'
// short forms. A missing entry here means a real count parses as null, which is
// how the comment scraper used to lose reaction counts on non-pt/en UIs.
const COUNT_UNITS = {
  k: 1e3, mil: 1e3, rb: 1e3, tis: 1e3, tys: 1e3, tusen: 1e3,
  m: 1e6, mi: 1e6, mio: 1e6, jt: 1e6, mln: 1e6, mn: 1e6,
  b: 1e9, mrd: 1e9, bi: 1e9,
};

/**
 * Parse a localized count string into a number, or null.
 *   "14 mil" -> 14000   "1,5 mil" -> 1500   "1.2M" -> 1200000   "543" -> 543
 * When a unit word/suffix is present the numeric part is a small decimal, so a
 * comma is the decimal separator (pt-br "1,5"). Without a unit the value is a
 * plain integer whose separators are thousands groups and are stripped.
 */
function parseCount(text) {
  if (text == null) return null;
  if (typeof text === "number") return Number.isFinite(text) ? text : null;
  // A trailing period is an abbreviation mark in some locales ("1,2 mil.").
  const s = String(text).trim().toLowerCase().replace(/\s+/g, "").replace(/\.$/, "");
  if (!s) return null;
  const m = s.match(/^([\d.,]+)([a-zçã]+)?$/);
  if (!m) return null;
  const rawNum = m[1];
  const unitWord = m[2] || "";
  const mult = unitWord ? COUNT_UNITS[unitWord] : 1;
  if (unitWord && mult == null) return null; // unknown suffix → not a count
  // Separator rules, in order of how much they tell us:
  //   both present   → the LAST one is the decimal, the other is grouping.
  //                    "1.234,5" is 1234.5 (pt-BR) and "1,234.5" is 1234.5 (en).
  //   one + a unit   → that one is the decimal ("76,8 mil", "1.2M").
  //   one, no unit   → grouping; strip it ("1.234" is 1234, "76.800" is 76800).
  const hasDot = rawNum.includes(".");
  const hasComma = rawNum.includes(",");
  let norm;
  if (hasDot && hasComma) {
    const decimal = rawNum.lastIndexOf(".") > rawNum.lastIndexOf(",") ? "." : ",";
    const grouping = decimal === "." ? "," : ".";
    norm = rawNum.split(grouping).join("").replace(decimal, ".");
  } else if (unitWord) {
    norm = rawNum.replace(",", ".");
  } else {
    norm = rawNum.replace(/[.,]/g, "");
  }
  const num = parseFloat(norm);
  if (!Number.isFinite(num)) return null;
  return Math.round(num * mult);
}

// Display formatting. 964490 -> "964.5K". Null renders as an em dash rather than
// "0" — an unknown count and a zero count are different facts. Counts are stored
// raw and formatted here at render time.
function fmtCount(n) {
  if (n == null) return "—";
  if (n >= 1e6) return (n / 1e6).toFixed(1).replace(/\.0$/, "") + "M";
  if (n >= 1e3) return (n / 1e3).toFixed(1).replace(/\.0$/, "") + "K";
  return String(n);
}
// >>> inline:end
  // <<< inline:src/lib/shared/fbReelsData.js
// GENERATED by scripts/gen-inline.mjs — do not edit here.
// Edit src/lib/shared/fbReelsData.js and run `npm run gen:inline`.
// Compact Facebook reel records from hydration and streamed GraphQL. No requests.

function fbReelsSurface(href) {
  try {
    const u = new URL(href, "https://www.facebook.com");
    if (!/(^|\.)facebook\.com$/.test(u.hostname)) return null;
    const reel = u.pathname.match(/^\/reel\/(\d+)/);
    if (reel) return `reel:${reel[1]}`;
    if (u.pathname === '/profile.php' && /^(reels_tab|owner_reels)$/.test(u.searchParams.get('sk')) && /^\d+$/.test(u.searchParams.get('id')))
      return `profile:${u.searchParams.get('id')}`;
    const profile = u.pathname.match(/^\/([^/]+)\/(?:reels|reels_tab)\/?$/);
    return profile ? `profile:${profile[1].toLowerCase()}` : null;
  } catch { return null; }
}

function mergeFbReel(prev, next) {
  const out = { ...prev };
  for (const [k, v] of Object.entries(next || {})) {
    if (v != null && v !== '' && (!Array.isArray(v) || v.length)) out[k] = v;
    else if (!(k in out)) out[k] = v;
  }
  return out;
}

function fbReelUrlId(url) {
  try {
    const u = new URL(url, 'https://www.facebook.com');
    return /(^|\.)facebook\.com$/.test(u.hostname) ? u.pathname.match(/^\/reel\/(\d+)/)?.[1] || null : null;
  } catch { return null; }
}

function parseFbReels(input, activeId = null) {
  const parts = typeof input === 'string' ? input.split('\n').flatMap(line => {
    try { return [JSON.parse(line.replace(/^for\s*\(;;\);\s*/, ''))]; } catch { return []; }
  }) : Array.isArray(input) ? input : [input];
  const records = new Map(), videos = new Map(), edgeIds = new Map();
  const empty = id => ({ id, views: null, likes: null, comments: null, shares: null,
    taken_at: null, created_at: null, duration: null, caption: null, authorName: null,
    authorId: null, authorUrl: null, thumb: null, progressive: null, audio: null, captions: [],
    sourceUrl: `https://www.facebook.com/reel/${id}`, media_type: 'video' });
  function put(id, row) {
    if (!/^\d{6,}$/.test(id || '')) return;
    records.set(id, mergeFbReel(records.get(id) || empty(id), { ...row, id }));
  }
  function stats(o) {
    return { likes: parseCount(o.fb_reel_react_button?.story?.feedback?.likers?.count),
      comments: parseCount(o.feedback?.total_comment_count), shares: parseCount(o.feedback?.share_count_reduced) };
  }
  let budget = 220000;
  function walk(o, depth = 0) {
    if (!o || typeof o !== 'object' || depth > 60 || --budget < 0) return;
    if (o.aggregated_fb_shorts?.edges) {
      o.aggregated_fb_shorts.edges.forEach((e, i) => {
        const id = e.profile_reel_node?.node?.attachments?.find(a => a.media?.__typename === 'Video')?.media?.id;
        if (id) edgeIds.set(i, id);
      });
    }
    const media = o.attachments?.find?.(a => a.media?.__typename === 'Video')?.media;
    if (media?.id && (o.__typename === 'Story' || o.actors || o.creation_time)) {
      const actor = o.actors?.[0];
      put(media.id, { taken_at: Number.isFinite(o.creation_time) ? o.creation_time : null,
        caption: o.message?.text || null, authorName: actor?.name || null,
        authorId: actor?.id || null, authorUrl: actor?.id ? `https://www.facebook.com/profile.php?id=${actor.id}` : null });
    }
    const id = fbReelUrlId(o.url);
    if (id && (o.feedback || o.fb_reel_react_button)) put(id, stats(o));
    if (o.__typename === 'Video' && /^\d{6,}$/.test(o.id || '')) {
      const delivery = collectFbVideos(o).find(r => r.id === o.id);
      videos.set(o.id, mergeFbReel(videos.get(o.id), {
        id: o.id, views: parseCount(o.play_count_reduced ?? o.play_count),
        created_at: Number.isFinite(o.created_time) ? o.created_time : null,
        duration: delivery?.durationS || null, thumb: delivery?.thumbs?.[0] || null,
        progressive: delivery?.progressive || null, audio: delivery?.audio || null, captions: delivery?.captions || [],
        authorName: o.owner?.name || null, authorId: o.owner?.id || null,
        authorUrl: o.owner?.id ? `https://www.facebook.com/profile.php?id=${o.owner.id}` : null,
      }));
    }
    for (const v of Object.values(o)) if (typeof v === 'object') walk(v, depth + 1);
  }
  // Base connections must be indexed before any out-of-order deferred part.
  for (const p of parts) if (!p?.path) walk(p);
  for (const p of parts) {
    if (!p?.path) continue;
    const at = p.path.indexOf('edges');
    const id = at >= 0 ? edgeIds.get(p.path[at + 1]) : null;
    const urlId = fbReelUrlId(p.data?.url);
    if (id && urlId && id !== urlId) continue;
    if (id) put(id, stats(p.data || {}));
    walk(p.data);
  }
  if (activeId && videos.has(activeId)) put(activeId, {});
  for (const [id, row] of records) {
    const merged = mergeFbReel(videos.get(id), row);
    // Null placeholders in a partial story must not erase the video delivery.
    records.set(id, merged);
  }
  return [...records.values()];
}
// >>> inline:end
  const reels = new Map();
  function rememberReels(rows) {
    const fresh = [];
    for (const row of rows) {
      const next = mergeFbReel(reels.get(row.id), row);
      if (JSON.stringify(reels.get(row.id)) === JSON.stringify(next)) continue;
      reels.delete(row.id); reels.set(row.id, next); fresh.push(next);
    }
    while (reels.size > 1000) reels.delete(reels.keys().next().value);
    if (fresh.length) window.postMessage({ type: "__fbwReelRecords", rows: fresh }, location.origin);
  }
  const records = new Map();
  let route = location.href;
  let swept = new WeakSet();
  function currentRoute() {
    if (route !== location.href) {
      route = location.href;
      // Search responses can arrive BEFORE history updates. Retain the bounded
      // ID/cover index across routes so the destination can replay those rows.
      // Isolated consumers clear their view and only match their current DOM.
      swept = new WeakSet();
    }
    return route;
  }
  function publish(rows) {
    if (!rows.length) return;
    window.postMessage({ type: "__fbwVideoRecords", route, rows }, location.origin);
  }
  function remember(rows) {
    const fresh = [];
    for (const row of rows) {
      const next = mergeFbVideo(records.get(row.id), row);
      if (JSON.stringify(records.get(row.id)) === JSON.stringify(next)) continue;
      records.delete(row.id);
      records.set(row.id, next);
      fresh.push(next);
    }
    while (records.size > 200) records.delete(records.keys().next().value);
    publish(fresh);
  }
  function sweep() {
    currentRoute();
    if (!fbSearchVideosSurface(location.pathname) && !fbReelsSurface(location.href)) return;
    for (const script of document.querySelectorAll('script[type="application/json"]')) {
      if (swept.has(script)) continue;
      swept.add(script);
      try {
        const text = script.textContent || '';
        if (!/videoDelivery|total_comment_count|aggregated_fb_shorts|"Video"/.test(text)) continue;
        const data = JSON.parse(text);
        if (fbSearchVideosSurface(location.pathname)) remember(collectFbVideos(data));
        else rememberReels(parseFbReels(data, fbReelsSurface(location.href)?.split('reel:')[1]));
      } catch {}
    }
  }
  const originalOpen = XMLHttpRequest.prototype.open;
  const originalSend = XMLHttpRequest.prototype.send;
  const urls = new WeakMap();
  XMLHttpRequest.prototype.open = function (method, url) {
    urls.set(this, String(url));
    return originalOpen.apply(this, arguments);
  };
  XMLHttpRequest.prototype.send = function () {
    currentRoute();
    const searchRequest = typeof arguments[0] === "string" && /fb_api_req_friendly_name=SearchComet/.test(arguments[0]);
    const reelRequest = typeof arguments[0] === "string" && /fb_api_req_friendly_name=[^&]*(?:Reels|Reel|Shorts)/.test(arguments[0]);
    const reelsHere = !!fbReelsSurface(location.href);
    if ((reelRequest || reelsHere || searchRequest || fbSearchVideosSurface(location.pathname)) && /\/api\/graphql\/?(?:\?|$)/.test(urls.get(this) || "")) {
      this.addEventListener("load", () => {
        // SPA search starts its request before committing the new URL. Keep
        // the returned videos on the destination search; consumers join by
        // exact ID/cover, never by response order or recency.
        if (!searchRequest && !reelRequest && !reelsHere && !fbSearchVideosSurface(location.pathname)) return;
        currentRoute();
        try {
          const text = this.responseText;
          if (!searchRequest && (reelRequest || reelsHere)) rememberReels(parseFbReels(text, fbReelsSurface(location.href)?.split('reel:')[1]));
          else if (text.includes('videoDelivery')) remember(parseFbVideoResponse(text));
        } catch {}
      }, { once: true });
    }
    return originalSend.apply(this, arguments);
  };
  window.addEventListener("message", e => {
    if (e.source !== window) return;
    if (e.data?.type === "__fbwReelRecordsSweep") { sweep(); return; }
    if (e.data?.type === "__fbwReelRecordsRequest") {
      sweep();
      window.postMessage({ type: "__fbwReelRecords", rows: [...reels.values()] }, location.origin);
      return;
    }
    if (e.data?.type !== "__fbwVideoRecordsRequest") return;
    sweep();
    publish([...records.values()]);
  });
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", sweep, { once: true });
  else sweep();
})();
