#!/usr/bin/env node
// Inline the shared pure helpers into the import-free content scripts.
//
// WHY THIS EXISTS
// An ES `import` in a content script makes CRXJS emit a dynamic-import loader
// (`await import(chrome.runtime.getURL(...))`) instead of a self-contained IIFE —
// visible in dist/manifest.json, where content.js and pin-api.js get *-loader.js
// files and the other nine get bundles. In a MAIN-world script that dynamic import
// is subject to the PAGE's CSP, which on Facebook/Instagram can kill it and
// silently disable capture. So the capture scripts must not import.
//
// The old workaround was hand-copying the helpers with a "mirror of src/lib/x.js"
// comment. Nothing enforced it and the copies drifted — notably
// comments-scrape.js's parseCount, which had 5 locale unit words against the
// tested lib's 13, so "1,2 rb" parsed to null on the page while tests stayed green.
//
// Now: one canonical source under src/lib/shared/ (unit-tested, re-exported by the
// panel libs) is copied verbatim into a marked region of each content script.
//
//   npm run gen:inline           write the regions
//   npm run gen:inline -- --check  exit 1 if any region is stale (build + tests use this)
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// target content script -> shared modules to inline, in order.
// Order matters: fbCommentParse's parseReactions calls parseCount from counts.js.
const TARGETS = {
  "src/content/fb/comments-scrape.js": [
    "src/lib/shared/counts.js",
    "src/lib/shared/fbCommentParse.js",
  ],
  "src/content/fb/reels-capture.js": ["src/lib/shared/counts.js"],
  "src/content/fb/feed-filter.js": [
    "src/lib/shared/counts.js",
    "src/lib/shared/fbCounts.js",
    "src/lib/shared/feedFilter.js",
  ],
  "src/content/transcription/inject.js": [
    "src/lib/shared/fbCounts.js",
    "src/lib/shared/fbPermalink.js",
    "src/lib/shared/captureIdentity.js",
    "src/lib/shared/txLang.js",
    "src/lib/shared/railTarget.js",
  ],
  "src/content/fb/photos-scrape.js": ["src/lib/shared/fbPhotoIds.js"],
  "src/content/ig/bridge.js": [
    "src/lib/shared/counts.js",
    "src/lib/shared/igSurface.js",
    "src/lib/shared/savedEntry.js",
    "src/lib/shared/filenames.js",
    "src/lib/shared/igFilters.js",
    "src/lib/shared/igFormat.js",
    "src/lib/shared/overlayUi.js",
    "src/lib/shared/txLang.js",
  ],
  "src/content/ig/main-world.js": ["src/lib/shared/igFilters.js", "src/lib/shared/igEnrich.js", "src/lib/shared/igSurface.js"],
  "src/content/tt/tt-relay.js": [
    "src/lib/shared/counts.js",
    "src/lib/shared/savedEntry.js",
    "src/lib/shared/overlayUi.js",
    "src/lib/shared/txLang.js",
  ],
};

const BEGIN = (mod) => `// <<< inline:${mod}`;
const END = "// >>> inline:end";

// A shared module may import from a SIBLING shared module and nothing else. That
// keeps it valid ESM for the panel and the unit tests, while the generator strips
// the import line — the sibling is inlined into the same content script, so the
// declaration is already in scope there.
const SIBLING_IMPORT = /^import\s*\{([^}]*)\}\s*from\s*"\.\/([\w.-]+\.js)";?[ \t]*\n/gm;

function siblingDeps(modPath) {
  const src = readFileSync(resolve(ROOT, modPath), "utf8");
  return [...src.matchAll(SIBLING_IMPORT)].map((m) => `src/lib/shared/${m[2]}`);
}

// Turn a shared module's source into inlinable statements: drop sibling imports,
// strip the `export` keyword, keep everything else byte-for-byte so the page runs
// exactly what the tests test.
function inlinable(modPath) {
  const src = readFileSync(resolve(ROOT, modPath), "utf8");
  const stripped = src.replace(SIBLING_IMPORT, "");
  const bad = stripped.match(/^\s*(?:import\s|export\s+default\b|export\s*\{)/m);
  if (bad)
    throw new Error(
      `${modPath}: a shared module may only import from a sibling in src/lib/shared/ ` +
        `and may not re-export (found ${JSON.stringify(bad[0].trim())}). See src/lib/shared/README.md`,
    );
  return stripped.replace(/^export\s+/gm, "").trimEnd();
}

function renderRegion(mod) {
  return [
    BEGIN(mod),
    `// GENERATED by scripts/gen-inline.mjs — do not edit here.`,
    `// Edit ${mod} and run \`npm run gen:inline\`.`,
    inlinable(mod),
    END,
  ].join("\n");
}

function applyTo(targetPath, mods) {
  const abs = resolve(ROOT, targetPath);
  let src = readFileSync(abs, "utf8");
  // A module's sibling deps must be inlined into the same script, and BEFORE it —
  // the stripped import leaves a bare reference that has to already be in scope.
  mods.forEach((mod, i) => {
    for (const dep of siblingDeps(mod)) {
      const at = mods.indexOf(dep);
      if (at < 0)
        throw new Error(
          `${targetPath}: inlines ${mod}, which imports ${dep} — add ${dep} to this target's module list in scripts/gen-inline.mjs`,
        );
      if (at > i)
        throw new Error(
          `${targetPath}: ${dep} must be listed before ${mod} (a stripped sibling import needs its declarations already in scope)`,
        );
    }
  });
  for (const mod of mods) {
    const begin = BEGIN(mod);
    const bi = src.indexOf(begin);
    if (bi < 0)
      throw new Error(
        `${targetPath}: missing region marker ${JSON.stringify(begin)} — add it (and a matching ${JSON.stringify(END)}) where the helpers belong.`,
      );
    const ei = src.indexOf(END, bi);
    if (ei < 0)
      throw new Error(`${targetPath}: region ${mod} has no closing ${END}`);
    src = src.slice(0, bi) + renderRegion(mod) + src.slice(ei + END.length);
  }
  return { abs, src };
}

const check = process.argv.includes("--check");
let stale = 0;
let written = 0;

for (const [target, mods] of Object.entries(TARGETS)) {
  const { abs, src } = applyTo(target, mods);
  const current = readFileSync(abs, "utf8");
  if (current === src) continue;
  if (check) {
    stale++;
    console.error(`stale inline region: ${target}`);
  } else {
    writeFileSync(abs, src);
    written++;
    console.log(`updated ${target}`);
  }
}

if (check && stale) {
  console.error(
    `\n${stale} content script(s) carry a stale copy of a src/lib/shared/ helper.\nRun \`npm run gen:inline\` and commit the result.`,
  );
  process.exit(1);
}
console.log(
  check
    ? "inline regions up to date"
    : written
      ? `${written} file(s) updated`
      : "inline regions already up to date",
);
